microsoft/BotFramework-Composer

Composer/packages/server/package.json
Composer/packages/server/src/models/environment/interface.ts
Composer/packages/server/src/services/asset.ts
Composer/packages/server/src/settings/index.ts
Composer/yarn.lock

1. Add [cross-env](https://www.npmjs.com/package/cross-env) to set environment variables for different platforms.
2. In development "import settings from '../settings/settings';" will import setting.json. This will make some path can't be found. so I renamed the setting.ts to index.ts.

fix: yarn start:dev can't work in windows

---

Composer/packages/server/src/server.ts

Adding https://login.microsoftonline.com and https://*.botframework.com to the composer server side content security policy to allow login refresh to work
Without it, the hosted composer session can not refresh the login token.
For release build the initial token is valid for 2 hours. 
For scratch devportal, the token is only valid for 20 minutes.
Notice, since the token is saved in the local store and **NOT** refreshed when composer refreshes, the user may encounter the failure to refresh login less predictable from session to session.
1. users opens composer at 10am, works on it, close it, goto lunch
1. user comes back at 11:45, reopen the composer, works for 15 minutes, then hit the 'cant refresh login' bug.
User can workaround this by refresh the composer after the token expires.
If …

add login.microsoftonline.com and *.botframework.com to CSP frame-src

---

Composer/packages/server/src/models/connector/csharpBotConnector.ts

Check error.
Closes https://github.com/microsoft/BotFramework-Composer/issues/1535

Fix start bot failure after switching reconginzer from Luis to None

---

Composer/packages/client/src/CreationFlow/DefineConversation/index.js
Composer/packages/client/src/CreationFlow/LocationBrowser/FileSelector.tsx
Composer/packages/client/src/CreationFlow/LocationBrowser/LocationSelectContent.tsx
Composer/packages/client/src/CreationFlow/index.js

1. When creating a new bot, we should compare the name with the bots existing in current folder.
2. For user's convenience, we should show up all bots existing in current folder.
Closes #1445 #1372 

show bot name when creating bot

---

Composer/README.md

I submitted the following pull request to stable branch.
So, I resubmit to master branch as @a-b-r-o-w-n said.
[Fix docs link #1549](https://github.com/microsoft/BotFramework-Composer/pull/1549)
I found the following link is the below 404.
So, I guess the correct link is "https://github.com/microsoft/BotFramework-Composer/blob/stable/toc.md".

Fix docs link

---

Composer/packages/lib/shared/src/constant.ts

This PR is to fix this [Issue](https://github.com/microsoft/BotFramework-Composer/issues/1538)
[Ref](https://github.com/microsoft/BotFramework-Composer/pull/1558)
**Root Cause** 
This Issue is because the botproject(runtime) read qna.endpointkey from disk before, and we omit it as a fixed sensitive property. But It's more like a self-defined property and no need to omit. 
closes #1538
During the QnaMaker trace, it won't show "Object not set to instance of an object" anymore.

fix: QnA Maker EndpointKey is null Issue

---

Composer/cypress/integration/LGPage.spec.js
Composer/cypress/integration/Onboarding.spec.js
Composer/cypress/support/commands.js

1. Onboarding is set disabled by default. Make it enable before testing.
2. LgPage can't find the button.
closes #1592 

fix: E2E test Onboarding and LgPage

---

Composer/packages/extensions/visual-designer/demo/src/samples/todo/AddToDo.json
Composer/packages/extensions/visual-designer/demo/src/samples/todo/ClearToDos.json
Composer/packages/extensions/visual-designer/demo/src/samples/todo/DeleteToDo.json
Composer/packages/extensions/visual-designer/demo/src/samples/todo/ShowToDos.json
Composer/packages/extensions/visual-designer/demo/src/samples/todo/ToDoBot.main.json
Composer/packages/extensions/visual-designer/demo/src/stories/VisualEditorDemo.js
Composer/packages/extensions/visual-designer/src/index.tsx

**How does the redraw promblem happen**
My observation was based on two scenarios: 1. change focus state by clicking a node 2. change node data by adding/deleting a node.
According to the profiler's result, every time we do those two operations, Visual Editor will be redrawn twice: 
- the first redraw is triggered by Shell state update (expected);
- the second redraw, which is redundant, is triggered by the `useEffect` hook which syncs Shell props to local state(unexpected).
So the redraw problem is basically caused by the misused `useEffect` hook and unnecessary local states in Visual Editor.
**Why there are 'useEffect' hooks**
At the very beginning, Visual Editor didn't sync states except 'obi json' with Shell, so all its states were local. As the evolution of Visual Editor, we are …

fix: misused 'useEffect' hook in Visual Editor (#1496)

---

Composer/packages/extensions/obiformeditor/demo/src/index.tsx
Composer/packages/extensions/obiformeditor/src/Form/widgets/LgEditorWidget.tsx

Fix form editor demo not work
refs #1144 

fix: form editor demo not work

---

Composer/yarn.lock

Update the lubuild's computed integrity.
lubuild package in myget was covered today.
Fixes #1609

fix: lubuild computed integrity not match when run yarn install

---

Composer/packages/client/src/CreationFlow/DefineConversation/index.js
Composer/packages/client/src/CreationFlow/LocationBrowser/LocationSelectContent.tsx
Composer/packages/client/src/CreationFlow/index.js
Composer/packages/client/src/store/action/storage.ts
Composer/packages/server/__tests__/services/project.test.ts
Composer/packages/server/__tests__/services/storage.test.ts
Composer/packages/server/src/controllers/storage.ts
Composer/packages/server/src/router/api.ts
Composer/packages/server/src/services/storage.ts
Composer/packages/server/src/store/data.template.ts
Composer/yarn.lock

These commits have introduced some bugs in the creation of bots and breaks current users of Composer by changing the shape of `data.json`. We need to revert for now so we can cut a stable release with a P0 fix.
refs #1583
refs #1548

revert: changes to bot creation

---

.github/workflows/validate-pr.yml

The `edited` event creates a new check instead of re-using the failed on. This creates more noise that necessary. Instead, use the `re-run` check in the Github UI.
refs #1564

ci: update validate-pr action trigger

---

.github/workflows/main.yml
Composer/README.md
README.md

updates the badges to report master branch instead
refs #1619

docs: update coveralls badge

---

Composer/packages/server/assets/projects/InterruptionSample/ComposerDialogs/GetProfile/GetProfile.dialog
Composer/packages/server/assets/projects/InterruptionSample/ComposerDialogs/Main/Main.dialog
Composer/packages/server/assets/projects/InterruptionSample/ComposerDialogs/common/common.lg

1. add a thredhold in GetStarted intent to avoid over trigger.
2. fix malformed schema, extra comma
3. fix value expression.
4. fix turn.value -> this.value
5. fix allowInterrutions: notRecognized->true
closes #1627

fix: Fix interruption sample

---

BotProject/CSharp/Controllers/BotController.cs
BotProject/CSharp/Startup.cs
BotProject/Templates/CSharp/Controllers/BotController.cs
BotProject/Templates/CSharp/Startup.cs

Add directlinespeech support
Close #1638

feat: add directlinespeech support

---

Composer/packages/extensions/obiformeditor/package.json
Composer/packages/extensions/visual-designer/package.json
Composer/packages/lib/shared/package.json
Composer/yarn.lock

- Upgrade Fabric Ui package to fix marqueeSelection horizontal scrolling function.
- Add webpack-cli package to visual editor
closes #1365 

fix: support horizontal scrolling in visual eidtor

---

Composer/yarn.lock

closes #1590
No more confusing stdout (for now)

chore: cleanup yarn.lock to bump `browserslist`

---

Composer/scripts/e2e.sh
azure-pipelines.yml

ci: run cypress in single job for now

---

Composer/packages/extensions/obiformeditor/src/Form/fields/RootField.tsx
Composer/packages/extensions/obiformeditor/src/Form/fields/styles.css

subtitle in form editor
If this is a bug fix, please describe the root cause and analysis of this problem.
Please include a link to the related issue. [Ex. `Closes #<issue #>`](https://help.github.com/en/articles/closing-issues-using-keywords)

subtitle in form editor

---

Composer/package.json
Composer/scripts/update.js

refs #1674
This change introduces a script to parse the local git branch and use it to do sha inspection of the corresponding remote branch. I've added a `RELEASE_BRANCH` guard to avoid unnecessary checks in development mode. This seems appropriate for now.
I've added execution of the script inside both `build` and `startall`.

chore: add startup script to check for oudated versions

---

Composer/scripts/update.js

fix: make update script cross platform compatible

---

Composer/packages/lib/code-editor/src/languages/lg.ts

fix mistakes in syntax highlighting when user enter an unpaired expression.
For example:
closes #1689

fix: add fault tolerance for syntax highlighting

---

.vscode/settings.json
Composer/packages/client/__tests__/components/DialogWrapper/index.test.tsx
Composer/packages/client/__tests__/jest.d.ts
Composer/packages/client/__tests__/setupTests.ts
Composer/packages/client/__tests__/store/actions/storage.test.ts
Composer/packages/client/jest.config.js
Composer/packages/client/setupTests.ts
Composer/packages/client/src/store/action/storage.ts
Composer/packages/client/src/utils/__mocks__/httpUtil.ts
Composer/packages/client/tsconfig.json
Composer/packages/server/README.md
Composer/packages/server/__tests__/controllers/storage.test.ts
Composer/packages/server/__tests__/models/bot/botProject.test.ts
Composer/packages/server/__tests__/services/project.test.ts
Composer/packages/server/jest.config.js
Composer/packages/server/package.json
Composer/packages/server/src/controllers/storage.ts
Composer/packages/server/src/models/bot/botProject.ts
Composer/packages/server/src/router/api.ts
Composer/packages/server/tsconfig.json

The root cause of this was not url encoding the path when loading storage folders and the webpack-dev-server not properly proxying the request to the api server (which is why it was working when running in production mode). 
I went ahead and refactored a bit, making the path a query string param instead of a route parameter. As well as some jest updates.
closes #1612

fix: ability to view storages when in local dev on mac

---

Composer/packages/extensions/obiformeditor/src/Form/ObjectFieldTemplate/styles.css
Composer/packages/extensions/obiformeditor/src/Form/fields/EditableField.tsx
Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/ChoiceInput/Choices.tsx
Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/PromptSettings.tsx
Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/styles.ts
Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/twoSettingFields.tsx
Composer/packages/extensions/obiformeditor/src/Form/fields/RecognizerField/InlineLuEditor.tsx
Composer/packages/extensions/obiformeditor/src/Form/fields/RecognizerField/RegexEditor.tsx
Composer/packages/extensions/obiformeditor/src/Form/fields/RecognizerField/ToggleEditor.tsx
Composer/packages/extensions/obiformeditor/src/Form/fields/RecognizerField/styles.css
Composer/packages/extensions/obiformeditor/src/Form/fields/RecognizerField/styles.ts
Composer/packages/extensions/obiformeditor/src/Form/fields/RootField.tsx
Composer/packages/extensions/obiformeditor/src/Form/widgets/ExpressionWidget.tsx
Composer/packages/extensions/obiformeditor/src/Form/widgets/LgEditorWidget.tsx
Composer/packages/extensions/obiformeditor/src/Form/widgets/TextWidget.tsx
Composer/packages/lib/code-editor/src/RichEditor.tsx
Composer/yarn.lock

Align with the new design in form for inline error display
- Show detail error message.(Now the error message is fixed)
- Notification level. (Now only show error message, but notification message has 2 levels in notification page: warninig & error).
closes #1623 

feat: Align with the new design in form for inline error display

---

Composer/packages/lib/code-editor/src/languages/lg.ts

Closes #776 
update LG editor with new theme.
Examples for current LG theme:
1. template _name and keywords:
2. Multiline 
3. Nested function calls in expression
4. Structure-lg

fix: update LG Editor with new theme

---

Composer/packages/client/src/TestController.tsx
Composer/packages/lib/shared/src/labelMap.ts
Composer/packages/server/schemas/editor.schema

refs #1667
- makes the error/warning number clickable to the Navigaiton page
- changes subtitle label to Adaptive dialog, from AdaptiveDialog

fix: minor styling and labeling for linting ux 

---

.github/actions/conventional-pr/src/conventional-pr.ts
.github/actions/conventional-pr/src/utils.ts

ci: disallow opening pr against stable branch unless a release

---

Composer/packages/client/package.json
Composer/packages/client/src/pages/language-generation/index.tsx
Composer/packages/client/src/pages/language-generation/table-view.tsx
Composer/packages/client/src/utils/dialogUtil.ts
Composer/packages/extensions/obiformeditor/demo/src/index.tsx
Composer/packages/extensions/obiformeditor/package.json
Composer/packages/extensions/obiformeditor/src/Form/types.ts
Composer/packages/extensions/obiformeditor/src/Form/widgets/ExpressionWidget.tsx
Composer/packages/extensions/obiformeditor/src/Form/widgets/LgEditorWidget.tsx
Composer/packages/extensions/obiformeditor/src/FormEditor.tsx
Composer/packages/lib/code-editor/src/RichEditor.tsx
Composer/packages/lib/indexers/package.json
Composer/packages/lib/indexers/src/dialogUtils/dialogChecker.ts
Composer/packages/lib/indexers/src/lgIndexer.ts
Composer/packages/lib/indexers/src/type.ts
Composer/packages/tools/language-servers/language-generation/src/builtinFunctionsMap.ts
Composer/yarn.lock

Sync diagnostics info with notification page in form editor, includes lg, lu and expression dianostics.
closes #1699 
closes #1715 

feat: show error message in form editor.

---

.vscode/settings.json

upgrade `vscode-eslint` plugin  from `1.*` to `2.*`, rewrite setting to latest recommended config.
https://github.com/microsoft/vscode-eslint#release-notes
Requires: 
1. vscode@latest(>=1.41.0) 
_may not valid if your version can search & install latest vscode-eslint_
2. vscode extension: vscode-eslint@latast(>=2.0.6)
if development environment haven't upgrade to latest,  **eslint auto format when save may not be work**
refs #1787 
https://github.com/microsoft/vscode-eslint/issues/840 

chore: upgrade vscode-eslint

---

Composer/packages/client/config/env.js
Composer/packages/client/src/pages/about/index.tsx
Composer/packages/client/src/pages/about/styles.js

Added COMPOSER_VERSION to env variables
Closes #1773 

fix: Updated release version on about page

---

Composer/packages/lib/code-editor/src/languages/lg.ts

In LG editor, when user enter ' (', '[', '{' in template, it will auto close the pair with ')', ']', '}'. 
closes #1679

fix: adding auto closing pairs in LG editor

---

Composer/packages/client/src/pages/language-generation/code-editor.tsx

The initial state, content is empty, so keep ctrl-z will hit this. fixed by set initial content as expected.
fix #1803 

fix: lg all-up view editing ctrl-z bug

---

Composer/packages/client/src/CreationFlow/CreateOptions/index.js

when the state templateId is set. Create a bot from scratch will use that templateId. But it should be emptyBot.
Closes #1814 

fix: Create bot from scratch may create a non-empty bot

---

Composer/packages/lib/shared/src/dialogFactory.ts
Composer/packages/server/assets/projects/ActionsSample/ComposerDialogs/Main/Main.dialog
Composer/packages/server/assets/projects/ActionsSample/ComposerDialogs/RepeatDialog/RepeatDialog.dialog
Composer/packages/server/assets/projects/AskingQuestionsSample/ComposerDialogs/DateTimeInput/DateTimeInput.dialog
Composer/packages/server/assets/projects/AskingQuestionsSample/ComposerDialogs/Main/Main.dialog
Composer/packages/server/assets/projects/AskingQuestionsSample/ComposerDialogs/NumberInput/NumberInput.dialog
Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/Main/Main.dialog
Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/RepeatDialog/RepeatDialog.dialog
Composer/packages/server/assets/projects/EchoBot/ComposerDialogs/Main/Main.dialog
Composer/packages/server/assets/projects/EmptyBot/ComposerDialogs/Main/Main.dialog
Composer/packages/server/assets/projects/InterruptionSample/ComposerDialogs/Main/Main.dialog
Composer/packages/server/assets/projects/QnAMakerLUISSample/ComposerDialogs/Main/Main.dialog
Composer/packages/server/assets/projects/RespondingWithCardsSample/ComposerDialogs/Main/Main.dialog
Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/Main/Main.dialog
Composer/packages/server/assets/projects/ToDoBotWithLuisSample/ComposerDialogs/Main/Main.dialog
Composer/packages/server/assets/projects/TodoSample/ComposerDialogs/Main/Main.dialog

Update OnConversationUpdate conditions, and add a foreach step to loop on MemberAdded.
fixes #1780 
fixes #1632 

feat: Update OnConversationUpdate actions

---

Composer/packages/extensions/obiformeditor/src/Form/widgets/TextWidget.tsx

Updated the hover styles for strings to match the hover styles for expressions. 
Closes #1823

fix: Fixed TextWidget Hover Styles

---

Composer/packages/extensions/visual-designer/src/schema/uischema.ts
Composer/packages/extensions/visual-designer/src/schema/uischema.types.ts
Composer/packages/extensions/visual-designer/src/schema/uischemaRenderer.tsx
Composer/packages/extensions/visual-designer/src/widgets/ActionCard.tsx

fixes #1831 
If a $type is not covered by uischema, it should fallback to a default element. However, the default elelement was set to `<></>` which is a blank node (it should show something).
Now the fallback renderer was set to a grey box
changes on uischema:

fix: RepeatDialog not shown

---

BotProject/Templates/CSharp/Scripts/build_runtime.ps1
Composer/packages/client/src/store/action/bot.ts
Composer/packages/server/src/models/connector/csharpBotConnector.ts

**Cause** Using pwsh command to run a powershell script need its version larger than 6. So when powershell version small than 6, composer crashed in running build script.
**Solution** Remove the powershell version limit in build script, and change the pwsh command into powershell.
Close #1855

fix: botproject build script powershell version limit 

---

Composer/packages/lib/indexers/__tests__/luIndexer.test.ts
Composer/packages/lib/indexers/__tests__/utils/extractProperties.test.ts
Composer/packages/lib/indexers/src/dialogIndexer.ts
Composer/packages/lib/indexers/src/dialogUtils/extractMemoryPaths.ts
Composer/packages/lib/indexers/src/dialogUtils/extractProperties.ts
Composer/packages/lib/indexers/src/type.ts
Composer/packages/server/src/services/project.ts

1. Add some prebuild properties. (turn., dialog.)
2. find user-defined variables in dialogs.
Refs #1807 

feat: enrich prebuilt memory paths and add user defined memory paths

---

Composer/packages/extensions/visual-designer/src/components/nodes/layout-steps/BaseInput.tsx
Composer/packages/extensions/visual-designer/src/components/nodes/layout-steps/Foreach.tsx
Composer/packages/extensions/visual-designer/src/components/nodes/layout-steps/IfCondition.tsx
Composer/packages/extensions/visual-designer/src/components/nodes/layout-steps/SwitchCondition.tsx
Composer/packages/extensions/visual-designer/src/components/renderers/ElementWrapper.tsx
Composer/packages/extensions/visual-designer/src/components/renderers/StepRenderer.tsx

fixes #1770 
Refactor the component `ElementRenderer` -> `ElementWrapper` to prepare for schema-driven.
```tsx
// This is the usage of 'ElementRenderer' (inheritance)
<ElementRender
id={'trigggers[0].actions[0]'}
data={json}
/>
// This is the usage of 'ElementWrapper' (composition)
<ElementWrapper id={xxx}>
<UiSchemaRenderere id={xxx} data={json} />
</ElementWrapper>
```
(In my next PR, I will migrate those remaining $types to uischema)
#1770 

refactor: use composition instead of inheritance in ElementRenderer

---

Composer/packages/extensions/visual-designer/src/components/nodes/layout-steps/BaseInput.tsx
Composer/packages/extensions/visual-designer/src/components/nodes/layout-steps/Foreach.tsx
Composer/packages/extensions/visual-designer/src/components/nodes/layout-steps/IfCondition.tsx
Composer/packages/extensions/visual-designer/src/components/nodes/layout-steps/SwitchCondition.tsx
Composer/packages/extensions/visual-designer/src/components/nodes/templates/FormCard.tsx
Composer/packages/extensions/visual-designer/src/components/renderers/ElementWrapper.tsx
Composer/packages/extensions/visual-designer/src/components/renderers/StepRenderer.tsx
Composer/packages/extensions/visual-designer/src/widgets/ActionCard.tsx
Composer/packages/extensions/visual-designer/src/widgets/ActivityRenderer.tsx
Composer/packages/extensions/visual-designer/src/widgets/DialogRefCard.tsx

fixes #1770 
follows #1873 
When I clicking on a node, ElementWrapper will fire a 'focus' event instead of the node content.
This PR is an optimization work and will benefit the migration of TextInput types to uischema as well.
**Why**
1. Now that `ElementWrapper` is aleady rendering focus states, it should also hold the controller of changing focus states.
2. We will never customize the 'onClick' handler of a whole node, it should be a built-in logic and appear outside uischema, `ElementWrapper` is the right place.
**Changes**
1. in `FormCard.ts`, make the `onClick` prop optional
2. under `widgets` folder, don't pass `onClick` handler in every widget used by uischema
3. bind `onEvent` handler to all appearances of `<ElementWrapper />`
#1770  …

chore: let ElementWrapper handle Visual Editor focus states

---

Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/styles.ts

Set `align-items` to `flex-end` in `settingsFields` to align the prompt settings text inputs.
Closes #1673

fix: Aligned elements in prompt settings

---

Composer/packages/extensions/visual-designer/src/schema/uischema.tsx

Closes #1915 
In Visual Editor, `User Answers` -> `User Input`.
`User Input` should be the correct title, to make two titles consistent, change the title of visual editor nodes from `User Answers` to `User Input`
closes #1915

chore: change title 'User Answers' to 'User Input'

---

Composer/packages/extensions/visual-designer/src/constants/ElementSizes.ts

sync the invalidPromptBrick with design
- before
- After
closes #1905

chore: update IconBrickSize for InvalidPromptBrick

---

Composer/packages/client/src/pages/about/index.tsx
Composer/packages/client/src/pages/about/styles.js
Composer/packages/client/src/pages/design/styles.js
Composer/packages/client/src/pages/home/index.tsx
Composer/packages/client/src/pages/home/styles.ts
Composer/packages/client/src/pages/language-generation/index.tsx
Composer/packages/client/src/pages/language-understanding/index.tsx
Composer/packages/client/src/pages/language-understanding/styles.js
Composer/packages/client/src/pages/notifications/styles.ts
Composer/packages/client/src/pages/setting/deployment/index.js
Composer/packages/client/src/pages/setting/deployment/styles.js
Composer/packages/client/src/pages/setting/dialog-settings/index.tsx
Composer/packages/client/src/pages/setting/dialog-settings/style.ts
Composer/packages/client/src/pages/setting/onboarding-settings/index.tsx
Composer/packages/client/src/pages/setting/onboarding-settings/style.ts

update header's font size and weight
Closes #1902

style: update header size and weight

---

Composer/packages/lib/shared/src/appschema.ts

Updated the dialog property title in `Microsoft.ReplaceDialog`'s app schema to match the title in the SDK schema.
Closes #1697

fix: Updated replace dialog's dialog property title

---

Composer/packages/extensions/obiformeditor/src/Form/ObjectFieldTemplate/styles.css
Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/BotAsks.tsx
Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/styles.ts
Composer/packages/extensions/obiformeditor/src/Form/fields/RecognizerField/styles.ts
Composer/packages/extensions/obiformeditor/src/Form/fields/RootField.tsx
Composer/packages/extensions/obiformeditor/src/Form/fields/styles.css

Changed the padding on the edges of the Form Editor from `18px` to `12px`, and changed the font weight on the `RootField`'s subtitle from `600` to `400`. 
Closes #1693

fix: Adjusted padding in the Form Editor and RootField fonts

---

Composer/packages/client/src/utils/convertUtils/parsePathToFocused.ts

The 'cases' was ignored when creating the focused path. 
closes #1972

fix: the path format generated by notification page is wrong

---

Composer/packages/lib/indexers/src/dialogUtils/dialogChecker.ts
Composer/packages/lib/indexers/src/dialogUtils/validation.ts

https://github.com/microsoft/botbuilder-dotnet/pull/3253
refs #1939

refactor: update the validation for new schema

---

Composer/packages/lib/shared/src/appschema.ts

Replace `includeActivity` with `activityProcessed` for `beginDialog` in form editor depend on new schema.
- Before
- After
fixed #1838

chore: sync new schema in form editor

---

Composer/packages/lib/indexers/__tests__/dialogUtils/dialogChecker.test.ts
Composer/packages/lib/indexers/src/dialogUtils/dialogChecker.ts

the diagnostic path is wrong
the  format is like 'path#type#property'
Closes #1972

fix: the diagnostic path error

---

Composer/packages/lib/shared/src/lgUtils/parsers/lgPatterns.ts

chore: update lg template pattern

---

Composer/packages/client/src/pages/language-generation/index.tsx
Composer/packages/client/src/pages/notifications/useNotifications.tsx

When it common.lg has error, other lg file import common.lg would also report an error.
close #2099

fix: lg duplicate error notification

---

Composer/packages/extensions/visual-designer/__tests__/layouters/measureJsonBoundary.test.ts
Composer/packages/extensions/visual-designer/src/constants/ElementColors.ts
Composer/packages/extensions/visual-designer/src/constants/ElementSizes.ts
Composer/packages/extensions/visual-designer/src/layouters/measureJsonBoundary.ts
Composer/packages/extensions/visual-designer/src/schema/uischema.tsx
Composer/packages/extensions/visual-designer/src/widgets/ActionHeader.tsx

Follows new design, implement a new widget `<ActionHeader />` to draw contentless node and apply it to 6 types:
1. EndDialog
2. EndTurn
3. RepeatDialog
4. CancelAllDialogs
5. LogAction
6. TraceActivity
**Preview the changes in UISchema** (2 types out of 6):
According to new design, we want to show some types as contentless node.
1. Created a new widget `<ActionHeader />`
2. Consumed the new widget in 6 types' definition to make them borderless.
3. Adjusted element size constants.
4. Color
I plan to retire the `FormCard` component in next few PRs because it can't meet our customization requirements under the new widget-based structure.
Therefore, this PR copied out a part of its code as `ActionHeader`; the new widget will be applied to more actions as a nested field. For example:
``` …
```

feat: display 6 actions as contentless node

---

Composer/packages/lib/code-editor/demo/src/richEditor.tsx
Composer/packages/lib/code-editor/src/LuEditor.tsx
docs/Create-Your-First-Bot.md
docs/CreateYourFirstBot.md
docs/concept-events-and-triggers.md
docs/how-to-define-advanced-intents-entities.md
docs/how-to-define-triggers.md
docs/how-to-use-LUIS.md
docs/how-to-use-validation.md
docs/olddocs/CreateYourFirstBot.md
docs/olddocs/testing_debugging.md
docs/olddocs/triggers_and_events.md
docs/tutorial/tutorial-luis.md
toc.md

Did not find the wrong link in master but find it in stable. Still update lu format link to the latest address.
Closes #2105

fix: update lu format link

---

Composer/packages/extensions/visual-designer/src/components/groups/StepGroup.tsx
Composer/packages/extensions/visual-designer/src/widgets/SwitchConditionWidget.tsx

As #2165 described, visual editor invoke `sort()` incorrectly, causes a series of 10+ steps have wrong order.
This PR fixes that issue by parsing string to int.
closes #2165

fix: fix 'sort()' function of steps and cases in visual editor

---

.github/actions/conventional-pr/src/utils.ts

Fix #2172 
Add 'a11y' prefix to PR titles. This is to help distinguish category for accessibility PRs. 
Please use this prefix for the PRs for issues with the Accessibility label: 
Thank you!

ci: add a11y title prefix for accessibility prs

---

Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/Other.tsx
Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/UserInput.tsx
Composer/packages/extensions/obiformeditor/src/Form/widgets/LuEditorWidget.tsx

fix: Moved value field to user tab and removed lu from attachment prompt

---

Composer/packages/client/package.json
Composer/packages/lib/indexers/package.json
Composer/packages/lib/indexers/src/luIndexer.ts
Composer/packages/server/package.json
Composer/packages/tools/language-servers/language-understanding/package.json
Composer/yarn.lock

fix: lu build bug when training empty intents

---

Composer/packages/extensions/visual-designer/src/index.tsx

**Problem:**
Users can't copy actions across different dialog files. If they copied some actions and pasted to another dialog file, nothing would happen. 
**Solution:**
This PR fixes that issue by handling errors when the copy lg api invocation failed.
**Context:**
This bug is related to recent lg file structure changes. Previously, we only have one lg file 'common.lg', but for now, each dialog file has a default lg file, makes our `copyLgTemplate` api won't work if user wants to copy a template from 'Main.lg' to 'Todo.lg'.
As I discussed with Zhixiang, it's quite complicated to deal with cross-file lg template copying problem because LG template could be nested. In this PR, visual editor only defenses potential LG copy failures to make sure the functionality 'copy selection' always work …

fix: support copy actions across dilaogs

---

CHANGELOG.md
scripts/generate-changelog.js

- feat: Remove input LU when deconstructing prompts ([#2180](https://github.com/microsoft/BotFramework-Composer/pull/2180)) ([@tdurnford](https://github.com/tdurnford))
- feat: Add cross train before luis publish ([#2069](https://github.com/microsoft/BotFramework-Composer/pull/2069)) ([@cwhitten](https://github.com/cwhitten))
- feat: Added inline lu to prompts ([#2159](https://github.com/microsoft/BotFramework-Composer/pull/2159)) ([@cwhitten](https://github.com/cwhitten))
- feat: implement new action design to improve readability ([#2136](https://github.com/microsoft/BotFramework-Composer/pull/2136)) ([@cwhitten](https://github.com/cwhitten))
- feat: repaint ui for setProperties in visual editor ([#2017](https://github.com/microsoft/BotFramework-Composer/pull/2017)) …

release: update changelog

---

Composer/packages/extensions/visual-designer/__tests__/utils/normalizeSelection.test.ts
Composer/packages/extensions/visual-designer/src/utils/normalizeSelection.ts

Solve a bug in previous sort. Now the 
```
// before
['actions[10]', 'actions[2]'] => 'actions[10]' < 'actions[2]'
// after
['actions[10]', 'actions[2]'] => 'actions[2]' < 'actions[10]'
```
Define the exact sort order of orphan actions
```
['actions[0].actions[0]', 'actions[0].actions[1]', 'actions[0].elseActions[0]', 'actions[1]']
=> 'actions[0].actions[0]' <'actions[0].elseActions[0]' < 'actions[0].actions[1]' < 'actions[1]'
```
**TODO**: use a trie-tree to manage action path order

fix: sort selected action ids by tree path order

---

.github/workflows/main.yml
.github/workflows/validate-pr.yml

attempting to address:
```
git checkout --progress --force b679ac13b2c48def229f873545fa1258bbf0decd 
359##[error]fatal: reference is not a tree: b679ac13b2c48def229f873545fa1258bbf0decd 
360Removed matchers: 'checkout-git' 
361##[error]Git checkout failed with exit code: 128 
362##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.165.2/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
```
fixes #2221

fix: Switch to actions/checkout@v2

---

Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
Composer/packages/client/src/utils/dialogUtil.ts

1. Delete the regEx pattern when we delete the trigger which triggers it.
2. Do not allow user to create an onIntent trigger when the recognizer type is None.
closes #2215

fix: regEx trigger creation bug

---

Composer/packages/client/src/pages/setting/deployment/deployWizard.js
Composer/packages/client/src/pages/setting/deployment/deployWizardStep-getDeploy.js
Composer/packages/client/src/pages/setting/deployment/index.js

fix: change deploy copy to publish

---

Composer/packages/extensions/visual-designer/__tests__/utils/normalizeSelection.test.ts
Composer/packages/extensions/visual-designer/src/utils/normalizeSelection.ts

1. Solve a bug in previous sort. Now the 
```
// before
['actions[10]', 'actions[2]'] => 'actions[10]' < 'actions[2]'
// after
['actions[10]', 'actions[2]'] => 'actions[2]' < 'actions[10]'
```
2. Filter invalid action ids such as 'actions[0].else', 'actions[0].diamond'
3. Define the exact sort order of orphan actions
```
['actions[0].actions[0]', 'actions[0].actions[1]', 'actions[0].elseActions[0]', 'actions[1]']
=> 'actions[0].actions[0]' <'actions[0].elseActions[0]' < 'actions[0].actions[1]' < 'actions[1]'
```
**TODO**: use a trie-tree to manage action path order

fix: sort action ids correctly

---

BotProject/Templates/CSharp/Scripts/deploy.ps1

fixes #2218
1. Create generated if not exists ( if user doesn't debug locally, the 'generated' folder would not be created and luis build would fail)
2. Add luis authoring region in deploy.ps1.

fix: add luis authoring region for lubuild 

---

Composer/packages/server/assets/projects/ActionsSample/ComposerDialogs/Actions/Actions.dialog
Composer/packages/server/assets/projects/ActionsSample/ComposerDialogs/EditActions/EditActions.dialog
Composer/packages/server/assets/projects/ActionsSample/ComposerDialogs/IfCondition/IfCondition.dialog
Composer/packages/server/assets/projects/ActionsSample/ComposerDialogs/Main/Main.dialog
Composer/packages/server/assets/projects/ActionsSample/ComposerDialogs/Main/Main.lg
Composer/packages/server/assets/projects/TodoRecognizerSetSample/ComposerDialogs/ClearToDos/ClearToDos.dialog
Composer/packages/server/assets/projects/TodoRecognizerSetSample/ComposerDialogs/ClearToDos/ClearToDos.lg
Composer/packages/server/assets/projects/TodoRecognizerSetSample/ComposerDialogs/DeleteToDo/DeleteToDo.dialog
Composer/packages/server/assets/projects/TodoRecognizerSetSample/ComposerDialogs/ShowToDos/ShowToDos.dialog
Composer/packages/server/assets/projects/TodoRecognizerSetSample/ComposerDialogs/ShowToDos/ShowToDos.lg
Composer/packages/server/assets/projects/TodoSample/ComposerDialogs/ClearToDos/ClearToDos.dialog
Composer/packages/server/assets/projects/TodoSample/ComposerDialogs/DeleteToDo/DeleteToDo.dialog
Composer/packages/server/assets/projects/TodoSample/ComposerDialogs/DeleteToDo/DeleteToDo.lg

Some of the dialog files in the Sample files had duplicate ID fields. This change should eliminate these duplicates, letting the "duplicate-id" a11y test past.
The side dialog is created from the sample .dialog files, so the fix here was to check that the ids in each file contain no duplicate ID fields and change the ones that did.
Closes #2142

a11y: adjust id numbers in dialog samples

---

Composer/packages/client/src/ShellApi.ts
Composer/packages/client/src/extension-container/ExtensionContainer.tsx
Composer/packages/client/src/messenger/FrameAPI.ts
Composer/packages/client/src/pages/design/index.tsx
Composer/packages/client/src/store/action/dialog.ts
Composer/packages/client/src/store/index.tsx
Composer/packages/client/src/store/reducer/index.ts
Composer/packages/client/src/store/types.ts
Composer/packages/extensions/obiformeditor/src/Form/widgets/DialogSelectWidget.tsx
Composer/packages/extensions/visual-designer/__tests__/utils/normalizeSelection.test.ts
Composer/packages/extensions/visual-designer/src/constants/NodeEventTypes.ts
Composer/packages/extensions/visual-designer/src/editors/ObiEditor.tsx
Composer/packages/extensions/visual-designer/src/index.tsx
Composer/packages/extensions/visual-designer/src/utils/jsonTracker.ts
Composer/packages/extensions/visual-designer/src/utils/normalizeSelection.ts
Composer/packages/lib/shared/__tests__/copyUtils/copyInputDialog.test.ts
Composer/packages/lib/shared/__tests__/copyUtils/copySendActivity.test.ts
Composer/packages/lib/shared/__tests__/jestMocks/externalApiStub.ts
Composer/packages/lib/shared/src/copyUtils/ExternalApi.ts
Composer/packages/lib/shared/src/copyUtils/copyInputDialog.ts
Composer/packages/lib/shared/src/copyUtils/copySendActivity.ts
Composer/packages/lib/shared/src/copyUtils/index.ts
Composer/packages/lib/shared/src/dialogFactory.ts
Composer/packages/lib/shared/src/types/shell.ts
Composer/packages/lib/shared/src/walkerUtils/walkLgResources.ts

closes #2206 
https://share.getcloudapp.com/eDuxRoXn

feat: Move

---

Composer/packages/client/src/pages/language-generation/table-view.tsx

This adds proper screen-reader labels to the "Been used" column in Bot Responses. Now, instead of "read-only, button" and "read-only", the cells are read as "used" and "unused".
Closes #2049

a11y: add SR labels to Bot Responses "used" column

---

Composer/packages/lib/shared/src/appschema.ts

sync oauth input property in form editor. Replace `tokenProperty` to `property` for `OAuthInput` in form editor appschema.
fixes #2260

chore: sync oauth input property in form editor

---

Composer/packages/extensions/obiformeditor/src/schema/uischema.ts
Composer/packages/lib/shared/src/appschema.ts

add default alwaysPrompt value in OAuthInput step.
There is a bug in SDK, that requires alwaysPrompt property must have value, otherwise it will throw an exception called : Object reference to null.
This PR is to hotfix that issue in Composer side to work around that bug. 
fixes #2266

chore: add default alwaysPrompt value in OAuthInput step

---

Composer/packages/lib/code-editor/src/languages/lu.ts
Composer/packages/tools/language-servers/language-understanding/src/LUServer.ts
Composer/packages/tools/language-servers/language-understanding/src/matchingPattern.ts

fixes #2141 
1. Incorrect syntax highlight for entity definition. For example:
2. Wrong place of inserting '-' in auto-completion of utterance
3. trigger error of lebeling experience

fix: Some editting bugs in Lu editor

---

Composer/packages/client/src/pages/design/createDialogModal.tsx

One-line fix to make it clear that this field is mandatory
Closes #2073

a11y: make dialog name required

---

Composer/packages/client/src/pages/setting/index.tsx
Composer/packages/client/src/store/action/navigation.ts
Composer/packages/client/src/utils/navigation.ts

The Nav component provided by Fabric is good enough at managing its own state, and we don't need a lot of the extra machinery we had to make Links do the right thing; it's that machinery that was causing the extra keyboard-navigation targets.
Closes #2102 
Just to demonstrate that it still looks the same:

a11y: remove extra Link stuff from settings Nav

---

Composer/packages/client/src/App.tsx
Composer/packages/client/src/components/NavItem/index.tsx
Composer/packages/extensions/visual-designer/src/schema/uischema.tsx

This moves a FocusZone element from the sidebar's NavItems into the App itself; this lets us use up/down arrow keys instead of Tab to navigate between the icons, as requested in the Issue.
Closes #2040

a11y: move FocusZone from NavItem to App

---

Composer/packages/client/src/components/Header/index.js
Composer/packages/client/src/components/Pagination/index.tsx
Composer/packages/client/src/pages/notifications/NotificationHeader.tsx
Composer/packages/client/src/pages/notifications/NotificationList.tsx

This addresses a few minor problems that were causing a11y issues.
Closes #2124

a11y: resolve issues in Notifications page

---

Composer/packages/extensions/obiformeditor/src/Form/fields/RecognizerField/index.tsx

set luis  recognizer type for dialog recognizer property in formEditor.
There is the code to `set luis recognizer type` in current master branch.
```
if (selectedFile) {
onChange(currentDialog.luFile);
}
```
But `currentDialog.luFile` is '',  it will cause the recognizer is '', and can not create recognizered intent, So I revert the code to 
```
if (selectedFile) {
onChange(`${currentDialogId}.lu`);
}
```

fix: set luis  recognizer type for dialog in formEditor 

---

Composer/packages/server/src/models/bot/botProject.ts

The referred lu id should add locale before search
refs #2357
-> 2. Configuring LUIS as recognizer appears to break. (500's from emulator)
for the multi locale publish result will be like:

fix: can't find referred lu files for publishing

---

Composer/cypress/integration/NotificationPage.spec.ts
Composer/packages/server/src/models/bot/botProject.ts

when create or save as bot, rename entry dialog/lg/lu
refs #2357 
> 1. serialization has a couple minor issues:
>  when a template is selected for creation, the main/entry dialog is the name of the template, when it should be the name the user gave for the bot.

fix: file serialization regressions

---

Composer/packages/extensions/visual-designer/src/components/groups/StepGroup.tsx
Composer/packages/extensions/visual-designer/src/components/lib/SVGContainer.tsx
Composer/packages/extensions/visual-designer/src/components/renderers/ElementWrapper.tsx
Composer/packages/extensions/visual-designer/src/widgets/ActionHeader.tsx
Composer/packages/extensions/visual-designer/src/widgets/PromptWidget.tsx
Composer/packages/lib/shared/src/viewUtils.ts

The label that gets read by the screen reader turns out to come from the ElementWrapper component, so this adds some mechanisms to that code so it can reach in and extract the title of what it's rendering. I couldn't use a callback because ElementWrapper just has generic "children" with no guarantee of that having any shape in particular, and I didn't want to add a whole new "ariaLabel" field to our schema when it would just duplicate the same information already in "title".
There are a lot more screen-reader-related issues going on in this codebase, but this at least fixes one of them.
Closes #2058

a11y: have screen-reader extract card titles from headers

---

Composer/packages/client/src/pages/design/createDialogModal.tsx

We already have form errors in our state, so we should be able to just clean up our validation code and use existing methods to make them happen every form change and not just on submit.
Closes #2060
Closes #2074

a11y: use formError state in "New Dialog" form

---

Composer/packages/client/src/store/index.tsx
Composer/packages/client/src/store/reducer/index.ts
Composer/packages/lib/shared/src/index.ts
Composer/packages/lib/shared/src/resolverFactory.ts
Composer/packages/server/src/models/bot/botProject.ts
Composer/packages/server/src/services/project.ts

Enable resolve file with or without locale.
```
*  for example:
*  in todosample.en-us.lg:
*   [import](common.lg)
*
*  would resolve to common.en-us.lg || common.lg
*
```
close #2361

fix: lg resolver with locale

---

Composer/packages/lib/code-editor/src/BaseEditor.tsx

This changes the BaseEditor component slightly, letting its error messages be multiline as well as changing the format of the "Refer to docs" link to better resemble the examples in the Fabric UI component demo. This obviates the problem in #2114 by removing the need to collapse the message bar in the first place.
Closes #2114

a11y: use multiline message bars for errors

---

Composer/packages/ui-plugins/lg/src/LgField.tsx
Composer/packages/ui-plugins/luis/src/LuisIntentEditor.tsx

Fix form refactor merge revert previous changes
refs #2118

fix: form refactor merge revert

---

README.md

Broken link
unless this should be https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial/tutorial-create-bot.md instead?
closes #2437

docs: fix broken link for getting started docs

---

README.md

@a-b-r-o-w-n FYI. Per our discussion yesterday. 
Updated the following four doc links in the _Get Started_ section of the [README](https://github.com/microsoft/BotFramework-Composer/blob/master/README.md) file in Composer master branch. 
Refs #2431 
1. Pointing to: https://aka.ms/bf-composer-docs-welcome-page
2. Pointing to: https://aka.ms/bf-composer-docs-introduction
3. Pointing to: https://aka.ms/bf-composer-docs-setup-yarn
4. Pointing to: https://aka.ms/bf-composer-docs-create-first-bot

docs: update docs in readme to point to docs site

---

Composer/packages/client/src/CreationFlow/LocationBrowser/FileSelector.tsx

During rendering, the currentPath is empty. And it is selected in the dropdown although it does not match any option. This behavior will make the dropdown select the first option by default, which is '/'. In our code, when currentPath is empty, the dropdown should not have any option.
Closes #2453

fix: did not open default path when we have the new install

---

Composer/packages/extensions/adaptive-form/src/utils/__tests__/resolvePropSchema.test.ts
Composer/packages/extensions/adaptive-form/src/utils/index.ts
Composer/packages/extensions/adaptive-form/src/utils/resolvePropSchema.ts

This happened because I was recursing on object types with properties defined which collided with a schema property named properties. This is unnecessary now as I don't need to recurse the schema.
fixes #2458

fix: fix issue rendering delete properties action

---

Composer/packages/server/schemas/sdk.schema
Composer/packages/ui-plugins/lg/src/LgField.tsx

Previously, the user had to interact with the editor in order to get the template saved.
Note: There is an issue right now with the lg api where if there are multiple parallel writes, the last write wins. So only the last lg field on the form will be created. There is an issue tracking this: #2247 
closes #2406

feat: create lg template when schema provides a default value

---

Composer/packages/client/src/CreationFlow/index.js
Composer/packages/client/src/store/action/project.ts

Save as e2e test failed.
The reason is when navigating the function doesn't use the new project id and will fetch the previous project.
refs #2611

fix: save as can't navigate to the target project

---

Composer/packages/client/src/pages/design/VisualEditor.tsx
Composer/packages/client/src/pages/design/styles.ts

img dispaly incorrent when zoom in 400%
- before
- after
Fix #2053

a11y: img display incorrect when zoom in 400%

---

Composer/packages/client/src/CreationFlow/CreateOptions/index.js

This is fixing the issue where the individual radio buttons did not have an aria label. 
Fix #2018 - missing `aria-label`s on radio buttons

a11y: Fix missing aria-labels on radio buttons 

---

Composer/packages/server/src/models/bot/botProject.ts

I think the project folder structure is changed since the last time we add the cleanUp function in Composer/packages/server/src/models/bot/botProject.ts. Add some more code to check empty folder from bottom to up. Stop at the root folder of the project.
Closes #2526

fix: bug about deleting empty folder

---

Composer/packages/extensions/adaptive-form/src/components/AdaptiveForm/FormTitle.tsx
Composer/packages/extensions/adaptive-form/src/components/FieldLabel.tsx

Used the form title and field labels to add a more descriptive aria-label to the "learn more" link.
closes #2133

a11y: Added aria label to help links

---

Composer/packages/extensions/adaptive-form/src/components/FieldLabel.tsx

This change adjusts FieldLabel.tsx so the SR reads out a sensible label for a field when it ought to and the a11y checker doesn't complain about fields without labels (this used to happen because the "aria-labelledby" attribute referred to an object which only existed while the tooltip was open).
closes #2063
closes #2122
SR: "Entities: Required entities - group."
(tab)
SR: "Form editor - new value - edit."

a11y: restructure field labels for better a11y

---

Composer/packages/extensions/visual-designer/src/utils/nodeOperation.ts

fix #2649 
As reported in #2649 , pressing TAB in visual editor will trigger an error like this:
This PR defends that error.
#2649

fix: defends tab move error raised by 'scrollIntoView()'

---

Composer/packages/extensions/adaptive-form/src/components/fields/OneOfField/OneOfField.tsx
Composer/packages/extensions/adaptive-form/src/components/fields/OneOfField/__tests__/utils.test.ts
Composer/packages/extensions/adaptive-form/src/components/fields/OneOfField/index.ts
Composer/packages/extensions/adaptive-form/src/components/fields/OneOfField/utils.ts
Composer/packages/ui-plugins/expressions/jest.config.js
Composer/packages/ui-plugins/expressions/src/ExpressionField.tsx
Composer/packages/ui-plugins/expressions/src/__tests__/utils.test.ts
Composer/packages/ui-plugins/expressions/src/utils.ts

We were checking `if (!value)` to determine which field type to render. This change hardens that check to only check for undefined or null.
closes #2658

fix: render correct field when value is '0'

---

Composer/cypress/integration/Breadcrumb.spec.ts
Composer/packages/extensions/visual-designer/src/widgets/ForeachWidget.tsx
Composer/packages/extensions/visual-designer/src/widgets/IfConditionWidget.tsx
Composer/packages/extensions/visual-designer/src/widgets/PromptWidget.tsx
Composer/packages/extensions/visual-designer/src/widgets/SwitchConditionWidget.tsx

fix #2667 by putting svg before actions
A trick about DOM event capturing:
- elements declared **before** `<svg />` are unreachable
- elements declared **after** `<svg />` are reachable

fix: cannot select nested actions in Visual Editor

---

Composer/packages/server/package.json
Composer/packages/server/src/server.ts
Composer/yarn.lock

Adds 'Composer now running at: <url>' back after startup.
closes #2648

fix: add composer startup message back

---

Composer/packages/client/src/components/ProjectTree/index.tsx
Composer/packages/client/src/components/ProjectTree/styles.ts
Composer/packages/client/src/components/ProjectTree/treeItem.tsx

the focus will go to left Navigate pane first now. 
Refs #2027

a11y: accessibility 2027

---

Composer/packages/client/src/CreationFlow/CreateOptions/index.js
Composer/packages/client/src/CreationFlow/CreateOptions/styles.js
Composer/packages/client/src/CreationFlow/LocationBrowser/styles.ts
Composer/packages/client/src/pages/language-generation/table-view.tsx
Composer/packages/client/src/pages/language-understanding/styles.ts
Composer/packages/client/src/pages/language-understanding/table-view.tsx

follow up on issue 2026. We can access the cell now (create bot dialog, lg/lu page)
Refs #2026

a11y: accessibility 2026

---

Composer/packages/electron-server/src/main.ts

A call was being made to `app.setAsDefaultProtocolClient()` when building locally, which was causing deeplinks meant for production Composer Electron to misbehave and throw an error.
Fixes #2323

fix: Fixed an issue with the Composer protocol

---

Composer/packages/client/__tests__/components/appUpdater.test.jsx
Composer/packages/client/src/components/AppUpdater/index.tsx

Updated some copy in the auto-update UX to more accurately represent what is actually happening under the hood.
refs #2226 
**Update available (Before)**
**Update available (After)**
**Update succeeded (Before)**
**Update succeeded (After)**

fix: Updated some auto-update UX copy to be more accurate.

---

Composer/packages/ui-plugins/prompts/src/flowSchema.tsx

close #2598 
ChoiceInput not changed;
To other input types, they will be displayed as a one-line card in the 'UserInput' part.
#2598

fix: align *Input nodes to design

---

Composer/plugins/mockRemotePublish/package.json

mockremote plugin should not be enabled in master, it has no build script, will break if you haven't built it once. 
refs #2766

fix: disable mockremote plugin 

---

Composer/packages/client/src/components/Header/index.jsx
Composer/packages/client/src/components/MainContent/index.jsx
Composer/packages/client/src/pages/about/index.tsx
Composer/packages/client/src/pages/design/index.tsx
Composer/packages/client/src/pages/home/index.tsx
Composer/packages/client/src/pages/language-generation/index.tsx
Composer/packages/client/src/pages/language-understanding/index.tsx
Composer/packages/client/src/pages/notifications/NotificationList.tsx
Composer/packages/client/src/pages/publish/index.tsx
Composer/packages/client/src/pages/skills/index.tsx

add main landmark on each page
Refs #2019

a11y: accessibility issue 2019

---

Composer/packages/lib/indexers/src/dialogUtils/dialogChecker.ts

ignore the same type
refs #2729

fix: Remove the duplicate types for schema

---

Composer/packages/client/src/pages/language-generation/index.tsx
Composer/packages/client/src/pages/language-understanding/index.tsx
Composer/packages/client/src/pages/language-understanding/styles.ts

Flow up fix of #2747 , move dialog tree down to origin place.
close #2791

fix: all up view dialog tree

---

Composer/packages/lib/code-editor/src/BaseEditor.tsx

This makes our error messages multiline, which is needed since we removed the reveal arrows (for a11y reasons).
fixes #2792

fix: make error messages multiline

---

Composer/packages/client/__tests__/utils/luUtil.test.ts
Composer/packages/client/src/utils/luUtil.ts
Composer/packages/lib/indexers/src/dialogUtils/extractIntentTriggers.ts

If a trigger start with OnIntent and there is no action or begin a dialog without lu
the config will be like   'tirgger_Intent':''
refs #2794

fix: crosstrain for dialog without lu file

---

Composer/packages/client/src/components/NavItem/styles.ts
Composer/packages/client/src/pages/home/ItemContainer.tsx
Composer/packages/client/src/pages/home/index.tsx
Composer/packages/client/src/pages/home/styles.ts

And onkeydown to new and recent bot buttons
Refs #2011

a11y: fix accessibility issue 2011

---

Composer/packages/extensions/adaptive-form/src/components/SchemaField.tsx
Composer/packages/ui-plugins/select-skill-dialog/src/BeginSkillDialogField.tsx
Composer/packages/ui-plugins/select-skill-dialog/src/SkillEndpointField.tsx

Fixed select skill endpoint dropdown selector.
Closes #2801

fix: Fixed select skill endpoint dropdown

---

Composer/packages/server/assets/shared/README.md
Composer/packages/server/assets/shared/scripts/test.js
Composer/packages/server/src/controllers/project.ts
Composer/packages/server/src/models/asset/assetManager.ts

This introduces a step in the bot project creation process that copies a set of files from the `assets/shared` folder into the project.
This will be used to copy the new provisioning script into the projects so they can be provisioned and deployed without first requiring a full eject.
Currently the shared assets include just a README file with a link to the Composer repo. However, this file will soon include instructions on using the provisioning tool and the publishing tool inside Composer to provision and deploy the bot to Azure.
I wanted to do this as a clean PR, but this is needed to finish #2733 
Closes #2451

feat: Copy boilerplate material into new bot projects

---

Composer/packages/client/__tests__/components/TestController/errorCallout.test.tsx
Composer/packages/client/src/components/TestController/errorCallout.tsx
Composer/packages/client/src/components/TestController/index.tsx

I update the code to make the 'reloading' status easier to be read out before the status changed.
In most cases, the reloading status exists for a very short period. And while narrator announce 'reloading', it may also be interrupted by an error message. @ashish315 Can you help checking whether the current behavior acceptable?
I think the current process is like: 
1. Click start bot button, the narrator starts to read the status 'publishing' or 'reloading'
2. Before the narrator finish, an error dialog may be pop up and get the focus. (We must focus on that dialog, otherwise we cannot click the try again or cancel button using keyboard)
3. Since the focus changed, the narrator start to read something else.
closes #2068

a11y: accessibility issue 2068

---

Composer/packages/electron-server/__tests__/appMenu.test.ts
Composer/packages/electron-server/src/appMenu.ts
Composer/packages/electron-server/src/main.ts
Composer/packages/lib/code-editor/src/BaseEditor.tsx

> Currently we do not set the application menu, so Electron uses the default menu which contains links to Electron documentation.
This PR addresses that and explicitly sets the menu so that it only contains info / functionality relevant to Composer and not Electron.
closes #2832 
**File**
**Edit**
**View**
**Window**
**Help**
**File**
**Edit**
**View**'
**Window**
**Help**
I don't have a Mac, but feel free to add screen shots if you test it out!

fix: Updated Composer Electron app menu

---

BotProject/Templates/CSharp/BotSettings/BotFeatureSettings.cs
BotProject/Templates/CSharp/Startup.cs
BotProject/Templates/CSharp/appsettings.json
Composer/packages/server/src/models/settings/defaultSettingManager.ts

1. Remove UseTelemetryLoggerMiddleware section in appsettings.json, use telemetry section to control 
2. Add feature section to compose default settings page. 
fixes #2789

fix: telemetry logger middleware

---

Composer/packages/client/src/pages/design/index.tsx
Composer/packages/client/src/shell/useShell.ts
Composer/packages/client/src/utils/dialogUtil.ts
Composer/packages/extensions/extension/src/hooks/index.ts
Composer/packages/extensions/extension/src/hooks/useActionApi.ts
Composer/packages/extensions/extension/src/hooks/useDialogApi.ts
Composer/packages/extensions/extension/src/hooks/useDialogEditApi.ts
Composer/packages/extensions/extension/src/hooks/useLgApi.ts
Composer/packages/extensions/extension/src/hooks/useLuApi.ts
Composer/packages/extensions/extension/src/hooks/useTriggerApi.ts
Composer/packages/extensions/visual-designer/src/editors/ObiEditor.tsx

fixes #2209
When deleting a trigger, let the handler invoke resource api to perform a cleanup.
Considering DesignPage is not under `<Extension>` context, I made some hooks receive `shellApi` instead of having a dependency on `useShellApi`

fix: clean LG/LU resources when deleting a Trigger

---

Composer/packages/electron-server/src/main.ts
Composer/packages/electron-server/src/utility/logger.ts

The `NODE_ENV` env variable was expected to be set to `production` when executing the packaged Composer Electron app, but it was not being set. This was breaking some production functionality such as dynamically finding an open port to mount the server on.
fixes #2770

fix: Fixed unset electron production flag.

---

Composer/packages/extensions/plugin-loader/src/composerPluginRegistration.ts
Composer/plugins/localPublish/package-lock.json
Composer/plugins/localPublish/package.json
Composer/plugins/localPublish/src/index.ts
Composer/plugins/localPublish/tsconfig.json

closes #1747 
Description
Calling `child_process.kill()` will kill that process but does not kill all processes spawned by that process. We need to run the bot in a detached process which gets its own process group, then call `process.kill(-child.pid)` to kill all porcesses in that group.

fix: bot content not updating after restart

---

Composer/packages/server/assets/projects/ActionsSample/language-generation/en-us/actionssample.en-us.lg
Composer/packages/server/assets/projects/ActionsSample/language-generation/en-us/common.en-us.lg
Composer/packages/server/assets/projects/AskingQuestionsSample/askingquestionssample.dialog
Composer/packages/server/assets/projects/AskingQuestionsSample/language-generation/en-us/askingquestionssample.en-us.lg
Composer/packages/server/assets/projects/AskingQuestionsSample/language-generation/en-us/common.en-us.lg
Composer/packages/server/assets/projects/ControllingConversationFlowSample/controllingconversationflowsample.dialog
Composer/packages/server/assets/projects/ControllingConversationFlowSample/language-generation/en-us/common.en-us.lg
Composer/packages/server/assets/projects/EchoBot/echobot.dialog
Composer/packages/server/assets/projects/EchoBot/language-generation/en-us/common.en-us.lg
Composer/packages/server/assets/projects/EchoBot/language-generation/en-us/echobot.en-us.lg
Composer/packages/server/assets/projects/EmptyBot/emptybot.dialog
Composer/packages/server/assets/projects/EmptyBot/language-generation/en-us/common.en-us.lg
Composer/packages/server/assets/projects/EmptyBot/language-generation/en-us/emptybot.en-us.lg
Composer/packages/server/assets/projects/RespondingWithTextSample/language-generation/en-us/common.en-us.lg
Composer/packages/server/assets/projects/RespondingWithTextSample/language-generation/en-us/respondingwithtextsample.en-us.lg
Composer/packages/server/assets/projects/TodoRecognizerSetSample/language-generation/en-us/common.en-us.lg
Composer/packages/server/assets/projects/TodoRecognizerSetSample/language-generation/en-us/todorecognizersetsample.en-us.lg
Composer/packages/server/assets/projects/TodoSample/language-generation/en-us/common.en-us.lg
Composer/packages/server/assets/projects/TodoSample/language-generation/en-us/todosample.en-us.lg
Composer/plugins/localPublish/yarn.lock

* Changes help() to WelcomeUser()
* fixes the references from the EmptyBot and EchoBot .dialog files to point to activities instead of values 
closes #2849

fix: reformat sample bot dialogs

---

Composer/packages/extensions/adaptive-form/src/utils/__tests__/getUIOptions.test.ts
Composer/packages/extensions/adaptive-form/src/utils/getUIOptions.ts

Fixes an issue where opening HTTPRequest or ConfirmInput results in a browser crash.
fixes #2867

fix: prevent infinite render loop

---

Composer/plugins/localPublish/src/index.ts

Closes #2870
We introduced some enhancement for process management in https://github.com/microsoft/BotFramework-Composer/pull/2861, which is not compatible with Windows, causing publishing request never return in Windows and the page eventually crashed in page.
This PR fix the local runtime management plugin by bring back previous behavior with a guard isWin, to be able to behave a little different than Mac.

fix: Fix start bot in windows

---

Composer/packages/client/src/store/persistence/FilePersistence.ts
Composer/plugins/localPublish/src/index.ts

Copied the `skill-manifests` directory to the runtime's wwwroot directory when the bot is publish locally, which makes the manifest available at `http://localhost:3979/skill-manifests/*`.
Closes #2327

feat: Copy skill manifests to static files

---

Composer/packages/server/assets/projects/ToDoBotWithLuisSample/dialogs/viewitem/language-generation/en-us/viewitem.en-us.lg

Some of the lines in viewitem.en-us.lg start with ##, which seems to throw off the parser - it wanted to read those as templates instead of as a continuation of a ```-demarked block. This fix just reformats that message without the ## marks; if we wanted a more complete fix that would work in all cases, I think that would take a bigger change to the parser itself.
fixes #2859

fix: simplify viewitem.en-us.lg

---

Composer/packages/electron-server/README.md
Composer/packages/electron-server/package.json
Composer/packages/electron-server/scripts/copy-templates.js
Composer/packages/electron-server/src/main.ts

The runtime eject feature was broken due to an outdated folder structure within the packaged version of Composer Electron.
Before, the folder structure was:
```
/app.asar.unpacked/
/build/
/templates/    <--- runtime templates
/plugins/
```
This was causing the eject functionality to break when looking for the runtime templates in `/app.asar.unpacked/BotProject/Templates/`.
The new folder structure is:
```
/app.asar.unpacked/
/BotProject/Templates/   <--- runtime templates
/build/
/plugins/
```
The runtime templates are no longer packed by electron-builder, but copied in after the `yarn pack` step, like the plugins.
Fixes #2868

fix: Fixed packaged folder structure.

---

Composer/packages/client/src/pages/design/exportSkillModal/content/SelectManifest.tsx
Composer/packages/client/src/store/persistence/types.ts
Composer/packages/lib/indexers/src/skillManifestIndexer.ts
Composer/packages/lib/indexers/src/utils/fileExtensions.ts
Composer/packages/server/src/models/bot/botProject.ts
Composer/plugins/localPublish/src/index.ts

- Changed the manifest file type from `.manifest` to `.json`
- Renamed the `skill-manifests` directory to `manifests`
- Manifest can be found at http://localhost:{PORT}/manifests/{BOTNAME}-{MANIFESTVERSION}-manifest.json
- Changed manifests names to `${botName}-{manifestVersion}-manifest.json`
Closes #2327

fix: changed manifest file type from '.manifest' to '.json'

---

Composer/packages/electron-server/src/main.ts

Local runtime plugin will publish bot using the environment variable populated from the electron process. This prevents the need to create a folder inside `Program Files` for windows which would require admin privileges.
Fixes #2862

fix: Populate env variable with AppData folder

---

Composer/packages/client/src/pages/design/PropertyEditor.tsx
Composer/packages/client/src/pages/design/index.tsx
Composer/packages/extensions/adaptive-form/src/components/AdaptiveForm/FormTitle.tsx
Composer/packages/extensions/adaptive-form/src/defaultUiSchema.ts
Composer/packages/extensions/adaptive-form/src/utils/__tests__/mergePluginConfigs.test.ts
Composer/packages/extensions/extension/src/types/formSchema.ts
Composer/packages/server/assets/projects/ToDoBotWithLuisSample/todobotwithluissample.dialog

This allows users to completely clear the form title. It will show the original title as a placeholder. If the user leaves that page and comes back, we will use the default heuristic to determine the title to use.
Also fixes an issue in the TodoLuis sample.
closes #2662 
closes #2841

fix: unable to clear form title

---

Composer/packages/client/src/pages/design/styles.ts

Fixed: can not use event capture in visual editor.
- Before
- After
After fixed it, the container focused state will be removed when children doms' event triggered.
This is because children doms' mouse event will be blocked when container dom has focus::after styles, like below
```
&::after {
content: '';
position: absolute;
top: 0;
bottom: 0;
left: 0;
right: 0;
border: black solid 1px;
}
```
So I removed the after styles.
fix #2907

fix: can not capture events in visual editor

---

Composer/packages/lib/indexers/src/dialogIndexer.ts
Composer/packages/lib/indexers/src/dialogUtils/extractMemoryPaths.ts
Composer/packages/lib/shared/src/types/indexers.ts
Composer/packages/server/src/services/project.ts

1. fix memory variables tracking
2. remove extract memory variables in dialog indexer at client, cause it's only used at server.
close #2895

fix: memory variables suggestions in lgEditor

---

Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
Composer/packages/client/src/utils/dialogUtil.ts

update trigger wizard due to schema changed. Further modification may be needed.

chore: Update trigger wizard

---

Composer/plugins/localPublish/src/index.ts

Currently, the `manifests` directory is being copied to the `runtime/wwwroot` directory; however, due to recent changes, it should be copied to the `runtime/azurewebapp/wwwroot` directory.
closes #2918

fix: Copy skill manifests to the correct directory in the localPublish plugin

---

Composer/packages/extensions/visual-designer/src/schema/defaultFlowSchema.tsx
Composer/packages/lib/ui-shared/src/components/PropertyAssignment.tsx
Composer/packages/lib/ui-shared/src/components/index.ts

fixes #2877 incorrect SetProperty content in visual nodes
1. If `value` set to `false` or `0`, SetProperty shows `?` instead of real value
2. Content in SetProperty and SetProperties are not consistent.
1. Let SetProperty and SetProperties share the same component `<PropertyAssignment>`
2. Update Flow Editor schema.

fix: improper visual node content in SetProperty / SetProperties

---

Composer/packages/client/src/pages/design/index.tsx
Composer/packages/client/src/pages/home/index.tsx
Composer/packages/client/src/pages/language-generation/index.tsx
Composer/packages/client/src/pages/language-understanding/index.tsx
Composer/packages/client/src/pages/notifications/NotificationList.tsx
Composer/packages/client/src/pages/publish/index.tsx
Composer/packages/client/src/pages/setting/index.tsx
Composer/packages/client/src/pages/skills/index.tsx

fix: revert aria regions change to fix layout issues

---

Composer/cypress/integration/TriggerCreation.spec.ts
Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
Composer/packages/client/src/utils/dialogUtil.ts
Composer/packages/extensions/adaptive-form/src/components/fields/RecognizerField.tsx
Composer/packages/extensions/adaptive-form/src/defaultUiSchema.ts
Composer/packages/lib/shared/src/labelMap.ts

Code logical got changed. Fixed the bugs and add some test cases.
Closes #2961

fix: trigger creation bug

---

Composer/packages/electron-server/__tests__/appUpdater.test.ts
Composer/packages/electron-server/src/appUpdater.ts

This PR adds a line that flips a flag to prevent multiple downloads of the same update.
(Must have missed this in the original auto update PR 😮)
[This check was already there](https://github.com/microsoft/BotFramework-Composer/blob/master/Composer/packages/electron-server/src/appUpdater.ts#L49), but nothing was ever flipping `downloadingUpdate` to `true`.
fixes #2226

fix: Added missing flag to prevent concurrent downloads of the same update.

---

Composer/packages/server/schemas/sdk.schema
runtime/dotnet/azurewebapp/Schemas/sdk.schema

update resultProperty descption of http request step
fix #974 
update resultProperty descption of http request step

chore: update resultProperty descption of http request step

---

Composer/packages/lib/code-editor/src/BaseEditor.tsx
Composer/packages/lib/code-editor/src/LgEditor.tsx
Composer/packages/lib/code-editor/src/LuEditor.tsx
Composer/packages/ui-plugins/lg/src/LgField.tsx
Composer/packages/ui-plugins/luis/src/LuisIntentEditor.tsx

Removed form-editor previous maintained localValue( for performance consideration ), let `BaseEditor` handle it, it would check `id` to see need update from external value or not. 
Because of no `localValue` anymore, we also don't need `sync` method.
close #2982 
refs #2627 
refs #2904

fix: lu/lg editor update strategy

---

Composer/packages/client/src/router.tsx
Composer/packages/client/src/store/action/navigation.ts

seems imported by #2922 , which `visual editor` call navigate methods with empty `projectId, dialogId`.
close #3015

fix: open bot read property 'sdk' is undefined

---

Composer/plugins/azureFunctionsPublish/package.json
Composer/plugins/azureFunctionsPublish/yarn.lock
Composer/plugins/azurePublish/package.json
Composer/plugins/azurePublish/yarn.lock

The `azurePublish` and `azureFunctionPublish` plugins have a hard dependency on `@bfc/libs/bot-deploy` but do not include it in their `package.json`.  [Source 1](https://github.com/microsoft/BotFramework-Composer/blob/master/Composer/plugins/azurePublish/src/index.ts#L6) [Source 2](https://github.com/microsoft/BotFramework-Composer/blob/master/Composer/plugins/azureFunctionsPublish/src/index.ts#L6)
The plugin code should have been broken in the web app as well, but the only reason it was working is because of the yarn monorepo hoisting the missing dependencies (`@bfc/libs/bot-deploy`).
This missing dependency then caused the plugin initialization to break in the packaged Electron app where there are no hoisted dependencies.
Fixes #3053

fix: Fixed missing publish targets in Composer Electron

---

Composer/packages/client/src/components/TestController/errorCallout.tsx

Replace "a" tags with Fluent Link components with target="_blank" on them, so the .NET Core SDK dialog properly opens things in a new window instead of taking over Electron.
closes #3056

fix: replace <a> links with <Link>s in error message

---

Composer/packages/client/src/pages/home/RecentBotList.tsx

The recent bot list use BotName as the key. The key maybe duplicated which causes the bug.
Closes #3048

fix: duplicated key in recent bot list

---

Composer/packages/client/src/components/SkillForm/CreateSkillModal/index.tsx
Composer/packages/client/src/components/SkillForm/CreateSkillModal/styles.ts
Composer/packages/lib/indexers/src/utils/diagnosticUtil.ts
Composer/packages/server/src/models/bot/skillManager.ts
Composer/packages/server/src/services/project.ts

Remove use cache at getProjectById introduced by #2786 to prevent high frequency server index.
nowadays, benefit from LeiLei's work, client do not fetch project at every route change, so there is no need to use cache at `getProjectById` anymore. 
When use want a fresh from server, `ctrl-f` refresh page would work as expected.
Appends: 
Also fixed a skill validating ui.
close #3068 
skill url validating spinner

fix: remove cache when getProjectById

---

Composer/cypress.json
Composer/cypress/integration/Breadcrumb.spec.ts
Composer/cypress/integration/CreateNewBot.spec.ts
Composer/cypress/integration/HomePage.spec.ts
Composer/cypress/integration/LGPage.spec.ts
Composer/cypress/integration/LUPage.spec.ts
Composer/cypress/integration/LeftNavBar.spec.ts
Composer/cypress/integration/LuisDeploy.spec.ts
Composer/cypress/integration/NavigateUrls.ts
Composer/cypress/integration/NewDialog.spec.ts
Composer/cypress/integration/NotificationPage.spec.ts
Composer/cypress/integration/Onboarding.spec.ts
Composer/cypress/integration/RemoveDialog.spec.ts
Composer/cypress/integration/SaveAs.spec.ts
Composer/cypress/integration/ToDoBot.spec.ts
Composer/cypress/integration/TriggerCreation.spec.ts
Composer/cypress/integration/VisualDesigner.spec.ts
Composer/cypress/support/commands.ts

- Short circuit the ui to create bot for most tests (create bot spec still uses UI). This should help speed up test runs.
- Uses baseUrl config option instead of COMPOSER_URL env var
- Also fixes todo spec.
refs #3081

test: use api to create bot in e2e tests

---

Composer/packages/client/src/pages/design/index.tsx

The `designPageLocation` object being included in the `usEffect` dependency array causes the selected trigger to be set to the `BeginDialog` trigger after the user selects the dialog because `designPageLocation.selected` gets set to null when a trigger isn't selected which causes the hook to execute unnecessarily. Removing `designPageLocation` from the `usEffect` dependency array resolves the issue.
Closes #3070

fix: Goto Begin Dialog after clicking dialog

---

Composer/packages/client/src/pages/setting/index.tsx
Composer/packages/client/src/router.tsx
Composer/packages/client/src/store/action/project.ts

You can repro this bug easily by deleting an Empty bot.
1. The root reason is a race condition. Pls check the code I have commented there.
2. Set a global error, if we fail to delete a bot.
Closes #3110

fix: update recent bots list after deleting a bot project

---

Composer/packages/client/src/pages/design/index.tsx

According to BaseEditor, if id is not changed, it will use memo value.
Then when switching dialogs, the json content will not change.
closes #3126

fix: use currentDialog.id for JsonEditor

---

Composer/packages/client/__tests__/store/persistence/filePersistence.test.ts
Composer/packages/client/src/store/persistence/FilePersistence.ts
Composer/packages/lib/code-editor/src/BaseEditor.tsx

1. If the server return error when handling file update. The flushing flag was not set to false, then the task queue will never do flush.
2. When click show code button, the editor will get initial value. If we switch the dialog, the value will update to the editor, and the editor will call the onChange function to update dialog. The update function in design page will use a stale dialog id to update, so the previous dialog was covered by the new dialog.
In this PR I just re-render the the editor if the id changed. 
It works If we use a reference attached the dialog id to update the dialog too. But the ctrl-z will undo the update and the value will be covered again.
refs #3134

fix: show code mess up the dialog content and the persistence layer block issue

---

.github/actions/conventional-pr/src/utils.ts

Adds a check for "#minor" as a signal for a minor PR without a related issue number. Intended only for use with minor changes (e.g. doc or typo fixes).
closes #3147

ci: update utils.ts to allow for "#minor" tag

---

README.md

The download links for mac and linux are currently swapped. This fixes them.
#minor

docs: Correct download links (mac and linux are swapped)

---

Composer/cypress/integration/LeftNavBar.spec.ts
Composer/cypress/integration/NewDialog.spec.ts
Composer/cypress/integration/NotificationPage.spec.ts
Composer/cypress/integration/Onboarding.spec.ts
Composer/cypress/integration/TriggerCreation.spec.ts
Composer/packages/client/src/utils/pageLinks.ts
docs/olddocs/testing_debugging.md
docs/tutorial/tutorial-lg.md

fix: change label text 'design flow' to 'design'

---

Composer/.prettierrc

add 
`endOfLine: auto`
in .prettierrc. this will maintain existing line endings
refs #3164

fix: set prettier rule end of line auto

---

Composer/packages/extensions/adaptive-form/src/components/fields/ArrayField.tsx
Composer/packages/extensions/adaptive-form/src/components/fields/ArrayFieldItem.tsx
Composer/packages/ui-plugins/expressions/src/ExpressionField.tsx

Fixed the 'Validation Rules' array styling so the expression expands to use the full width of the property editor and errors render below the text field instead of next to it.
Closes #3187

fix: Fixed expression array styling

---

Composer/packages/client/__tests__/utils/navigation.test.ts
Composer/packages/client/src/pages/notifications/index.tsx
Composer/packages/client/src/utils/navigation.ts

test: add test for client navigation util

---

Composer/plugins/samples/assets/shared/scripts/provisionComposer.js

Need to pass the tenant id as a parameter to the provision script.
fixes #3160

fix: Add tenantId to provision azure login

---

Composer/plugins/localPublish/src/index.ts

Ignore runtime folder zipping when localpublish.
close #3196

fix: ignore runtime folder zipping when local publish

---

Composer/packages/client/src/pages/home/ItemContainer.tsx

Fixes Fluent UI deprecation warning.
#minor

chore: use default button instead of button

---

Composer/packages/client/src/pages/setting/dialog-settings/index.tsx
Composer/packages/ui-plugins/expressions/src/index.ts

Addressing issue #3222
Addressing issue #3224  
#minor
Tested by local build and both doc links reported in the issues now point to the right places.

fix: update expression and publish doc links

---

Composer/packages/client/__tests__/components/CreationFlow/DefineConversation/index.test.tsx
Composer/packages/client/__tests__/components/createDialogModal.test.tsx
Composer/packages/client/src/components/CreationFlow/DefineConversation/index.tsx
Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
Composer/packages/client/src/constants/index.ts
Composer/packages/client/src/pages/design/createDialogModal.tsx
Composer/packages/client/src/pages/language-understanding/publish-luis-modal.jsx

do not allow using dot in bot's dialog and trigger name.
Closes #3185

fix: update bot naming rules

---

Composer/packages/client/src/components/CreationFlow/CreateOptions/index.tsx
Composer/packages/client/src/router.tsx
Composer/packages/server/src/models/bot/botProject.ts
Composer/plugins/localPublish/src/copyDir.ts
Composer/plugins/localPublish/src/index.ts
azure-pipelines.yml
runtime/dotnet/azurewebapp/Schemas/readme.md
runtime/dotnet/azurewebapp/Schemas/update-schema.ps1
runtime/dotnet/azurewebapp/Schemas/update-schema.sh
runtime/dotnet/azurewebapp/Schemas/update.sh

This PR addresses the following
1. Custom schema supplied to Composer from PVA was overwritten on ejection. This has been sorted out
2. The update-schema scripts(Bash and Powershell) have been added at the root. We have one .schema file at the root of the bot project which will be the source of truth
3. Routing to default dialog if dialog id not specified in URL
4. Routing schemaURL, name, description to the template if none specified in create protocol
5. Fixes improper saving of huge schema file with write stream as only a part of schema file was saved
refs #2322 
update-schema.sh -runtime azurewebapp
update-schema.sh -runtime azurefunctions

fix: Prevent schema from being overwritten

---

Composer/packages/client/__tests__/components/CreationFlow/LocationBrowser/FileSelector.test.tsx
Composer/packages/client/__tests__/components/CreationFlow/LocationBrowser/LocationSelectContent.test.tsx
Composer/packages/client/__tests__/components/FileSelector.test.tsx
Composer/packages/client/src/components/CreationFlow/LocationBrowser/FileSelector.tsx
Composer/packages/client/src/components/CreationFlow/LocationBrowser/LocationSelectContent.tsx

The deleted files are not used anymore.
#minor

test: add unit tests for location browser

---

README.md

#minor
Running 
```
$ git clone git@github.com:microsoft/BotFramework-Composer.git
```
fails with:
```
C:\>git clone git@github.com:microsoft/BotFramework-Composer.git
Cloning into 'BotFramework-Composer'...
Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
#minor

docs: Fix for git clone command

---

Composer/plugins/samples/assets/projects/ToDoBotWithLuisSample/dialogs/additem/additem.dialog
Composer/plugins/samples/assets/projects/ToDoBotWithLuisSample/dialogs/deleteitem/deleteitem.dialog

ToDoBotWithLuisSample has itemTite in dialog properties, fixed addItem and deleteItem dialogs to have @itemTitle
[fixes #3278](https://github.com/microsoft/BotFramework-Composer/issues/3278)

fix: 3278 fixed itemTitle typo in add and delete dialogs

---

Composer/packages/server/package.json
Composer/yarn.lock

PR #3155 added a hard dependency to `rimraf` in `@bfc/server`, but `rimraf` is only listed as a dev dependency resulting in a startup error in Composer Electron where only production dependencies are packaged.
The most recent nightly will not render anything due to this.
closes #3280

fix: Made rimraf a production dependency in @bfc/server

---

runtime/dotnet/tests/SkillConversationIdFactoryTests.cs

Fix the warning on PR validation
#minor

fix: fix id factory test

---

.github/ISSUE_TEMPLATE/bot-framework-composer-bug.md
Composer/packages/lib/code-editor/src/LgEditor.tsx
Composer/packages/lib/code-editor/src/LuEditor.tsx
Composer/packages/lib/code-editor/src/utils/index.ts
Composer/packages/lib/code-editor/src/utils/lspUtil.ts
Composer/packages/lib/code-editor/src/utils/types.ts

LG/LU editor use WebSocket connect to LSP server, this may failed when page is idle or network is poor, and at this moment inline editor's inside suggestion/check would not work. 
we have auto re-connection, so mute the failed alert sounds reasonable.
close #3167

fix: suppress websocket error after connection lost

---

Composer/packages/server/src/models/bot/botProject.ts
Composer/packages/server/src/models/bot/luPublisher.ts

The defaultLanguage in luis setting is used as fallback local. And fallbacklocal is used to set default recognizer when we use multi language.
When we load the lu content, the local is used to check the file local. 
lubuild will check the filename, if the filename is 'a.en-us.lu', the local will set to 'en-us'. 
If the file name is 'a.lu', lubuild will use the passed local. 
But if the file is 'a.en-us.lu', and the local is 'it-it', the function will throw an error.
#minor
refs #3274

fix: load lu content need add system locale

---

Composer/packages/electron-server/__tests__/appUpdater.test.ts
Composer/packages/electron-server/src/appUpdater.ts
Composer/packages/electron-server/src/main.ts

There was an error in the scenario that:
- The user installed Composer for all users (Windows only)
- The user enabled auto updates (silent install)
- The user **did not** run Composer as administrator
in which once the user exited Composer, a system prompt would ask the user to uninstall the old composer and then fail to run the new installer, resulting in just deleting the current Composer install.
This PR fixes that by explicitly calling the `.quitAndInstall()` method on the app updater class instead of relying on the auto install on app quit logic. The `.quitAndInstall()` API was already working in the explicit update dialog flow, and so no we are just using that in the auto update flow as well.
closes #3237

fix: Silent auto updates now explicitly call the quitAndInstall() method

---

Composer/packages/lib/code-editor/src/LgEditor.tsx
Composer/packages/lib/code-editor/src/constants.ts
docs/concept-language-generation.md
docs/concept-memory.md
docs/how-to-define-triggers.md
docs/how-to-send-messages.md
docs/how-to-use-LUIS.md
docs/how-to-use-validation.md
docs/olddocs/testing_debugging.md
toc.md

The previous link is invalid.
Closes #3213

fix: update lg format link

---

Composer/package.json
Composer/packages/client/package.json
Composer/packages/lib/code-editor/package.json
Composer/packages/tools/language-servers/language-understanding/package.json
Composer/yarn.lock

This PR upgrades the 
1.`kind-of` library through yarn resolutions as its a transitive dependancy on the latest webpack version
2.`webpack-server` in order upgrade `websocket-extensions` library
#minor

fix: More security vulnerability fixes

---

Composer/packages/client/__tests__/components/CreationFlow/DefineConversation/index.test.tsx
Composer/packages/client/__tests__/components/CreationFlow/index.test.tsx
Composer/packages/client/src/components/CreationFlow/DefineConversation/index.tsx
Composer/packages/client/src/pages/design/createDialogModal.tsx

Changed button text from Next to OK per request from design.
[fixes #3354](https://github.com/microsoft/BotFramework-Composer/issues/3354)

fix: 3354 Changed Next to OK in buttons that close dialogs

---

Composer/packages/client/__tests__/components/TestController/publish-luis-modal.test.jsx
Composer/packages/client/src/pages/language-understanding/publish-luis-modal.jsx
Composer/packages/client/src/store/types.ts
Composer/packages/server/src/models/bot/interface.ts

Fix endpoint, authoringEndpoint missing after publishing luis
close #3395

fix: endpoint, authoringEndpoint missing after publishing luis

---

Composer/cypress/integration/Onboarding.spec.ts
Composer/packages/client/src/components/NavTree/index.tsx
Composer/packages/client/src/pages/setting/index.tsx
Composer/packages/client/src/pages/setting/router.tsx
Composer/packages/client/src/router.tsx
Composer/packages/client/src/utils/pageLinks.ts
Composer/packages/electron-server/scripts/copy-plugins.js

1. Move Info page into Settings page
2. Remove/replace Info icon/location with Settings cog (move to bottom left)
3. Settings cog is always enabled and interactable
4. Bot settings & Runtime config in subnav of Settings page are disabled if no bot is currently loaded.
fixes #3309 
https://github.com/microsoft/BotFramework-Composer/issues/3309

fix: #3309 Allow configuring app settings without opening a bot project

---

Composer/packages/extensions/adaptive-flow/src/adaptive-flow-editor/constants/ScreenReaderMessage.ts
Composer/packages/extensions/adaptive-flow/src/adaptive-flow-editor/contexts/SelectionContext.ts
Composer/packages/extensions/adaptive-flow/src/adaptive-flow-editor/hooks/useEditorEventApi.ts
Composer/packages/extensions/adaptive-flow/src/adaptive-flow-editor/hooks/useSelectionEffect.ts
Composer/packages/extensions/adaptive-flow/src/adaptive-flow-editor/renderers/NodeWrapper.tsx
Composer/packages/extensions/adaptive-flow/src/adaptive-flow-editor/utils/calculateRangeSelection.ts
Composer/packages/extensions/adaptive-flow/src/adaptive-flow-renderer/constants/NodeEventTypes.ts

Closes #3249 
1. [Ctrl + Click] - Toggle selection
2. [Shift + Click] - Range Selection

feat: 'Ctrl + Click', 'Shift + Click' behaviors in Flow Editor

---

Composer/packages/client/src/pages/publish/createPublishTarget.tsx
Composer/packages/client/src/pages/publish/index.tsx
Composer/packages/client/src/store/action/publisher.ts
Composer/packages/client/src/store/persistence/FilePersistence.ts

Fix missing plugin issue when creating a new publish profile, and make url redirect to all profile when url error.
Cause: get publish history before settings file persisted to server.
Solution: Add filePersistence.flush after clicking the save button.
close #3300

fix: fix get history before file persistence

---

Composer/packages/extensions/adaptive-form/src/defaultUiSchema.ts

Removed 'AutoEndDialog' from hidden properties in the default ui schema.
Closes #3492

feature: show 'AutoEndDialog' from Adaptive Dialog Property Editor

---

Composer/packages/test-utils/src/base/jest.config.ts

Jest needs to be told to collect coverage from all files. Without this config, jest would only collect coverage on files that were imported in a test.
refs #3456

test: run coverage on all source files

---

Composer/packages/client/src/store/action/setting.ts
Composer/packages/client/src/store/persistence/FilePersistence.ts

action function call error.
the setting update in file persistence lost projectId
#minor
refs #3525

fix: composer will crashed when add a new publish profile

---

Composer/packages/client/__tests__/components/CreationFlow/DefineConversation/index.test.tsx
Composer/packages/client/__tests__/components/CreationFlow/index.test.tsx
Composer/packages/client/src/components/CreationFlow/DefineConversation/DefineConversation.tsx

The location is not initialized.  And an useEffect also reset location to "". Fixed both cases and updated test case to guarantee initialization correct.
refs #3535

fix: location initialization

---

Composer/package.json
Composer/packages/client/src/components/CreationFlow/CreationFlow.tsx
Composer/packages/client/src/components/CreationFlow/DefineConversation/DefineConversation.tsx
Composer/packages/client/src/pages/home/index.tsx
Composer/packages/client/src/recoilModel/atoms/appState.ts
Composer/packages/client/src/recoilModel/dispatchers/application.ts
Composer/packages/client/src/recoilModel/dispatchers/project.ts
Composer/packages/client/src/recoilModel/dispatchers/shared.ts

Adds support for project failure action with recoil and remove dependency on templateId in recoil

feat: Project Failure support for recoil

---

Composer/packages/electron-server/electron-builder-config.json

The electron version specified in the electron-builder config needs to be updated to match the current version or else the build process will fail to download the correct binary.
#minor

chore: Bumped electron-builder config to correct electron version.

---

Composer/plugins/README.md

This adds information about some missing parameters and methods to the `plugins/readme`

doc: add some missing details to plugin readme

---

Composer/packages/tools/language-servers/language-generation/src/lgParser.ts

lgWorker fork process re-exec nodemon run arguments `--inspect=9228` , which caused an app crashed error
Fix this by reset forked process `execArgv: []`, but not sure it's the best solution or not.
#minor

fix: yarn start:dev app crashed

---

Composer/packages/client/config/env.js
Composer/packages/electron-server/package.json
releases/1.0.2.md

- feat: Disable / Enable actions ([#3416](https://github.com/microsoft/BotFramework-Composer/pull/3416)) ([@yeze322](https://github.com/yeze322))
- feat: allow inputting path ([#3302](https://github.com/microsoft/BotFramework-Composer/pull/3302)) ([@liweitian](https://github.com/liweitian))
- feat: add loading indicator when waiting on form data or schema to load ([#3523](https://github.com/microsoft/BotFramework-Composer/pull/3523)) ([@a-b-r-o-w-n](https://github.com/a-b-r-o-w-n))
- feat: support validate lg custom functions ([#3273](https://github.com/microsoft/BotFramework-Composer/pull/3273)) ([@lei9444](https://github.com/lei9444))
- feat: show 'AutoEndDialog' from Adaptive Dialog Property Editor ([#3498](https://github.com/microsoft/BotFramework-Composer/pull/3498)) …

release: 1.0.2

---

Composer/packages/client/src/components/ToolBar/ToolBar.tsx
Composer/packages/client/src/components/ToolBar/ToolBar.types.ts
Composer/packages/client/src/components/ToolBar/ToolBarStyles.ts
Composer/packages/client/src/components/ToolBar/index.ts
Composer/packages/client/src/pages/design/DesignPage.tsx

closes #3591 
Follow the newest design in [Figma](https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-main-design-spec-%2F-UI-library?node-id=2968%3A26994).
**Changes**
1. Refactor the 'ToolBar' component which was coupled with design page buttons.
2. Grouping 'undo' / 'redo' / 'copy' / 'cut' / 'move' / 'delete' together as a dropdown button.

feat: grouping Toolbar buttons under the 'Edit' dropdown button

---

README.md

The path `./docs/media/` is broken, thus, I updated it with the right path to align with the rest of the [README](https://github.com/microsoft/BotFramework-Composer/blob/master/README.md) file to be `./docs/Assets/` to fix the visual aspect of the repo.
closes #3611 
Before this PR:
After this PR:

fix: Update banner with the right location to resolve 404 error

---

.github/actions/conventional-pr/src/conventional-pr.ts
.github/actions/conventional-pr/src/utils.ts

Dependabot is a useful tool, but the PRs it autogenerates don't match the format we restrict our PRs to. This change will detect if a PR's author is Dependabot and, if so, let it skip the usual checks.
#minor

ci: allow dependabot PRs to skip checks

---

Composer/packages/extensions/adaptive-form/src/components/SchemaField.tsx
Composer/packages/ui-plugins/expressions/src/__tests__/utils.test.ts
Composer/packages/ui-plugins/expressions/src/utils.ts

Numbers in expression fields were getting recognized with a valueType of "integer", which didn't match the expected type of "number", leading to numbers getting turned into generic blank objects.
fixes #3366

fix: numbers in ExpressionField now recognized as such

---

Composer/packages/client/src/store/reducer/index.ts
Composer/packages/lib/indexers/src/dialogIndexer.ts
Composer/packages/lib/indexers/src/utils/help.ts

This adds a mechanism to our "getProjectSuccess" reducer to handle exceptions passed up from the functions it calls, and adds an exception thrown when the dialog indexer encounters a file with an empty name (i.e. ".dialog"). These would break our routing and shouldn't be allowed in the first place. Trying to open a project with a bad dialog file will now kick back to the Home screen and display an appropriate error message.
fixes #3428

fix: add error for nameless dialog file

---

Composer/packages/server/src/models/bot/luPublisher.ts

delete old version when publishing luis.
The lubuild support this feature. 
composer set deleteOldVersion to true.
closes #3640

fix: set deleteOldVersion to true when publishing luis

---

Composer/packages/client/src/pages/about/About.tsx
Composer/packages/client/src/pages/home/Home.tsx

* **From:** 
"Bot Framework Composer is an integrated development environment (IDE) for building bots and other types of conversational software with the Microsoft Bot Framework technology stack."
* **To:** 
"Bot Framework Composer is an open-source visual authoring canvas for developers and multi-disciplinary teams to build bots. Composer integrates LUIS and QnA Maker, and allows sophisticated composition of bot replies using language generation."
* **From:** 
"Bot Framework Composer is an integrated development environment (IDE) for building bots and other types of conversational software with the Microsoft Bot Framework technology stack. Inside this web-based tool you will find everything you need to build a modern, state-of-the-art conversational experience.
Bot Framework Composer …

doc: home page text

---

Composer/packages/client/src/recoilModel/dispatchers/project.ts

Open a new bot after delete a bot will navigate to the old bot
The reason is the design page will use the location state to navigate to the begin dialog action. The location is not reset in dispatcher.
In this PR, reset the location when deleting a bot.
#minor

fix: Open a new bot after delete a bot will nagivate to the old bot

---

Composer/packages/client/__tests__/pages/notifications/useNotifications.test.tsx
Composer/packages/client/src/components/TestController/TestController.tsx
Composer/packages/client/src/components/TestController/warningInfo.tsx
Composer/packages/client/src/pages/design/createDialogModal.tsx
Composer/packages/client/src/pages/notifications/Notifications.tsx
Composer/packages/client/src/pages/notifications/types.ts
Composer/packages/client/src/pages/notifications/useNotifications.tsx
Composer/packages/client/src/recoilModel/dispatchers/lg.ts
Composer/packages/client/src/recoilModel/types.ts
Composer/packages/lib/indexers/src/dialogIndexer.ts
Composer/packages/lib/shared/src/types/indexers.ts

Show warning in toolbar, if both has error and warning, will show error at first priority. 
1. check dialog used skills exist (Error)
2. check skill required info (Warning)
Prevent create same id dialog, ignore case
close #3284 
close #3401 
close #3687

fix: validate skill empty & add duplicate dialog

---

Composer/plugins/samples/assets/projects/RespondingWithCardsSample/language-generation/en-us/common.en-us.lg

Fixed [audio card link](http://www.wavlist.com/movies/004/father.wav) in RespondWithCardSample. 
Should point to https://wavlist.com/wav/father.wav
#minor
#3698

fix: a broken link in CardSample

---

Composer/packages/client/src/recoilModel/dispatchers/publisher.ts

Recoil state is immutable. If we set the value but the value hasn't changed, the component will re-render.
In publish page useEffect will called every time the history changed. 
So there will be a loop infinitely
In this PR, if the status is 404, do nothing.
closes #3705

fix: loop infinitely on publish page when get publish status

---

Composer/packages/client/src/components/TestController/publishDialog.tsx
Composer/packages/client/src/pages/publish/Publish.tsx
Composer/packages/client/src/pages/publish/createPublishTarget.tsx
Composer/packages/client/src/pages/skills/skill-settings.tsx
Composer/packages/client/src/recoilModel/atoms/botState.ts
Composer/packages/client/src/recoilModel/dispatchers/project.ts
Composer/packages/client/src/recoilModel/dispatchers/setting.ts
Composer/packages/client/src/recoilModel/persistence/FilePersistence.ts
Composer/packages/client/src/recoilModel/types.ts
Composer/packages/extensions/plugin-loader/src/types.ts
Composer/packages/lib/shared/src/types/server.ts
Composer/packages/lib/shared/src/types/settings.ts
Composer/packages/server/src/controllers/publisher.ts
Composer/packages/server/src/models/bot/botProject.ts
Composer/packages/server/src/models/bot/interface.ts
Composer/packages/server/src/models/bot/luPublisher.ts
Composer/plugins/azureFunctionsPublish/src/index.ts
Composer/plugins/azurePublish/src/index.ts

Reason: Because files property in botproject is modified to Map and private, so it cause issue in azure plugin.
Solution: add botproject interface and move some other interfaces to shared folder. Change project type from any to IBotproject.
close #3717

fix: fix deploy issue because botproject files structure changed

---

Composer/packages/client/src/recoilModel/persistence/FilePersistence.ts

The flush method will be resolved when the queue is empty. But the asynchronous tasks may be not finished. 
#minor

fix: file persistence's flush method should wait for all tasks finish

---

Composer/packages/client/src/pages/design/createDialogModal.tsx
Composer/packages/server/__tests__/models/bot/botProject.test.ts
Composer/packages/server/src/models/bot/botProject.ts

In this PR if the name is empty, disable the "OK" button
Do we need to use { validateOnMount: true }? This will show error message when we open the dialog first time
closes #3428

fix: composer loading bot forever due to unexpected main dialog

---

Composer/packages/client/src/recoilModel/selectors/eject.ts

Showing the error message responded from server if it had, otherwise show the message in error object.
close #3750

fix: enhance error message in eject runtime

---

Composer/packages/client/src/pages/setting/dialog-settings/DialogSettings.tsx
Composer/packages/client/src/pages/setting/dialog-settings/style.ts
Composer/packages/server/src/models/bot/luPublisher.ts

1. fix luis publish missing `isStaging` parameters.(introduced by last luparser package upgrade which API changed)
2. update setting page empty space ux.
#minor
fix Luis publish error

fix: Luis publish missing parameter

---

Composer/packages/extensions/adaptive-flow/__tests__/adaptive-flow-editor/utils/getCustomSchema.test.ts
Composer/packages/extensions/adaptive-flow/src/adaptive-flow-editor/AdaptiveFlowEditor.tsx
Composer/packages/extensions/adaptive-flow/src/adaptive-flow-editor/utils/getCustomSchema.ts

fixes #2946 
Previously, custom Triggers / Recognizers were incorrectly grouped as `Custom actions`.
This PR implements a stricter schema $role filter to differentiate Adatpive Action / Trigger / Recognizer.
As an example, I have a custom $kind `Microsoft.CustomResource`.
- When it's declared as `IDialog`, it appears under the 'Custom actions' label.
- When it's declared as `ITrigger` or other type, it won't be recognized as a custom action.

fix: differentiate Action / Trigger / Recognizer from custom schema

---

Composer/packages/client/src/constants.ts
Composer/packages/client/src/pages/design/DesignPage.tsx

fix trigger actions bug

---

Composer/package.json

clean the yarn build:plugin script in yarn build.
#minor

fix: yarn build will run yarn build:plugin twice

---

Composer/packages/client/src/pages/design/DesignPage.tsx
Composer/packages/client/src/shell/useShell.ts
Composer/packages/extensions/extension/src/components/Extension.tsx
Composer/packages/lib/shared/src/types/shell.ts
Composer/packages/ui-plugins/select-dialog/src/__tests__/selectDialog.test.tsx
Composer/packages/ui-plugins/select-skill-dialog/src/__tests__/BeginSkillDialogField.test.tsx
Composer/packages/ui-plugins/select-skill-dialog/src/__tests__/SelectSkillDialog.test.tsx

fixes #3783 
refs #3721 
Let Flow Editor consumes shellData from `useShell('FlowEditor')`;
let Property Editor consumes shellData from `useShell('PropertyEditor')`
The difference is when an Action is selected, Property Editor's shellData should be the Action json, compared with Flow's data is whole dialog json.

fix: use different shellData in Form and Flow's ExtensionContext

---

Composer/package.json
Composer/tsconfig.base.json
Composer/yarn.lock

Uses `importHelpers` compiler option which imports various helper methods from `tslib` instead of inlining them. Reduces bundle size slightly.
#minor

build: use importHelpers compiler option

---

Composer/packages/lib/indexers/src/utils/lgUtil.ts
Composer/packages/lib/shared/src/types/indexers.ts
Composer/packages/tools/language-servers/language-generation/src/LGServer.ts
Composer/packages/tools/language-servers/language-generation/src/lgParser.ts
Composer/packages/tools/language-servers/language-generation/src/lgWorker.ts

fix lg editor validation error & intelligence, bug introduced by #3738 & #3337 
close #3815

fix: lg editor validation error & intelligence

---

Composer/packages/client/src/components/CreationFlow/CreateOptions.tsx
Composer/packages/client/src/components/CreationFlow/CreationFlow.tsx
Composer/packages/client/src/components/CreationFlow/DefineConversation.tsx
Composer/packages/client/src/constants.ts
Composer/packages/client/src/pages/qna/ImportQnAFromUrlModal.tsx
Composer/packages/client/src/pages/qna/index.tsx
Composer/packages/client/src/recoilModel/dispatchers/qna.ts
Composer/packages/server/src/controllers/project.ts
Composer/plugins/samples/assets/projects/QnASample/language-generation/en-us/common.en-us.lg
Composer/plugins/samples/assets/projects/QnASample/language-generation/en-us/qnasample.en-us.lg
Composer/plugins/samples/assets/projects/QnASample/qnasample.dialog
Composer/plugins/samples/assets/projects/QnASample/settings/appsettings.json
Composer/plugins/samples/src/index.ts

Creating qn a sample

---

Composer/packages/lib/indexers/src/utils/dialogCheckUtil.ts
Composer/packages/server/src/models/bot/botStructure.ts

1. When create a dialog `Hello` now will create same case sensitive files:
```
dialogs/Hello/{Hello.dialog, Hello.lg, Hello.lu}
```
previous will created files:
```
dialogs/hello/{hello.dialog, hello.lg, hello.lu}
```
2. Validation is case insensitive (addressed via #3686 )
close #3814

fix: do not strict new created dialog name to be lowercase

---

Composer/packages/client/src/recoilModel/dispatchers/user.ts

This change lets the user's settings stay around in localStorage, which is then used to initialize the Recoil store. Without it, the preferences would last through a session but then disappear on reload.
fixes #3824

fix: keep user settings in localStorage as well as recoil

---

runtime/dotnet/azurewebapp/Schemas/update-schema.ps1

The backup filename for the sdk schema and UI schema are the same in the update-schema.ps1 script.  This is not a bug in the sh script.  Updated the extension to .uischema in the ps1.
#minor
N/A

fix: Fixed uischema backup extension filename in update-schema.ps1

---

Composer/packages/client/package.json
Composer/packages/client/src/pages/design/exportSkillModal/__tests__/generateSkillManifest.test.ts
Composer/packages/client/src/pages/design/exportSkillModal/__tests__/getManifestId.test.ts
Composer/packages/client/src/pages/design/exportSkillModal/constants.tsx
Composer/packages/client/src/pages/design/exportSkillModal/content/Description.tsx
Composer/packages/client/src/pages/design/exportSkillModal/content/Endpoints.tsx
Composer/packages/client/src/pages/design/exportSkillModal/content/SaveManifest.tsx
Composer/packages/client/src/pages/design/exportSkillModal/content/SelectDialogs.tsx
Composer/packages/client/src/pages/design/exportSkillModal/content/SelectManifest.tsx
Composer/packages/client/src/pages/design/exportSkillModal/content/SelectTriggers.tsx
Composer/packages/client/src/pages/design/exportSkillModal/content/index.ts
Composer/packages/client/src/pages/design/exportSkillModal/generateSkillManifest.ts
Composer/packages/client/src/pages/design/exportSkillModal/index.tsx
Composer/packages/client/src/pages/design/exportSkillModal/styles.ts
Composer/packages/client/src/recoilModel/dispatchers/skill.ts
Composer/packages/extensions/adaptive-form/src/components/FormRow.tsx
Composer/packages/extensions/adaptive-form/src/utils/resolveFieldWidget.ts
Composer/packages/extensions/adaptive-form/src/utils/resolveRef.ts
Composer/yarn.lock

- New Steps:
- Configure endpoints
- [#3756] Previously, users had add and configure the manifest's endpoint property in the JSON Editor. This new steps uses the Adaptive Form package to create a schema driven form that allows users to easily modify endpoints and add new ones.
- Select dialogs
- In the select dialogs step, users select which dialogs they want to include in the skill manifest. The dialogs get add to the manifest as event activities in the `activities` property. If the dialog added has a dialog schema, the `value` and `resultValue` schema definitions are included in the manifest.
- Select triggers
- This step is very simple to the previous step - select triggers; however, instead of selecting which dialogs to include, the user selects which triggers from the root dialog …

feat: Generate skill manifest

---

Composer/packages/client/src/hooks/useElectronFeatures.ts
Composer/packages/client/src/pages/design/DesignPage.tsx
Composer/packages/client/src/pages/design/VisualEditor.tsx
Composer/packages/electron-server/__tests__/appMenu.test.ts
Composer/packages/electron-server/src/appMenu.ts
Composer/packages/extensions/adaptive-flow/src/adaptive-flow-editor/AdaptiveFlowEditor.tsx

closes #3844
When Flow Editor is active, use Flow Editor shortcuts.
When Flow Editor is inactive, use Electron native shortcuts.
**Problem**:
Flow Editor registered several shortcuts `cut / copy / delete` in Electron app menu. Those shortcuts overrided and affected native cut copy delete behavior and caused user cannot do plain text editing in Form Editor.
**Solution**
Leveraging Electron menu's `visibile` property, conditionally switching between Flow's shortcuts and native shortcuts.
- When Flow Editor is focused, set mode to 'action', use Flow Editor's shortcut group
- When Flow Editor is blured, set mode to 'native', use system default shortcut group
The focus/blur state of FlowEditor is still posted by Electron rpc api. A new state `flowFocused` was added.
[Copy-Paste]
[Cut]
[Delete]

fix: resolve conflict between Electron native shortcut and FlowEditor shortcuts 

---

Composer/cypress/support/index.ts
Composer/packages/client/src/components/CreationFlow/CreationFlow.tsx
Composer/packages/client/src/pages/home/Home.tsx
Composer/packages/client/src/pages/setting/SettingsPage.tsx
Composer/packages/client/src/pages/setting/dialog-settings/DialogSettings.tsx
Composer/packages/client/src/pages/setting/runtime-settings/RuntimeSettings.tsx
Composer/packages/client/src/recoilModel/dispatchers/project.ts
Composer/packages/client/src/router.tsx
Composer/packages/client/src/utils/hooks.ts
Composer/packages/client/src/utils/projectCache.ts

Current if re-fresh page in home/setting page, all client state are lost. Notice `navigation` are disabled:
other page (design/lg/lu) which url include `:projectId` don't have this issue, cause when refresh page, `projectId` is still in url.
1. Cache projectId at client session storage.
2. Auto-fetch project if current no project is opened.
close #3845 
Refresh in home/setting page wouldn't lost states

fix: refresh page client state lost error.

---

Composer/packages/client/src/components/EditableField.tsx
Composer/packages/client/src/components/MultiLanguage/AddLanguageModal.tsx
Composer/packages/client/src/constants.ts
Composer/packages/client/src/pages/language-generation/table-view.tsx
Composer/packages/client/src/pages/language-understanding/table-view.tsx
Composer/packages/client/src/recoilModel/dispatchers/__tests__/dialog.test.tsx
Composer/packages/client/src/recoilModel/dispatchers/__tests__/lu.test.tsx
Composer/packages/client/src/recoilModel/dispatchers/lg.ts
Composer/packages/client/src/recoilModel/dispatchers/lu.ts
Composer/packages/extensions/adaptive-form/src/components/fields/EditableField.tsx
Composer/packages/lib/indexers/src/utils/luUtil.ts

Some refinement in multiple language & all up view
1. Search box for multiple languages
2. Editable table list view
3. Pretty column space.
#minor 
Search box for multiple languages
Editable table list view
Columns space in 1920px
Columns space in 1280px

fix: multi-lang all up view refinement

---

Composer/packages/client/src/pages/design/exportSkillModal/__tests__/generateSkillManifest.test.ts
Composer/packages/client/src/pages/design/exportSkillModal/constants.tsx
Composer/packages/client/src/pages/design/exportSkillModal/content/Endpoints.tsx
Composer/packages/client/src/pages/design/exportSkillModal/content/SelectDialogs.tsx
Composer/packages/client/src/pages/design/exportSkillModal/content/SelectItems.tsx
Composer/packages/client/src/pages/design/exportSkillModal/content/SelectTriggers.tsx
Composer/packages/client/src/pages/design/exportSkillModal/generateSkillManifest.ts
Composer/packages/extensions/adaptive-form/src/components/FormRow.tsx
Composer/packages/extensions/adaptive-form/src/components/SchemaField.tsx
Composer/packages/extensions/adaptive-form/src/components/fields/ObjectArrayField.tsx
Composer/packages/extensions/adaptive-form/src/utils/__tests__/getOrderedProperties.test.ts
Composer/packages/extensions/adaptive-form/src/utils/getHiddenProperties.ts
Composer/packages/extensions/adaptive-form/src/utils/getOrderedProperties.ts
Composer/packages/extensions/adaptive-form/src/utils/index.ts
Composer/packages/extensions/adaptive-form/src/utils/resolveRef.ts
Composer/packages/extensions/extension/src/types/form.ts

- Endpoints Step
- Hide the `protocol` property since it can only be set to 'BotFrameworkv3' at the moment
- There was a bug in the Adaptive Form package that didn't set the default/const for hidden properties. To resolve this, we shifted the responsibility for hiding fields from the `ObjectField` to the `SchemaField` where the default/const values are set.
- Dialog Selection Step
- Added a description column with an editable field to change the dialog description
- Added a 'Select all' checkbox and hid the select all checkbox in the table
- Select Trigger Step
- Added a 'Select all' checkbox and hid the select all checkbox in the table
closes #3333

feat: Design tweaks to Skill Manifest Generation Wizard

---

Composer/packages/client/src/pages/design/DesignPage.tsx

The reason is the design page will use the location state to navigate to the begin dialog action. The location will be updated by the @reach\router, then we use the location to update the location in our state management. So the first open will use the old location to navigate and get the old project id.
In this PR, check the project to avoid the page navigate to the old bot. 
**I think in R11 we need to make the router and state one way data flow.** #3022
closes #3865

fix: open a new bot will navigate to the old bot

---

Composer/packages/client/src/pages/language-generation/table-view.tsx
Composer/packages/client/src/recoilModel/dispatchers/lu.ts
Composer/packages/lib/indexers/__tests__/lgUtil.test.ts
Composer/packages/lib/indexers/__tests__/luUtil.test.ts
Composer/packages/lib/indexers/__tests__/utils/diagnosticUtil.test.ts
Composer/packages/lib/indexers/src/utils/lgUtil.ts
Composer/packages/lib/indexers/src/utils/luUtil.ts

Fix some regression on lg part, and do some refinement, add more unit test.
close #3867

fix: lg tablelist bugfix & regressions

---

Composer/packages/client/src/recoilModel/dispatchers/project.ts
Composer/packages/client/src/utils/projectCache.ts

The project id is saved to the session storage. When the bot is deleted, composer will use cache to fetch the project.
In this PR, clean the id cache when deleting a bot.
closes #3882

fix: clean the cache when deleting a bot

---

Composer/packages/client/src/pages/publish/createPublishTarget.tsx
Composer/packages/client/src/recoilModel/dispatchers/publisher.ts

Make profile name not editable, because we use name as key in targetList.
Fix profile edit issue because of publishTypes update issue.
#minor 
Profile edit issue during publishing :

fix: do not allow editing of publish profile name

---

Composer/packages/extensions/adaptive-flow/src/adaptive-flow-renderer/configs/builtinSchema.tsx
Composer/packages/lib/shared/src/labelMap.ts
Composer/packages/server/schemas/sdk.uischema
Composer/packages/ui-plugins/composer/src/defaultMenuSchema.ts
Composer/packages/ui-plugins/lg/src/index.ts

closes #3874
note: it still isn't clear where UI is getting component information (label, title, description, etc)

feat: Plumbs UpdateActivity and DeleteActivity into the app

---

Composer/packages/client/src/recoilModel/dispatchers/lu.ts
Composer/packages/client/src/recoilModel/parsers/__test__/luWorker.test.ts
Composer/packages/client/src/recoilModel/parsers/luWorker.ts
Composer/packages/client/src/recoilModel/parsers/types.ts
Composer/packages/client/src/recoilModel/parsers/workers/luParser.worker.ts
Composer/packages/client/src/shell/luApi.ts
Composer/packages/lib/shared/src/types/shell.ts
Composer/packages/ui-plugins/luis/src/LuisIntentEditor.tsx

The same as #3900 
1. bring all parse worker back to worker. The lu parse result has no parse tree, so there is no need to cache the result.
2. add debounced shell api for lu inline editor
refs #3900

fix: Improve performance of the editor behavior in LU

---

Composer/packages/extensions/adaptive-form/src/components/fields/ExpressionField/__tests__/utils.test.ts
Composer/packages/extensions/adaptive-form/src/components/fields/ExpressionField/utils.ts

Update the `getSelectedOption` function to check if the field's `value` is included an options enum schema and return the correct option accordingly.
Closes #3580

fix: Update getSelectedOption to return correct option for enums

---

Composer/packages/client/src/components/TestController/TestController.tsx

Move botStatusInterval out of TestController component, to make sure it won't create duplicated every time component reloaded.
close #3930

fix: "Reloading" spin forever when restart bot

---

Composer/plugins/localPublish/src/index.ts

Fix custom runtime setting error message not shown.
#minor 
previous: 
after fix:

fix: fix custom runtime setting error message not shown

---

Composer/packages/ui-plugins/prompts/src/index.tsx

Per @benbrown's request. 
Added helplinks in Validation Rules.
help link: https://aka.ms/bf-composer-docs-ask-input#prompt-settings-and-validation
The doc will be merged to live soon and the link will point to the newly added "prompt setting and validation" section specifically. 
#minor
https://github.com/microsoft/BotFramework-Composer/issues/3906
https://github.com/microsoft/BotFramework-Composer/issues/3907
Did e2e test and verified the help links exist in all the different types of prompts as required.

doc: add helplinks for validation rules

---

Composer/packages/client/src/components/TestController/TestController.tsx
Composer/packages/server/src/models/bot/botProject.ts

Migrates existing bots to use `qna.endpointKey` instead of `qna.endpointkey` and adds some more defensive accessors when reading from settings.
fixes #3948
fixes #3949

fix: qna settings duplicate endpointKey

---

Composer/packages/client/src/shell/triggerApi.ts

We need to wait for the lu intent creation to finish before navigating to the new url.
I think we need a  mechanism to sync the data between the inline editor and shell in the future.
closes #3971

fix: Hoisted LU editor in form view is not correctly initialized when creating new trigger

---

Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx

update the name will update the formdata.intent. Then the formdata.intent will update the luOption and luOption will trigger the inline editor re-render. The monaco-editor will have two requests when re-rendering.
In this PR use placeholder to fix the luoption and avoid the editor to re-render.
closes #3967

fix: update name don't need to re-render the inline editor when creating a new trigger

---

Composer/packages/client/src/recoilModel/dispatchers/lg.ts
Composer/packages/client/src/recoilModel/dispatchers/lu.ts
Composer/packages/client/src/recoilModel/parsers/__test__/baseWorker.test.ts
Composer/packages/client/src/recoilModel/parsers/baseWorker.ts
Composer/packages/client/src/recoilModel/parsers/workers/lgParser.worker.ts
Composer/packages/client/src/recoilModel/parsers/workers/luParser.worker.ts
Composer/packages/client/src/recoilModel/parsers/workers/qnaParser.worker.ts

Add try catch for the worker result to show the error message
refs #3982

fix: display the detail error messages from worker

---

Composer/package.json
Composer/packages/server/package.json
Composer/plugins/azurePublish/package.json
Composer/plugins/azurePublish/yarn.lock
Composer/plugins/localPublish/package.json
Composer/plugins/localPublish/yarn.lock
Composer/plugins/mockRemotePublish/package.json
Composer/plugins/mockRemotePublish/yarn.lock
Composer/plugins/mongoStorage/package.json
Composer/plugins/mongoStorage/yarn.lock
Composer/yarn.lock

DevOps tests are failing because the NPM package "bl" has security issues, and Dependabot can't see all of them. This should fix those.
#minor

fix: update bl for security reasons

---

Composer/package.json
Composer/yarn.lock

yarn audit reported 52 high sev vulnerabilities all but one related to js-yaml and a single one for tree-kill. This may help get the dev-ops part of CI to pass.
#minor
N/A

fix: Updated to remove 52 high sev issues

---

runtime/dotnet/core/ComposerSettingsExtensions.cs

Currently the runtime logic is if the luis.endpoint is missing from the setting, just use https://{luisRegion}.api.cognitive.microsoft.com
The runtime should also handle the condition when luis.endpoint does exist but it is an empty string. 
closes #4026

fix: Handle luis.endpoint empty

---

Composer/packages/adaptive-form/src/utils/uiOptionsHelpers.ts
Composer/packages/server/src/locales/en-US.json

This updates the locale files to match the new strings found in the code. Adding the localization tool to "yarn build" was intended to make this process happen automatically, but it's still possible for a change to merge without that script being run first, leading to locale files being out of sync.
This also picks up one more string that got missed.
closes #4134

fix: sync locale files and add missing "example" string

---

Composer/package.json
Composer/yarn.lock

Adds `selfsigned` to resoltuions instead of `node-forge` which bumps the `node-forge` dependency.
#minor

chore: add selfsigned to resolutions

---

Composer/packages/electron-server/src/appUpdater.ts
Composer/packages/electron-server/src/main.ts

When the auto download is on, explicit check for update does not show any feedback to the user.
closes #4099
N/A

fix: explicit check for update feedback

---

Composer/packages/client/__tests__/components/skill.test.tsx
Composer/packages/client/src/components/CreateSkillModal.tsx
Composer/packages/client/src/pages/design/DesignPage.tsx
Composer/packages/client/src/pages/skills/index.tsx
Composer/packages/client/src/pages/skills/skill-list.tsx
Composer/packages/client/src/recoilModel/dispatchers/__tests__/skill.test.ts
Composer/packages/client/src/recoilModel/dispatchers/skill.ts
Composer/packages/server/src/models/bot/skillManager.ts
Composer/packages/ui-plugins/select-skill-dialog/src/BeginSkillDialogField.tsx

Adds an endpoint dropdown to the add skill modal which allows the user to select which messaging endpoint they want to use when they add the skill. The `msAppId` and `endpointUrl` for the endpoint the user selects is serialized to the `skills` object in the bot settings with the other skill data - `name` and `manifestUrl` - provided in the modal.
Closes #4122
Closes #4087

feat: Add endpoint dropdown to the add skill modal

---

Composer/packages/client/src/pages/design/DesignPage.tsx
Composer/packages/server/__tests__/models/bot/botProject.test.ts
Composer/packages/server/src/models/bot/botProject.ts
Composer/packages/server/src/models/utilities/util.ts

We should do migration on server. This pr will check missing qna files, create them and return all files to client.
Closes #4168

fix: qna migration bug

---

Composer/packages/extension/src/manager/manager.ts
Composer/packages/extension/src/storage/extensionManifestStore.ts

In #4224, the way builtin plugins are loaded changed which breaks when the `extensions.json` file already existed, due to a failure to load the `sample-ui-plugin`. This just removes that from the manifest.
#minor

fix: fix loading of extensions by removing sample-ui-plugin

---

Composer/packages/client/src/recoilModel/dispatchers/storage.ts
Composer/packages/server/src/controllers/storage.ts

Did not encode when sending http request but decode on server side.
Closes #4236 
Closes #4250

fix: URL encode bug

---

Composer/packages/lib/code-editor/src/BaseEditor.tsx
Composer/packages/lib/code-editor/src/utils/common.ts

Monaco editor has option config to auto detect urls in text. ctrl + click on it will call vscode.open() -> window.open() open url.
Our current electron setting can handle `<a target="_blank">open in browser</a>`, but electron@8.2.4 seems has issue accept correct arguments. then we will see a empty page, case the accepted arguments `url` is `about:blank`.
If we upgrade electron@10.1.1, the electron opened window would be correctly, but still failed to open in default browser.
So before find a better way, current fix is disable link detecting in BaseEditor.text for electron environment.
close #4070
Before (electron): 
After (electron):

fix: Monaco editor links opened in blank window in electron

---

Composer/packages/client/src/pages/design/DesignPage.tsx

do not create duplicated qnamaker kind trigger through Add new knowledge base on {dialogName}
Closes #4059

fix: do not create duplicated qnamatcher trigger

---

Composer/packages/client/src/utils/notifications.ts
Composer/packages/server/src/locales/en-US.json

Another round of l10n string updates, including a slight change to a notification string to remove some extraneous Surface Go branding.
#minor

fix: resync locale strings

---

Composer/packages/server/package.json

Adds the missing reference to \Composer\packages\server\package.json
"tslib": "^2.0.0",
Closes #4024

fix: Adding missing tslib reference to server packages

---

Composer/packages/client/src/pages/setting/SettingsPage.tsx
Composer/packages/client/src/pages/setting/extensions/ExtensionSearchResults.tsx
Composer/packages/client/src/pages/setting/extensions/Extensions.tsx
Composer/packages/client/src/pages/setting/extensions/InstallExtensionDialog.tsx
Composer/packages/client/src/recoilModel/types.ts
Composer/packages/client/src/utils/hooks.ts
Composer/packages/client/src/utils/pageLinks.ts
Composer/packages/extension/src/manager/manager.ts
Composer/packages/extension/src/utils/npm.ts
Composer/packages/server/src/controllers/__tests__/extensions.test.ts
Composer/packages/server/src/controllers/extensions.ts

fix: minor UX fixes for installing extensions

---

Composer/.eslintrc.js
Composer/package.json
Composer/packages/electron-server/src/main.ts
Composer/packages/extension/package.json
Composer/packages/extension/src/extensionContext.ts
Composer/packages/extension/src/manager/__tests__/manager.test.ts
Composer/packages/extension/src/manager/manager.ts
Composer/packages/extension/src/types/extension.ts
Composer/packages/extension/src/utils/__tests__/isSubdirectory.test.ts
Composer/packages/extension/src/utils/__tests__/npm.test.ts
Composer/packages/extension/src/utils/isSubdirectory.ts
Composer/packages/extension/src/utils/npm.ts
Composer/packages/server/src/server.ts
Composer/packages/tools/language-servers/language-understanding/package.json
Composer/plugins/README.md
Composer/plugins/authTest/package.json
Composer/plugins/azurePublish/package.json
Composer/plugins/githubAuth/package.json
Composer/plugins/localPublish/package.json
Composer/plugins/mockRemotePublish/package.json
Composer/plugins/mongoStorage/package.json
Composer/plugins/publishTest/package.json
Composer/plugins/runtimes/package.json
Composer/plugins/samples/package.json
Composer/plugins/webRoute/package.json
Composer/yarn.lock

Directly download and unpack extensions using the npm registry api. This enables a unified approach to loading built-in vs remote extensions and results in more transparent installation output.
#minor

refactor: change method of installing extensions

---

Composer/packages/adaptive-form/src/utils/arrayUtils.ts
Composer/packages/adaptive-form/src/utils/objectUtils.ts

When the Property Editor switches between two actions of the same type, the `useArrayItems` and `useObjectItems` caches were not resetting. 
Closes #4276

fix: Fixed useArrayItems and useObjectItems

---

Composer/cypress/integration/TriggerCreation.spec.ts
Composer/packages/adaptive-flow/__tests__/adaptive-flow-renderer/transformers/todoBot.main.json
Composer/packages/adaptive-flow/demo/src/samples/todo/ToDoBot.main.json
Composer/packages/client/__tests__/constants.json
Composer/packages/server/src/__mocks__/asset/projects/SampleBot/bot1.dialog
Composer/packages/server/src/locales/en-US.json
Composer/packages/ui-plugins/composer/src/defaultRecognizerSchema.ts
Composer/plugins/samples/assets/projects/TodoSample/todosample.dialog

The naming convention between the different recognizer types is inconsistent when the user clicks on the associated dropdown. These changes are implemented to bring consistency across the various JSON, .spec.ts, and .dialog files.
Replaces #4297 
Closes #4060
e2e test:

fix: Updates regular expressions formatting and naming convention

---

Composer/packages/server/schemas/sdk.uischema
runtime/dotnet/azurewebapp/Schemas/sdk.uischema

Those changes enable Intellisense to leverage the uiSchema in order to know what type of completion items to show.
Step 1 was modifying the schema of the uiSchema: microsoft/botframework-sdk#6047
Step 2 was updating the uiSchema of individual components: microsoft/botbuilder-dotnet#4704
Step 3 was updating Composer to leverage the uiSchema for Intellisense: https://github.com/microsoft/BotFramework-Composer/pull/4263
This final step is to update Composer's uiSchema itself.
The schema was generated running bf _dialog:merge "libraries/**/*.schema" "libraries/**/*.uischema"_ from botbuilder-dotnet
fixes #4187
fixes #4189 
Intellisense:
Example of schema change:

feat: Updating uiSchema in Composer

---

Composer/packages/server/src/models/bot/botProject.ts

#minor
closes #4419 
PVA prefers the naming convention `app.*schema` over the `sdk.*schema`.
This PR lets the project loader load 4 aliases of schema files:
- `app.schema` -> `sdk.schema`
- `app.override.schema` -> `sdk.override.schema`
- `app.uischema` -> `sdk.uischema`
- `app.override.uischema` -> `sdk.override.uischema`
The `app.*` schema files will take priority over `sdk.*` files.

feat: support app schema

---

Composer/packages/server/package.json
Composer/yarn.lock
extensions/azurePublish/package.json
extensions/azurePublish/src/luisAndQnA.ts
extensions/azurePublish/yarn.lock
extensions/runtimes/src/index.ts

In #4351 we have updated the bf-cli version. But the azure publish copied the build logic from the server and client. It will fail if we update the bf-lu version. 
1. use previous bf-lu version in azure publish as a short term fix.
2. The luis settings' structure changed  (lubuild result)  in previous PR. update the get function.
3. update the azure plugin relative path. (the plugins folder path changed in #4399).
4. update the down-sampling library version
#minor

fix: azure publish failed

---

Composer/packages/server/src/models/bot/__tests__/botProject.test.ts
Composer/packages/server/src/models/bot/botProject.ts

Excluded settings and scripts from glob patterns.  These folder contents are not directly part of the project files loaded.
Fixes #4407
N/A

fix: Excluded settings and scripts globs

---

Composer/packages/client/src/hooks/useElectronFeatures.ts
Composer/packages/client/src/pages/design/DesignPage.tsx

#minor
**Problem** When moving cursor around Action flyout menu, whole UI stuck.
**Root cause**
According to this issue https://github.com/microsoft/fluentui/issues/5642 , when loading FluentUI's ContextualMenu, browser's focus state will be affected unexpectedly. In our case, when using the Action flyout menu, the browser focus state (triggered by onFocus and onBlur event) would be changed repeatedly for multiple (around 20) times.
Unfortunately, the browser's focus state was saved as a React state in DesignPage and post to Electron via IPC to enable/disbale the Electron app menu. As a result, everytime user moves cursor around the flyout menu, the design page will be redraw for tons of times which led to the UI stuck.
**Solution**
This PR fixes this issue by saving the focus state as a …

fix: perf problem of Action flyout menu

---

Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx

Missing a $ in a format string for a project tree item key
#minor
N/A

fix: Missing $ in format string

---

Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/TriggerSummary/TriggerSummary.tsx

fix: change Flow Editor Trigger icon to 'LightningBolt'

---

Composer/packages/client/__tests__/utils/convertUtils/designerPathEncoder.test.ts
Composer/packages/client/src/utils/convertUtils/designerPathEncoder.ts

#minor 
When clicking on a child action under a case of SwitchCondition, Composer will redirect to root dialog.
This is caused by the data path `triggers["nPWg4L"].actions["CSz3HO"].cases[0].actions["r3Mhiy"]` cannot be recognized by url decoder.
Previously, the url decoder only supports pure index-based format or pure designer-based format. This PR lets the decoder support a mixed format data path.

fix: SwitchCondition's path cannot be parsed correctly

---

Composer/packages/client/src/pages/publish/createPublishTarget.tsx
Composer/packages/client/src/pages/publish/styles.ts

The pva publish iframe was too small, truncating the view and ruining the experience.
#minor
**Before:**
**After:**

fix: Added custom iframe styling for pva publish

---

Composer/packages/adaptive-form/src/utils/resolveFieldWidget.ts

**resolveFieldWidget** assumed that all expressions start with "=". But there are two types of expressions:
- **equalsExpression**
- **expression**
As such, schema types that were **oneOf** between **expression** (not **equalsExpression**) and a list of non string types were enable to resolve when the input was a string. Such an example is **condition**:
```
"condition": {
"$role": "expression",
"title": "Boolean condition",
"description": "Boolean constant or expression to evaluate.",
"oneOf": [
{
"$ref": "#/definitions/expression"
},
{
"type": "boolean",
"title": "Boolean",
"description": "Boolean value.",
"default": true,
"examples": [
false
]
}
]
},
```
This PR addresses this issue by resolving to a regular input field when the type is an **expression**.
fixes #4479

fix: Expressions not starting with "=" can resolve to a regular TextField

---

Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
Composer/packages/lib/indexers/src/groupTriggers.ts

Triggers w/o properties were missing, this now provides the form-wide group
Updated to include expectedProperties in property search
Fixes #4534

fix: Add form-wide and better trigger grouping

---

extensions/pvaPublish/src/node/constants.ts
extensions/pvaPublish/src/node/publish.ts

The `baseUrl` that is provided from PVA in the publishing profile configuration has the form:
`https://bots.int.customercareintelligence.net/`
with just the host name. So I adjusted the constant base URLs to adhere to this shape.
#minor

fix: Fixed pva publish base url bug

---

Composer/packages/lib/indexers/src/groupTriggers.ts
Composer/packages/server/package.json
Composer/yarn.lock

Fixes a small issue where the filter was applied to the triggers rather than the property names.
Closes #4539 
N/A

fix: Filter property names, not trigger

---

Composer/packages/server/src/controllers/formDialog.ts
Composer/packages/server/src/models/bot/botProject.ts
Composer/packages/server/src/router/api.ts

Deleting a form dialog requires deleting form dialog assets which are all contained within a folder under dialogs.
#minor
#4505
N/A

fix: Add delete form dialog to Composer server API

---

Composer/packages/client/src/recoilModel/dispatchers/dialogs.ts
Composer/packages/client/src/utils/qnaFileStatusStorage.ts

a small undefined variable bug.
Closes #4511

fix: delete dialog bug

---

Composer/packages/client/src/recoilModel/dispatchers/dialogs.ts
Composer/packages/client/src/recoilModel/dispatchers/formDialogs.ts
Composer/packages/server/src/locales/en-US.json

Calls form dialog dedicated delete api when dialog is removed
#minor
#4505

fix: Calls form dialog dedicated delete api when dialog is removed

---

Composer/packages/intellisense/src/components/Intellisense.tsx

- onBlur when pressing Tab
- using keydown instead of keyup so that Intellisense doesn't disappear from the next field being tabbed to
closes #4573

fix: Intellisense doesn't disappear when tabbing out of a field 

---

Composer/cypress/integration/NotificationPage.spec.ts
Composer/cypress/integration/ToDoBot.spec.ts
Composer/packages/server/src/models/bot/botProject.ts
Composer/packages/server/src/models/bot/botStructure.ts

This is the #4520 's follow up. In #4520 we only preserve the root dialog. The lu and lg also can't be updated when precerveRoot is true.
1. preserve the root lu and lg file.
2. update the id in root dialog content.
3. update the recognizer generate
#minor
#refs #4520

fix: preserve the root files when creating a PVA bot

---

Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx

This fixes a small glitch in generating URLs for the links; dialogs and triggers that belong to the root of a botProject now generate links that look like the older non-botProject ones, which should fix some issues with undo/redo.
#minor

fix: generate correct URLs for root bots

---

Composer/packages/server/src/models/bot/botProject.ts

Excluding luconfig.json from file loading to prevent duplicate conflicts for multiple form dialogs generated.
#minor 
N/A

fix: Excluded luconfig.json from project load

---

Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx

fix: increase the size of 'warning' icon in Trigger modal

---

Composer/packages/client/src/components/Notifications/NotificationContainer.tsx

When create notification card dismissed, the empty notification panel will still cover on buttons such as Test/Start/Show code. Introduced in #4484 
close #4644

fix: Test/Start buttons unable to click.

---

Composer/packages/server/src/models/bot/botProject.ts
extensions/azurePublish/package.json
extensions/azurePublish/src/index.ts
extensions/azurePublish/yarn.lock

the recognizer file is end with .dialog, in azurepublish plugin will regard them as dialog.
The bf-lu package version is updated in other PR, we need to preserve the old version. We didn't update the plugin's build logic
1. filter the recognizer file
2. update the bf-lu to old version
closes #4636

fix: Bot publish to azure failed in cross train step

---

Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
Composer/packages/server/src/controllers/formDialog.ts

delete root dialog button is hidden and add checks on server side.
Closes #4626

fix: does not allow to delete root bot

---

Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx

closes #4635 
1. Decrease the wait time from 1000ms to 200ms.
2. Use `throttle` instead of `debounce` to provide fluent experience especially when the search box is reset.

fix: optimize the search experience in ProjectTree

---

Composer/packages/adaptive-flow/__tests__/adaptive-flow-editor/stubs/ShellApiStub.ts
Composer/packages/adaptive-flow/src/adaptive-flow-editor/hooks/useEditorEventApi.ts
Composer/packages/client/src/shell/useShell.ts
Composer/packages/types/src/shell.ts

closes #4616 
**Problem**:
New action not focused automatically
**Root cause**:
Related to $designer.id encoded URL.
The focusPath is calculated based on old dialog data where $designerId is for wrong Action.
**Solution**:
Let `saveData()` return a Promise, postpone the calculation of next focused Action to after dialog updated.
It will correct the behavior of:
1. Create new Action via flyout menu
2. Paste Action from clipboard

fix: let newly created Action be focused automatically

---

Composer/packages/lib/shared/src/featureFlagUtils/index.ts
Composer/packages/server/src/services/featureFlags.ts

Hiding form dialogs feature switch for composer 1.2 (hidden:true in the defaults)
There were issues with the feature switch service that caused hidden:true to not hide the switch.
I refactored to fix the following:
- filter statements were returning values and not booleans
- hidden switches needed to follow the process.env for enabled
- hidden switches that were updated weren't properly causing the storage to save again
- the display name and description shouldn't be saved as user data
- the defaults were only applied if the key was not present, needed to merge defaults and currents per key
Fixes #4621

fix: Form dialog hidden fixed feature flags

---

extensions/localPublish/src/index.ts
extensions/runtimes/src/index.ts

Fix JS runtime eject issue. 
**Cause**:  npm install timeout when ejecting. 
**Solution**: don't doing npm install in ejecting, just install and build before publish.
close #4011

fix: fix js runtime eject issue

---

Composer/packages/server/src/models/bot/builder.ts

Composer is calling luis build api to publish luis models and generate luis settings file. But currently in composer, the config.region is not passed into luis build api that makes the luis settings file name `luis.settings.{environment}.{region}.json` consumed the default westus region even if users are specifying other regions.
Closes #4663

fix: region is not set correctly when generating luis settings file name in luis build call

---

Composer/packages/adaptive-form/src/components/fields/RegexIntentField.tsx

closes #4653 
Fix the problem that intent value not shown when the recognizer is RegexRecognizer.
Reference: https://github.com/microsoft/BotFramework-Composer/pull/4383/files#r517765615

fix: show intent value in the "Trigger phrases" field of a RegEx intent

---

Composer/packages/client/src/utils/hooks.ts
Composer/packages/client/src/utils/routerCache.ts

bug: router cache saved url with previous projectId
need to clean all router cache data after switching project
Closes #4639

fix: router cache bug

---

Composer/packages/adaptive-form/src/components/fields/OneOfField/__tests__/utils.test.ts
Composer/packages/adaptive-form/src/components/fields/OneOfField/utils.ts

"object" was the default type for fields accepting **valueExpression**, such as **Microsoft.SetProperty**.
This was due to the fact that the default type is simply the first one mentioned in the schema:
As such the dropdown for fields using **valueExpression** was listing in that order: object -> array -> string -> boolean -> number, with object being the default.
One solution to this problem could be to modify the ordering in the schema.
The approach taken in this PR instead is to have a mappings of type to weights to give more priority to certain types (such as string) and order based of that.
closes #4654

fix: Sorting OneOfField options / better default type

---

Composer/packages/client/src/recoilModel/dispatchers/lg.ts

1. update 'common.lg', re-parse 'common.lg', 
2. update 'hello.lg', re-parse 'hello.lg';
to keep minimal re-parse will improve client performance.
1. in 'hello.lg', refer a template named 'Welcome' imported from 'common.lg'
2. change a template name from 'Welcome' to 'Welcome1' in 'common.lg'. 
'hello.lg' would not be able to update it's diagnostics, cause re-parse only happen on 'common.lg'
1. when update on 'common.lg', re-parse all lg files. because 'common.lg' maybe referred by other lg files.
2. when update on 'hello.lg', still only re-parse 'hello.lg' itself. because 'hello.lg' suppose to be standalone.
it can reduce file diagnostics not sync issue, but not totally solve it.
close #3884

fix: LG file diagnostics not always sync.

---

Composer/packages/client/src/recoilModel/selectors/projectTemplates.ts

Starting up Composer was failing for me because it was looking for this "enabled" prop on a flag that didn't exist. This changes that one line to match a similar case above.
#minor

fix: optionalize check for template creation flag

---

Composer/packages/client/src/pages/notifications/NotificationList.tsx
Composer/packages/client/src/pages/notifications/Notifications.tsx
Composer/packages/client/src/pages/notifications/types.ts
Composer/packages/client/src/pages/notifications/useNotifications.tsx
Composer/packages/client/src/recoilModel/selectors/index.ts
Composer/packages/client/src/recoilModel/selectors/messagers.ts

1. Also show skill bot's notification, add a column 'Bot' to show message belong to  which bot.
2. Fix deep link to Design page etc.
close #4638

fix: Notification deep link

---

Composer/packages/client/src/recoilModel/Recognizers.tsx

Can't use startsWith here, if the dialog name is a.dialog and ab.dialog, the filter for lu files will be wrong
closes #4705

fix: the generated recognizer files is messy when the dialog name has the same prefix

---

Composer/packages/adaptive-flow/src/adaptive-flow-editor/hooks/useEditorEventApi.ts
Composer/packages/client/src/recoilModel/dispatchers/navigation.ts
Composer/packages/client/src/recoilModel/undo/history.ts
Composer/packages/client/src/shell/useShell.ts
Composer/packages/types/src/shell.ts

Editors use the designpage location to calculate some important values.
The data flow now is saveData -> commitChanges -> navigate. So undoHistory can't get the correct locations.
In this PR add callback for shellApi.saveData to make sure the navigate is before commit. Update the designPageLocation when navigate.
#minor
refs #4620

fix: undo/redo can't navigate to the correct position

---

Composer/packages/adaptive-flow/src/adaptive-flow-renderer/components/ElementMeasurer.tsx

#minor 
Follows #4672 
In #4672, we use `scroll` rather than `bounds` to measure node size. This change broke the layouter of Flow Editor.
This PR fixes the issue by reading `scroll` instead of `bounds` in the `onResize` handler.
**Wrong layout**:
**Correct layout**:

fix: Flow Editor 'onResize' handler not working

---

Composer/packages/adaptive-flow/src/adaptive-flow-renderer/components/ElementMeasurer.tsx
Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
Composer/packages/client/src/pages/design/DesignPage.tsx

#minor
1. Follows #4652, redirect to the specific dialog url instead of main dialog.
2. Follows #4630, increase icon size to 12px (5px -> 8px -> 12px).

fix: update incompatible Trigger redirect url & icon size

---

extensions/azurePublish/webpack.config.js
extensions/azurePublish/yarn.lock
extensions/localPublish/webpack.config.js
extensions/localPublish/yarn.lock
extensions/runtimes/webpack.config.js
extensions/samples/webpack.config.js
extensions/vacore/webpack.config.js
extensions/vacore/yarn.lock

Allows node extensions bundled by webpack to use `__dirname` appropriately.
#minor

fix: do not stub __dirname for node extensions

---

Composer/packages/client/src/pages/design/DesignPage.tsx

Fixes an issue where the designer cannot load because a trigger does not have $designer.
fixes #4750

fix: account for undefined $designer in breadcrumb

---

extensions/authTest/webpack.config.js
extensions/azurePublish/webpack.config.js
extensions/githubAuth/webpack.config.js
extensions/localPublish/webpack.config.js
extensions/mockRemotePublish/webpack.config.js
extensions/mongoStorage/webpack.config.js
extensions/runtimes/webpack.config.js
extensions/sample-ui-plugin/webpack.config.js
extensions/samples/webpack.config.js
extensions/vacore/webpack.config.js
extensions/webRoute/webpack.config.js

Setting `mainFields` to ['main'] forces webpack to only resolve a package's main module, bypassing loading it's `module`.
[Webpack docs](https://webpack.js.org/configuration/resolve/#resolvemainfields)
#minor

fix: force node extensions to only require commonjs

---

Composer/packages/client/src/components/ImportModal/ImportModal.tsx

Previously, the import flow was using the standard browser `fetch` API, and then switched to `axios` which actually throws on all non-200 HTTP responses.
There was code that was expecting a 404 from the `getAlias` API to fall through and not throw, so I've bypassed 404 in axios' built-in status number validation.
#minor

fix: Allowed 404 to fall through axios during import flow

---

.vscode/launch.json
Composer/packages/client/__tests__/pages/publish/Publish.test.tsx
Composer/packages/client/src/pages/publish/Publish.tsx
Composer/packages/client/src/pages/publish/pullDialog.tsx
Composer/packages/client/src/pages/publish/pullFailedDialog.tsx
Composer/packages/client/src/pages/publish/pullStatus.tsx
Composer/packages/client/src/recoilModel/dispatchers/project.ts
Composer/packages/client/src/recoilModel/types.ts
Composer/packages/server/src/controllers/project.ts
Composer/packages/server/src/controllers/publisher.ts
Composer/packages/server/src/router/api.ts
Composer/packages/server/src/services/project.ts
Composer/packages/types/src/publish.ts
Composer/yarn.lock
extensions/pvaPublish/package.json
extensions/pvaPublish/src/node/index.ts
extensions/pvaPublish/src/node/publish.ts

This PR enables the ability for publishing extensions to implement the "pull" method to provide updated bot content from a remote source.
Fixes #4385

feat: Implement pull from publish target

---

Composer/packages/adaptive-form/src/components/AdaptiveForm.tsx
Composer/packages/adaptive-form/src/components/PropertyEditorHeader.tsx
Composer/packages/adaptive-form/src/components/__tests__/PropertyEditorHeader.test.tsx
Composer/packages/client/src/pages/design/DesignPage.tsx
Composer/packages/client/src/pages/design/ManifestEditor.tsx
Composer/packages/client/src/pages/design/PropertyEditor.tsx
Composer/packages/client/src/pages/design/PropertyEditorHeader.tsx
Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts

This PR adds a header to the property  editor when the botname is clicked in the project tree and no dialogs are selected. Default routing to main dialog is stopped.

feat: Property Editor Header when botname is selected in Project tree

---

Composer/packages/client/src/components/ImportModal/ImportModal.tsx
Composer/packages/client/src/pages/publish/Publish.tsx
Composer/packages/client/src/pages/publish/publishStatusList.tsx
Composer/packages/types/src/publish.ts
Composer/packages/types/src/server.ts
Composer/packages/ui-plugins/cross-trained/src/index.ts
extensions/pvaPublish/src/node/publish.ts
extensions/pvaPublish/src/node/types.ts

- fixes flakiness in publishing to PVA due to a race condition when writing the .zip to the outgoing request
- adds support to the publish status page for clickable actions or links (ex. "Test in PVA" after publishing)
- should fix inconsistencies with invalid dates appearing in the publish status list
- fixes wrong path in the success notification after an import (was pointing to bot location instead of backup location)
- expands the width of the publish job log
fixes #4385

fix: Several PVA integration improvements / bug fixes

---

Composer/packages/server/src/server.ts

A csrf token was not present when rendering the plugin host causing it to error.
#minor

fix: plugin hosts are not able to load

---

Composer/packages/client/src/pages/design/DesignPage.tsx

#minor
**BEFORE**
**AFTER**
(Fullscreen)

fix: Made the default width of the Property Editor larger

---

Composer/packages/electron-server/src/electronWindow.ts
Composer/packages/electron-server/src/main.ts

Fixes linux icons on the taskbar, tested on Ubuntu.
#minor

fix: Fixes linux icons on the taskbar

---

Composer/packages/server/src/externalContentProvider/powerVirtualAgentsProvider.ts

Some extra, unwanted characters were being added to the end of the downloaded .zip from PVA. This PR removes those characters.
#minor

fix: Removed some extraneous characters from the downloaded pva zip name

---

Composer/scripts/compileExtensions.js

`yarn build:extensions --force` will now force a rebuild of all the extensions.
#minor

build: add option to force rebuild of extensions

---

Composer/packages/server/src/models/bot/botProject.ts

Passing in the metaSchema (or app schema) for generated dialogs to point at SDK schema for given language.
Closes #4676 
N/A

fix: set app schema for generated dialogs

---

Composer/packages/electron-server/package.json

`DEBUG=composer*` is not valid syntax on Windows so I've passed it to the `cross-env` package
#minor

fix: X-platform fix for electron-server "start" script

---

extensions/pvaPublish/src/node/publish.spec.ts
extensions/pvaPublish/src/node/publish.ts

Previously, in the case that PVA would send back a response other than what was expect (202), we would discard any info in the response and simply display a 500 and say something went wrong.
With this change, we look for the 202, and if we do not receive a 202, we try to surface the response from PVA in the Composer UI.
#minor

fix: Added better error handling in pva publish extension's publish method

---

Composer/packages/client/src/pages/knowledge-base/table-view.tsx

Previously, questions are all rendered, even rows are collapsed, expand is set question components 'hide'/'show'. That cause perf issue when QnA is large. benchmark from low performance laptop:
1. when table list first page ( top 10 QnA pairs ), questions amount more than 1000, scroll on list will feel 1s delay.
2. when questions amount less than 500, UX still feel smoothy.
3. when each pairs don't have much alternative questions, more than 10000 line qna file still smooth, UX works fine.
So the bottleneck is rendered too many hide question components in viewport. and the amount of QnA pairs will not cause perf issue. 
Fix it by render only one question when row collapsed.
close #4849

fix: QnA list render slow issue

---

Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts

if the bot project only contains a root bot. The botProjectSpaceLoaded is not set to true.
Closes #4845

fix: luis key not initialized

---

Composer/packages/client/src/App.tsx
Composer/packages/client/src/components/AppComponents/Assistant.tsx
Composer/packages/client/src/components/DataCollectionDialog.tsx
Composer/packages/client/src/pages/setting/app-settings/AppSettings.tsx
Composer/packages/client/src/pages/setting/app-settings/SettingToggle.tsx
Composer/packages/client/src/recoilModel/atoms/appState.ts
Composer/packages/client/src/recoilModel/dispatchers/__tests__/serverSettings.test.tsx
Composer/packages/client/src/recoilModel/dispatchers/index.ts
Composer/packages/client/src/recoilModel/dispatchers/serverSettings.tsx
Composer/packages/server/src/controllers/__tests__/settings.test.ts
Composer/packages/server/src/controllers/settings.ts
Composer/packages/server/src/router/api.ts
Composer/packages/server/src/services/settings.ts
Composer/packages/types/src/index.ts
Composer/packages/types/src/telemetry.ts

Adds a prompt when the user opens the app to opt-in or opt-out of data collection. It also adds the ability for them to change their data collection preferences in the Application Settings. 
Closes #4766

feat: Add data collection dialog and settings

---

Composer/cypress/integration/LuisDeploy.spec.ts
Composer/cypress/integration/NotificationPage.spec.ts
Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
Composer/packages/client/src/components/ProjectTree/treeItem.tsx
Composer/packages/client/src/pages/diagnostics/Diagnostics.tsx
Composer/packages/client/src/pages/diagnostics/types.ts
Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
Composer/packages/client/src/recoilModel/selectors/diagnosticsPageSelector.ts
Composer/packages/client/src/recoilModel/selectors/index.ts
Composer/packages/client/src/utils/navigation.ts
Composer/packages/client/src/utils/pageLinks.ts

1. disable start bot button when there are some errors
2. fix the diagnostic link error in sidebar
3. add link for setting page
#minor

chore: update the navigation link for setting page

---

Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
Composer/packages/electron-server/scripts/copy-artifacts.js

1. Copy artifacts was not copying the top level files in a given folder.
2. Removes extra spacing for form property names that dont have an icon in the project tree.
#minor

fix: fixes form dialog generation on electron

---

Composer/packages/server/src/controllers/publisher.ts
extensions/pvaPublish/src/node/index.ts

fix getHistory always return empty array.
reason: the function defined in publishplugin interface is getHistory, not history.
#minor

fix: get history always return empty array

---

Composer/packages/server/src/controllers/publisher.ts
extensions/pvaPublish/src/node/index.ts

cherry pick get history always return empty array
#minor

chore: cherry pick get history always return empty array

---

Composer/packages/client/__tests__/navItem.test.tsx
Composer/packages/client/src/components/AppComponents/SideBar.tsx
Composer/packages/client/src/components/Header.tsx
Composer/packages/client/src/components/NavItem.tsx
Composer/packages/client/src/utils/hooks.ts
Composer/packages/client/src/utils/pageLinks.ts

This rewrites some of the logic of how we decide which sidebar icon to highlight; detecting that a URL matches its "to" link doesn't work when there's a "skill/<skill ID>" in the way. Instead, this uses some simple regexes to detect the page mode.
This also fixes a minor issue where the "Start Bots" button was showing up in the header on the home screen.
closes #4918

fix: use URL to select sidebar icons and fix pathname in header

---

Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
Composer/packages/client/src/recoilModel/dispatchers/multilang.ts
Composer/packages/client/src/shell/useShell.ts

Dialog creation uses the currently selected dialog to seed the data for the new dialog. With the new bot project work we can have urls to the bot name and not redirected to the main dialog always. Essentially, this PR makes sure if no dialog is selected we get the seed data from root dialog.
Fixes #4821

fix: Dialog creation, trigger creation error resolved

---

Composer/packages/client/src/components/ProjectTree/ExpandableNode.tsx
Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
Composer/packages/client/src/recoilModel/atoms/appState.ts
Composer/packages/client/src/recoilModel/dispatchers/__tests__/editor.test.tsx
Composer/packages/client/src/recoilModel/dispatchers/editor.ts
Composer/packages/client/src/shell/useShell.ts

1. make the copy move and paste work for just in bot.
2. update the setting link in context menu
closes #4921

fix: make copy, move and paste work for one bot instead of cross bots

---

Composer/packages/client/src/components/ProjectTree/ExpandableNode.tsx
Composer/packages/client/src/components/ProjectTree/treeItem.tsx

The line-height from parent make the component height bigger than the container.
#minor

fix: the board in project tree on the ellipsis is taller

---

Composer/packages/client/src/pages/design/styles.ts

let flex box to calculate the height by itself
closes #4949

fix: scrolling issue in propertyeditor

---

Composer/packages/server/src/models/bot/botProject.ts
Composer/packages/server/src/models/bot/builder.ts

- The cross train config is from the settings/cross-train.config.json, but sever use wrong config name(cross-train.config), so crossTrain get the empty config content.
- CrossTain config contains the empty lu files, but sever filters the empty files. crosstrain api will throw error when no lu file find.
In this PR:
1. use the correct config file name.
2. don't filer the empty lu files. (The bf-lu will filter the empty files and the empty lu file will never generate the orcherator recognizer files)
closes #4960

fix:  missing cross train config

---

Composer/packages/server/src/models/bot/builder.ts

- The cross train config is from the settings/cross-train.config.json, but sever use wrong config name(cross-train.config), so crossTrain get the empty config content.
In this PR:
1. use the correct config file name.
refs #4961

chore: cherry pick #4961 to v1.2.2

---

Composer/packages/client/src/recoilModel/dispatchers/lu.ts
Composer/packages/client/src/recoilModel/dispatchers/trigger.ts

Delete dialog will also delete lu file. Then luis key is not needed. This works as expected. But delete trigger, if the referred intent is the last one in the lu file. Then luis key is not needed either. The bug is: lu file name missing locale.
Closes #4950

fix: the parameter lufile name is not correct when removing lu intent

---

extensions/packageManager/src/node/index.ts

Resolves an issue where runtimes configured with a relative path would fail to install components.
#minor

fix: Add support for relative runtime paths in package manager

---

Composer/packages/client/src/pages/publish/Publish.tsx
Composer/packages/client/src/pages/publish/PublishDialog.tsx

- fix memory leak 
- delete backgroud color for publish dialog
#minor

fix: Memory leak & UI adjust for publish page

---

Composer/packages/lib/indexers/src/botIndexer.ts

This is a fix to fix #4971 - there was a mistake in LU check.  Was meant to say if `luProvider` is undefined or `luProvider` is LUIS, then this dialog is using LUIS.
closes #4953

fix: Remove LUIS key error if LUIS not used

---

Composer/packages/client/src/utils/pageLinks.ts

publish page link on left navigation list is not correct.
Closes #4982

fix: publish url on left navigation list

---

Composer/packages/ui-plugins/lg/src/LgField.tsx

closes #4955 
In generative dialog, the lg file in the dialog only contains some import statements. 
The issues is caused by LGOption contains the wrong file id. Once it is passed to language server, it will throw unexpected duplicated definition error. Also, it will also make the sendResponse node uneditable.
To fix this, we need add a lookup function to find out the correct lg file id which contains current template id.
After the fix, the error will disappear and the body is editable.

fix: make sure LGOption has the correct LG file id in LGField

---

Composer/packages/client/src/recoilModel/dispatchers/__tests__/lg.test.tsx
Composer/packages/client/src/recoilModel/dispatchers/lg.ts

Bug introduced in #4669, root caused is a long time LG parsing. when editing common.lg, all LG files in this bot will be parse again. when the bot has many lgFiles or some of them is large. The time of re-parsing them could be seconds. 
at this moment, if go to another page, composer is reading a middle state, which cause a mangled editing version in LG Editor.
Fix it by split re-parse all to another async thread.
close #4988

fix: LG Editor dropping changes

---

Composer/packages/client/src/recoilModel/dispatchers/__tests__/lg.test.tsx
Composer/packages/client/src/recoilModel/dispatchers/lg.ts

Bug introduced in #4669, root caused is a long time LG parsing. when editing common.lg, all LG files in this bot will be parse again. when the bot has many lgFiles or some of them is large. The time of re-parsing them could be seconds.
at this moment, if go to another page, composer is reading a middle state, which cause a mangled editing version in LG Editor.
Fix it by split re-parse all to another async thread.
refs #4997

chore: cherry pick #4997 to v1.2.2

---

Composer/packages/client/src/components/Modal/DisplayManifestModal.tsx
Composer/packages/client/src/pages/design/DesignPage.tsx
Composer/packages/client/src/recoilModel/atoms/appState.ts
Composer/packages/client/src/recoilModel/atoms/botState.ts
Composer/packages/client/src/recoilModel/dispatchers/__tests__/skill.test.ts
Composer/packages/client/src/recoilModel/dispatchers/skill.ts
Composer/packages/client/src/recoilModel/selectors/skills.ts
Composer/packages/client/src/shell/useShell.ts

Current `displaySkillManifestState` is a atomFamily `{ projectId: skillINameIdentify }`
but skill is shared cross current workspace, by projectId only increases difficulty to locate this state, for example, the shell api call from form editor only have `skillNameIdentify`, do not know this skill is on which projectId. 
By update it to a single atom `string` state, caller do not need pass `projectId`. 
#minor

fix: click show skill manifest no response in form editor

---

Composer/cypress/integration/NewDialog.spec.ts
Composer/cypress/integration/TriggerCreation.spec.ts
Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
Composer/packages/client/src/pages/design/DesignPage.tsx

With the new context menu giving operations for adding a dialog, trigger we do not need the toolbar item anymore.
close #4972

chore: remove Add toolbar dropdown button

---

Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
Composer/packages/client/src/utils/fileUtil.ts

Fix two bug on skill bot path in windows.
1. add duplicate path bot do not throw error.
2. load skill bot not found
the root cause is  path.resolve result will prefix with /
e.g 1
```
path.resolve('', 'C:/<path>') 
``` 
will get 
```
/C:/<path>
````
it suppose to get
```
C:/<path>
````
e.g 2
```
path.resolve('C:/<path>', 'a/b/c') 
``` 
will get 
```
/C:/<path>/a/b/c
````
it suppose to get
```
C:/<path>/a/b/c
````
#minor

fix: skill bot path bug

---

Composer/packages/client/src/components/EditableField.tsx

- For single line input, press Enter do submit
- For multiple line input, press Enter do submit, Shift+Enter get a new line,
close #4825

fix: a11y in all-up view

---

Composer/packages/server/src/models/storage/localDiskStorage.ts

When bot is exported to zip, recognizers, form-dialogs, scripts, bot project file and a README.md are missing.
closes #5019

fix: Export to zip is missing files and folders

---

Composer/packages/client/src/components/TextFieldWithCustomButton.tsx
Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
Composer/packages/client/src/pages/botProject/SkillBotExternalService.tsx
Composer/packages/client/src/recoilModel/dispatchers/__tests__/mocks/mockProjectResponse.json
Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts

Add luis name field on Settings page. During bot project initialization, if luis name is empty, it will initialize luis name with bot name and save it into settingsState.
Closes #5044

feat: Adds LUIS name to settings

---

Composer/packages/client/src/recoilModel/dispatchers/publisher.ts

This pr it to solve conflict.
#minor

fix: merge with main again

---

extensions/README.md

fix: Add missing header anchors

---

Composer/packages/client/src/components/Page.tsx
Composer/packages/client/src/pages/language-generation/LGPage.tsx

The Common links should only show up in the LG page; this wires a prop through so we can make that work.
#minor

fix: use Common links in LG page only

---

Composer/packages/electron-server/scripts/installOneAuth.js

Uses env variable to install a specific version of oneauth or falls back to 1.15.0
#minor

chore: allow setting oneauth version via env variable when installing

---

Composer/cypress/integration/LuisDeploy.spec.ts
Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
Composer/packages/client/src/components/Header.tsx
Composer/packages/client/src/components/__tests__/BotRuntimeController/BotController.test.tsx
Composer/packages/client/src/pages/design/DesignPage.tsx
Composer/packages/client/src/pages/setting/SettingsPage.tsx

**Add support for disabling stop all operations while bots are starting.**
@sangwoohaan 
**Changed copy to add an existing skill in context menu**
**Removed toolbar from application settings page**
#minor

feat: Disable stop all operations while start operations is being performed

---

Composer/packages/client/src/components/AppComponents/SideBar.tsx
Composer/packages/client/src/pages/setting/app-settings/AppSettings.tsx
Composer/packages/client/src/pages/setting/app-settings/SettingDropdown.tsx

This restores the SettingsDropdown to its updated design. This also widens the expanded sidebar by 25 pixels, leaving enough room for the labels.
#minor

fix: restore dropdown and widen sidebar

---

Composer/packages/server/scripts/build.js
Composer/packages/server/src/services/telemetry.ts

Adds missing `APPINSIGHTS_INSTRUMENTATIONKEY` to the `getBuildEnvironment` method.
#minor

fix: Add APPINSIGHTS_INSTRUMENTATIONKEY to getBuildEnvironment

---

Composer/packages/server/src/controllers/formDialog.ts

bf-generate-library searches templates directories for main.dialog in a certain order (requires standard to be first), but was finding it under "professional" templates first.
This PR only sends in "standard" for template directory to generation library since professional and swagger are not being used anyways to make sure library only searches standard templates.
closes #5146 
closes #5148 
closes #5139 
closes #5147

fix: Fixes electron-based form dialog generation 

---

Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx

This adds some logic to the ProjectTree so the LG page will show "Common" links again. It also only shows expandable-node triangles if a dialog has any LG/LU imports to avoid the "stack of meaningless triangles" effect.
closes #5131

fix: restore Common links to LG page

---

Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
Composer/packages/client/src/pages/design/DesignPage.tsx
Composer/yarn.lock

Allow manifest creating,editing on Root bot and skills. The view mode of the manifest is not required in the Project tree. It is only required inside the property editor pane of Connect to skill action
Fixes #5082 
@zhixzhan

fix: Allow manifest creation on root bot

---

Composer/packages/client/src/components/Modal/DisplayManifestModal.tsx
Composer/packages/client/src/recoilModel/dispatchers/project.ts
Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts

Fix two issue:
1. "Show skill manifest" has double scroll bar
2. fix QnA bot creation flow, broken in feature/botprojects check in
close #5167 
1. "Show skill manifest" has double scroll bar
2. fix QnA bot creation flow, broken in feature/botprojects check in

fix: "Show skill manifest" has double scroll bar

---

Composer/packages/client/src/recoilModel/Recognizers.tsx
Composer/packages/server/src/models/bot/botProject.ts
Composer/packages/server/src/models/bot/builder.ts
Composer/packages/ui-plugins/orchestrator/src/index.ts

**Why we can't choose Orchestrator type in the previous design**
When the dialog recognizer type is CrossTrainedRecognizerSet, the value of the recognize field in dialog is '{fileBasename}.{locale}.lu.qna'. So we don't know the the dialog recognizer type from the recognize field in the dialog directly. 
When we choose the Orchestrator type, we will update the {fileBasename}.{locale}.lu.dialog content. We will write the Orchestrator type to this file. Composer then will use the recognize field from the dialog and the type from it's recognizer file to determine if it is Orchestrator type.
But in the previous design, we will not create a recognizer file for empty lu file and in order to avoid users to choose the Orchestrator type when the lu file is empty, we add a warning here.
**fix** …

fix: Allow choose Orchestrator recognizer type when lu file is empty

---

Composer/packages/adaptive-form/src/components/FormTitle.tsx
Composer/packages/client/src/pages/design/VisualEditor.tsx

Changes:
1. 'Backspacing intent name to empty' won't reset Form title for now.
2. Fix the Flow nodes' title by updating memo deps.
Note that when backspacing form title to empty, Form's title is synced to empty as requested but Flow node's title keeps fallback to the title from sdk.schema to make sure the flow logic is readable.
closes #5123

fix: title problem

---

Composer/packages/client/src/Onboarding/Onboarding.tsx
Composer/packages/client/src/pages/botProject/DeleteBotButton.tsx
Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx
Composer/packages/client/src/pages/design/DesignPage.tsx
Composer/packages/client/src/pages/form-dialog/FormDialogPage.tsx
Composer/packages/client/src/pages/form-dialog/FormDialogSchemaList.tsx
Composer/packages/client/src/pages/form-dialog/FormDialogSchemaListHeader.tsx
Composer/packages/client/src/pages/form-dialog/VisualFormDialogSchemaEditor.tsx
Composer/packages/client/src/recoilModel/atoms/appState.ts
Composer/packages/client/src/recoilModel/dispatchers/formDialogs.ts
Composer/packages/client/src/shell/useShell.ts
Composer/packages/form-dialogs/package.json
Composer/packages/form-dialogs/src/components/FormDialogPropertiesEditor.tsx
Composer/packages/form-dialogs/src/components/property/PropertyListItem.tsx
Composer/packages/form-dialogs/src/components/tags/TagInput.tsx
Composer/packages/lib/shared/src/featureFlagUtils/index.ts
Composer/packages/lib/ui-shared/src/components/ConfirmDialog.tsx
Composer/packages/lib/ui-shared/src/components/index.ts
Composer/packages/server/package.json
Composer/yarn.lock
docs/preview features/form-dialogs.md

1. Adds notification to form dialog generation: progress, fail, success.
2. Adds help text to schemas, fixes minor search issue for schemas.
3. Adds back export for form dialog schema.
4. Replace native browser "confirm" with Composer confirm dialog (moved to ui-shared)
Note: using native browser confirm freezes electron UI on windows.
5. Fixes disable state for "clear all" and "generate dialog"
6. Fixes text for feature flags view and in the documentation.
closes #5153
closes #5143
closes #5141
closes #5138

fix: UX improvement to form dialogs and updated library

---

Composer/packages/adaptive-form/src/components/fields/StringField.tsx

Preserves selection state when using shift+left arrow.
fixes #5125

fix: preserve selection when selecting right to left

---

Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
Composer/packages/lib/indexers/src/botIndexer.ts

The bug is caused not set botProjectFileState for skill bot when do open local skill.
close #5211

fix: skill bot missing skill diagnostics

---

Composer/packages/client/src/pages/publish/Publish.tsx
Composer/packages/client/src/recoilModel/selectors/project.ts

- Add publishHistory recoil value
- UseMemo to involve publishType, publishHistory & settings
- Reduce `useEffect` use.
- Data flow is clearer.  
- Data change is unidirectional.
- Avoid data reset possiblity.
- publish multi-bot 
- bot is still publishing status when reload page, if bot is publishing status
- change publish target, publish history work well
- bot list displayed right when switching from other page
fix #5214

fix: data flow for publish page

---

Composer/packages/server/src/models/utilities/parser.ts
Composer/packages/server/src/services/telemetry.ts

Fixed an incorrect reference to the `env.json` file that contains the `APPINSIGHTS_INSTRUMENTATIONKEY`.
#minor

fix: Fixed reference to build environment variables

---

Composer/packages/server/src/services/featureFlags.ts

Feature flags won't load if there is a mismatch between default and current structure.
Closes #5229 
Closes #5102

fix: Fixed undefined deref on new property.

---

Composer/packages/client/src/components/BotRuntimeController/BotController.tsx

Prevent reopening the start bots panel when updating LG. This is to avoid the scenario to show the panel every time the selector updates and the botsStartedFlag gets set
#minor

fix: Show panel only if previous status is not restart all bots

---

Composer/packages/server/src/models/bot/builder.ts

**Root cause**
we have source qna file and dialog qna file today. The dialog qna file will import the the source qna file. When we do a qna publish, the loader will add source file content to the qna content of the dialog, then publish all these two files to the Qna maker.
**fix**
do a filter to prevent publish source file to the service.
closes #5104

fix: Qna pairs are being duplicated in the Qna knowledge base

---

Composer/packages/client/src/pages/botProject/PublishTargets.tsx
Composer/packages/client/src/pages/publish/BotStatusList.tsx
Composer/packages/client/src/pages/publish/Publish.tsx

UI fix about publish & setting page.  text truncate  instead of overflow & set column width wider
- publish page
- setting page
fix #5246

fix: ui fix about publish & setting page

---

Composer/packages/client/src/recoilModel/dispatchers/qna.ts

Fix force qna locale to be en-us, but unable to update source qna file, cause source qna file name do not include locale.
introduced in #5010 
#minor

fix: update source qna file not found

---

extensions/azurePublish/src/deploy.ts

Orchestrator has a dependency on `OnnxRuntime`, and this dependency bundles its debug symbols (~150MB) even in Release mode.  
This additional heft is not often used or needed in the published bot, if the user needs to debug locally these pdbs will still be there.  We remove the Orchestrator pdb file from publishing as well (`oc_abi.pdb`, ~8MB).  
Saves ~24MB zipped when uploading bot to Azure.
#minor

chore: Remove Orchestrator pdbs from Azure publish flow

---

Composer/packages/client/src/components/TextFieldWithCustomButton.tsx
Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
Composer/packages/client/src/pages/botProject/SkillBotExternalService.tsx

Recent update (add luis endpoint key) on settings cause some bugs. 
1.The luis authoring key and luis endpoint key share the same error.
2. If luis authoring key and luis endpoint key are both empty, inputting into luis endpoint key field. The error on luis authoring key is gone. But luis endpoint key should be an optional field and not a substitute to luis authoring key.
3. Region field error style is not the same as others
Closes #5274

fix: separate luis endpoint key from luis authoring key and update region's error style on Settings page

---

extensions/runtimes/src/index.ts

This PR is to fix two issues:
1. Azure Function does not work with --self-contain publish with RID. So in this PR, we only enable --self-contain and RID in azure web app.
2. We found a bug that the build targets are duplicated in the publishing process, this is because we set the publish target folder to bin/release/netcoreapp3.1, this is the default folder that all the built stuff be placed in, and we add a -o parameter for the dotnet publish which points to the same folder, this will actually generated two duplicated built targets. One is in bin\release\netcoreapp3.1\ and the other is in bin\release\netcoreapp3.1\win-x64, which doubled the build target. 
fixes #5267

fix: Azure functions deployment and code.zip size doubled issue

---

Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
Composer/packages/lib/shared/src/featureFlagUtils/index.ts

Replaced the 404 link (https://docs.microsoft.com/en-us/composer/setup-yarn)
To: https://aka.ms/install-composer
Fixed the double full stop issue in the Package manager texts.
fixes #5273

fix: help link

---

extensions/azurePublish/src/deploy.ts

This reverts commit 0f4820fb74a908fcf2bad66da4916669bc56643e.
Breaks publishing flow with an error: 
```
Error: An assembly specified in the application dependencies manifest (Microsoft.BotFramework.Composer.WebApp.deps.json) was not found: package: 'Microsoft.BotFramework.Orchestrator', version: '4.11.0-daily.20201023.178190' path: 'runtimes/win-x64/native/oc_abi.pdb'
```
More investigation needed. 
#minor

revert: Remove Orchestrator pdbs from Azure publish flow

---

extensions/localPublish/src/index.ts

This PR handles an unnecessary check that forces us to clear the hosted bots folder. Copy the bot again. Rebuild all the dependnacies every run.
@luhan2017 @VanyLaw can u help me evaluate if this change is OK. I have tried ejecting C# runtime and non ejected scenarios all of them seem to work fine. It seems to have been introduced here https://github.com/microsoft/BotFramework-Composer/pull/3198/files#diff-8bc80526cd9185a7138ca77498899908f213e41c98bfc7852a05a9e3c4fca37cR247
Fixes #5191

fix: Start bots optimization

---

Composer/packages/client/src/recoilModel/dispatchers/project.ts

Fetches the mergedSettings from settings state on reload. This would avoid the LUIS key error.
Fixes #5285

fix: Fetch merged settings on reload

---

Composer/packages/client/src/recoilModel/dispatchers/project.ts
Composer/packages/server/src/services/telemetry.ts

Moved `set(botOpeningState, false);` to the `finally` block in the `try/catch` so the loading screen will always be dismissed.
#minor

fix: dismiss open bot loading screen

---

Composer/packages/client/src/pages/design/createDialogModal.tsx

PVA bot's root dialog has different name with bot name, when create a botName dialog, current check will pass because there is no duplicate dialog name. that mess up PVA bot structure.
The solution add a check prevent root dialog (bot name dialog). that both work for normal composer bot and PVA bot.
close #5304

fix: prevent create root dialog (PVA scenario)

---

Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx
Composer/packages/client/src/pages/botProject/runtime-settings/style.ts

fix: update script button overlaps with publish target content in setting page

---

extensions/azurePublish/src/luisAndQnA.ts
runtime/dotnet/NuGet.Config
runtime/dotnet/azurewebapp/Startup.cs

This PR include 3 fixes:
1. This is a fix to backward compatible issue with 1.0 created bot, which don't have cosmosdb config but our latest runtime code assume there is always one cosmosdb section and throw exception if there isn't. Fixing by loosing the constraints here.
2. remove the myget package source in Nuget.config
3. use logger instead of this.logger to fix the exception when publishing multiple lu files which triggers the retry logic. 
#minor

fix: runtime throw exception when there is no cosmosdb config

---

Composer/packages/client/src/recoilModel/dispatchers/publisher.ts

Prevent capturing dotnet build error from runtime wrongly as missing .NET on the machine.
#minor

fix: surface dotnet build error on runtime

---

Composer/packages/client/src/recoilModel/parsers/workers/lgParser.worker.ts
Composer/packages/lib/shared/src/resolverFactory.ts

For performance consideration, LG file parseResults are cached in client. the next time do CRUD, will directly use previous parseResult do increment parse. 
1. initially we have two file (`common.lg`, `a.lg`) and it's parsed resource ( `CommonParseResource:T0`, `AParseResource:T0` )
2. when modify common.lg file, will update common.lg to `CommonParseResource:T1`.
3. when modify a.lg (referred common.lg), a.lg will use  `AParseResource:T0 ` update itself. but in `AParseResource `, it referred
common.lg is expired `CommonParseResource:T0`.  which cause mismatch error.
At step2, not only update itself, but also update all rest lg files 's  resource reference.
#minor

fix: LG diagnostics mismatch by update reference in cache 

---

Composer/packages/client/src/pages/design/DesignPage.tsx
Composer/packages/client/src/pages/design/PropertyEditor.tsx
Composer/packages/client/src/recoilModel/dispatchers/navigation.ts
Composer/packages/client/src/recoilModel/dispatchers/trigger.ts
Composer/packages/client/src/recoilModel/undo/__test__/history.test.tsx
Composer/packages/client/src/recoilModel/undo/history.ts

we didn't commit the changes of creating trigger event in the context menu to undo history
1. Add commit change for creating and deleting trigger event.
2. Add await to make sure all data can be pushed to the undo history.
3. Use the navigation function from dispatcher to avoid the leakage of the navigate logic.
closes #5324

fix: undo failed after click create trigger and remove trigger

---

Composer/packages/client/src/plugins/api.ts
Composer/packages/extension-client/src/publish/index.ts
extensions/pvaPublish/src/ui/pvaDialog.tsx
extensions/pvaPublish/src/ui/styles.ts
extensions/sample-ui-plugin/src/client/publish/main.tsx
extensions/sample-ui-plugin/src/client/styles.ts

Upon merging the provisioning work, there were some changes made to the publishing extension API that were not translated into all the publishing extensions, breaking some of them.
This PR rewrites the `pvaPublish` and `sample-ui-plugin` extensions to use those updated APIs.
Gets rid of the `setPublishConfig()` and `setConfigIsValid()` APIs.
#minor
**`pvaPublish`**
**`sample-ui-plugin`**

fix: Updated publish extensions to use updated APIs

---

Composer/packages/client/src/recoilModel/atoms/botState.ts
Composer/packages/client/src/recoilModel/dispatchers/lg.ts
Composer/packages/client/src/recoilModel/dispatchers/lu.ts
Composer/packages/client/src/recoilModel/dispatchers/multilang.ts
Composer/packages/client/src/recoilModel/dispatchers/qna.ts

As describe in #5339. In current dispatchers methods, some of them, state manipulations are not concurrency safe.
If a concurrency call incoming also mutate same state variable, last time long time parsing will overwrite the concurrency mutation.
This PR reviewed those code again, change to use updater callback function make fine-gained operations.
close #5339

chore: Concurrency safe state manipulation for lg/lu/qna/multilang

---

Composer/packages/client/package.json
Composer/packages/client/src/recoilModel/dispatchers/provision.ts
Composer/packages/server/src/controllers/provision.ts
Composer/packages/server/src/locales/en-US.json

Someone's arm token was too large, and we pass both arm token and graph token in provision call header, so that the http call will throw `431 header fields are too large` error.
Reason: The HTTP protocol parser that Node uses appears to be hard-coded with a maximum header size.
Solution: 
1. set --max-http-header-size in client package.json.      **But it have no effect.**
2. move graph token from header into body.                   **I take this one in this fix.**
3. change a http parse, like used `http-parser-js` instead.
close #5335

fix: move graphToken into body, fix http call header too large

---

Composer/cypress/integration/LuisDeploy.spec.ts

Current: after clicking start bots button, the "start bots panel" will open automatically if it is failed to start bots. 
In our e2e test case, there is one more clicking on the panel which will actually close it, so the See Details text cannot be seen.
Fix: delete the clicking on the "start bots panel" operation.
#minor

fix: luis deploy e2e test case failed due to unnecessary clicking on the start bots panel.

---

Composer/packages/server/package.json
Composer/packages/server/src/controllers/__tests__/auth.test.ts
Composer/packages/server/src/controllers/asset.ts
Composer/packages/server/src/externalContentProvider/externalContentProvider.ts
Composer/packages/server/src/models/bot/botProject.ts
Composer/packages/server/src/models/bot/builder.ts
Composer/packages/server/src/models/bot/interface.ts
Composer/packages/server/src/models/settings/defaultSettingManager.ts
Composer/packages/server/src/models/settings/fileSettingManager.ts
Composer/packages/server/src/services/project.ts
Composer/packages/server/src/settings/env.ts
Composer/packages/server/src/store/migrations.ts
Composer/packages/server/src/utility/attachLSP.ts
Composer/packages/server/src/utility/isSubdirectory.ts
Composer/packages/tools/language-servers/language-understanding/__tests__/helpers/server.ts
Composer/packages/types/src/indexers.ts

This is a fix that cleans up a lot of the server code, adding type annotations where appropriate and smoothing out a few bumps. A lot of these "any" types are there for a good reason (they're either for test mocks or for data we're importing from a file), but there are some places that could be improved.
#minor

fix: improve type-safety of server code

---

docker-compose.yml

The build context in the `docker-compose.yml` file is currently incorrect. This PR is fixing that.
Closes #5381

fix: Docker Compose build context

---

Composer/packages/client/src/components/Header.tsx

active language callout on header should be closed once losing focus
Closes #5293

fix: active language callout on header should be closed once losing focus

---

Composer/packages/server/src/controllers/publisher.ts

PR #4924 updated the publish history API to `getHistory()` but did not update the conditional check above it to also check for the updated method name. This was causing the history call to fail for PVA publish profiles, and was not allowing users to select their PVA publishing profile from the dropdown.
Fixes #5398

fix: Updated condition to check for correct publish API

---

extensions/githubAuth/package.json

fix: GitHub auth plugin's name

---

Composer/packages/client/src/recoilModel/parsers/workers/lgParser.worker.ts
Composer/packages/lib/indexers/src/utils/lgUtil.ts

Inside LG worker, we maintained a cache which holds the parsed lg index, to avoid a full parse every time. We also designed a cache expiring mechanism that once we found the current state of lg file is not equaling the cached lg file, we consider lg file is changed outside, and thus the cache is invalid, we will do a full parse and resyncing with the master state. 
But we found that this caching is expiring more often than we think, and causing more full parsing than the expected incremental parsing.
Cache is expiring too fast and too often is because our store is updating slower than the caching itself. When user is typing fast, the store must be updated after the parsed result is obtained, because today, our raw lg content is tightened up with the parsed lg result and be updated …

fix: LG worker cache expires occasionally

---

.github/workflows/validate-pr.yml

#5505 added `opened` and `edited` to the pr validation triggers, however the check was being cleared when new commits were pushed and never re-running. The `synchronize` event should re-trigger in that case as well.
#minor

ci: re-trigger pr validation on push

---

Composer/packages/client/config/env.js
Composer/packages/electron-server/package.json
Composer/packages/server/src/constants.ts

Bump version from 1.3.0 to 1.3.1
#minor

fix: bump version to 1.3.1

---

Composer/packages/client/src/App.tsx
Composer/packages/client/src/pages/design/DesignPage.tsx
Composer/packages/client/src/pages/design/VisualEditorHeader.tsx
Composer/packages/client/src/recoilModel/dispatchers/__tests__/navigation.test.tsx
Composer/packages/client/src/recoilModel/dispatchers/navigation.ts

Switching in project tree is causing too much re-rendering (including some full re-rendering), up to 8 times in a simple switch. This fix some simple refactoring that saves us at least 4 full rendering times, leaves us to 3-4 partial rendering. Will continue investigate the other unnecessary rendering.   
The goal eventually is to have only one rendering in one switch. 
1. We always set local state in useEffect when location change.
2. We are setting < breadcrumb /> when switching the item, but the state only used by breadcrumb component and put it in the < DesignPage />  will make the page full re-render.
3. The < App /> will listen to the url to initialize the logger, the location change will make the whole app re-render
1. add value check, if no change, do nothing
2. move the < …

fix: switching in project tree is lagging

---

Composer/packages/client/src/pages/design/DesignPage.tsx

When delete trigger from ProjectTree, update dialog should take projectId passed from projectTree, instead of current page skillId.
Fixes #minor

fix: delete trigger broken in ProjectTree

---

Composer/packages/client/src/recoilModel/selectors/diagnosticsPageSelector.ts
Composer/packages/client/src/recoilModel/selectors/project.ts
Composer/packages/lib/indexers/src/botIndexer.ts

When root bot has a luis/qna key, the skill bot still shows needing a luis/qna key. The error shows in design page Project Tree.
fix: need to check whether the root bot has a key before generating this key missing error.
#minor

fix: luis/qna key shows missing while root bot has one

---

Composer/packages/client/src/components/ProjectTree/ProjectHeader.tsx

A url bug was introduced in recent Pr. When a skill bot is missing a luis/qna key, we can click on the error and navigate to settings page in Design page project tree. But the navigation url is incorrect. It passed current project id which should be root bot project Id.
#minor

fix: design page navigating to settings Page url error

---

Composer/package.json

Some zsh configurations will expand glob patterns resulting in `format-message` only executing on the first argument.
#minor

fix: correctly generate l10n files when using zsh

---

Composer/packages/server/package.json
Composer/yarn.lock
runtime/dotnet/azurefunctions/Microsoft.BotFramework.Composer.Functions.csproj
runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
runtime/dotnet/core/Microsoft.BotFramework.Composer.Core.csproj
runtime/dotnet/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj

During R12 development on the main branch, we should pick up the daily builds of the runtime.  This will help us discover issues earlier.
This also updates to the latest bf-generate library as it uses the latest runtime.
#minor
N/A

chore: Updating to daily runtime for R12 development

---

Composer/packages/server/package.json

fix 431 header too large error when publishing by setting max http header size in server.
close #5467 
Use user's token to test, won't return 431.

fix: 431 error when publish

---

extensions/localPublish/src/index.ts

some error doesn't serializate.
close #5390

fix: showing correct error message in local publish

---

Composer/packages/client/src/components/AppUpdater.tsx
Composer/packages/electron-server/src/appUpdater.ts
Composer/packages/electron-server/src/main.ts

We have a data race when user click "check for updates" with auto-update set to true, causing the updating fail (#5549).
This PR let manual-update can continue auto-update progress.
1. if auto update is downloading, when click "check for updates" will show the progress.
2. if auto update is downloaded, when click "check for updates" will show quit-and-start modal.
close #5551 
1. When auto update is downloading.
2. When auto update is downloaded.

fix: electron update error

---

Composer/packages/tools/built-in-functions/src/builtInFunctionsMap.ts
Composer/packages/tools/language-servers/language-generation/src/LGServer.ts

Fixes #5332 
Currently, LG editor displayed incorrect ReturnType when user hover on pre-built functions.
In this PR, the value of ReturnType will be mapped to its explicit content.

fix: hover on pre-built functions displays incorrect ReturnType content

---

extensions/samples/assets/projects/AskingQuestionsSample/dialogs/numberinput/numberinput.dialog

When playing around examples, I found this small bug.
fixes #minor

fix: Update numberinput.dialog

---

Composer/packages/extension-client/src/hooks/useTriggerConfig.ts

#minor
In #4079, the TriggerCreationModal becomes completely schema-driven, a small piece of PVA-only code was removed.
It will cause an issue, in PVA env, two triggers be visible to users but not available in PVA env:
- `Microsoft.OnQnAMatch` aka 'QnA Intent recognized'
- `Microsoft.OnChooseIntent` aka 'Duplicated intents recognized'
This PR forces these two triggers to be hidden when the env is detected as the PVA env.
**Notes**:
I was considering that updating the `app.uischema` on PVA side, however, it only affects newly created skills but won't work for existing skills.
On the other hand, an update on PVA's app.uischema is still required, will follow up with @tonyanziano.

chore: Hide triggers 'OnQnAMatch' and 'OnChooseIntent' in PVA env

---

Composer/packages/client/src/components/Header.tsx

should allow to click outside focuszone
Closes #5597

fix: should allow to click outside focuszone

---

Composer/packages/client/src/pages/language-generation/code-editor.tsx
Composer/packages/lib/code-editor/src/lg/LgCodeEditor.tsx

Fixes the height of LG editor under LG all up page.
Adds available templates to the template button in the toolbar in LG page.
#minor

fix: LG all up code editor height and templates

---

Composer/packages/server/src/models/bot/__tests__/botProject.test.ts
Composer/packages/server/src/models/bot/builder.ts

The outside service may be not stable, when we call it in unit tests, it may cause time out or access deny error.
**In this PR**
mock the luBuild and qnaBuild functions to avoid call outside service
closes #5646

fix: botProject UT depends on external service

---

Composer/packages/lib/indexers/package.json
Composer/packages/server/package.json
Composer/packages/server/src/models/bot/builder.ts
Composer/packages/tools/language-servers/language-understanding/package.json
Composer/yarn.lock

Update bf/lu package. 
Set directVersionPublish to true when call luis publish API. 
fixes #5622

fix: use directVersionPublish for LUIS to avoid 404 in bot response

---

Composer/packages/client/src/recoilModel/dispatchers/project.ts
Composer/packages/server/src/services/project.ts

refine the message to "path" doesn't seems to be exists anymore.
closes #3671

fix: refine the error message when the bot is deleted

---

Composer/packages/client/src/recoilModel/dispatchers/builder.ts
Composer/packages/client/src/utils/qnaUtil.ts

Only publish the referred qna file when do files build in the PR.
closes #4884

fix: Only publish the dialog referred qna file

---

Composer/packages/electron-server/scripts/sign-mac.js

Do not interpolate env variables when executing bash scripts. This had unintended consequences when values contained un-escaped characters. It is also safer to do so by not leaking secrets in the bash history.
#minor

fix: consume some env variables from bash instead of JS

---

.github/workflows/docker.yml

fix: docker build failed

---

Composer/packages/adaptive-flow/src/adaptive-flow-editor/renderers/NodeWrapper.tsx

Fix css err when clicking node in visual editor.
- Before
css err when clicking node in visual editor
- After
Add 
```
&:focus {
outline: 0;
}
```
for clicked div to remove outline
close #5712

fix: css err when clicking node in visual editor

---

Composer/package.json
Composer/packages/adaptive-flow/package.json
Composer/packages/lib/indexers/package.json
Composer/packages/lib/indexers/src/utils/lgUtil.ts
Composer/packages/tools/language-servers/language-generation/package.json
Composer/packages/types/src/indexers.ts
Composer/yarn.lock

Add structure LG parsed result to lg template.
For example:
`# template
[Activity
Text=good
Speak=hi
]`
The parsed Template would contains a property named properties, in which would contains:
`properties: {Text: "good", Speak:"hi", $type:'Activity'}`
#minor
refs https://github.com/microsoft/botbuilder-js/issues/3273

fix: Include structured response parse data in lg template

---

Composer/packages/server/src/services/telemetry.ts

Adds a truncated user id to the Application Insights envelope. 
#minor

feat: Add truncated user id to telemetry events

---

Composer/packages/client/src/pages/design/SideBar.tsx
Composer/packages/client/src/recoilModel/dispatchers/project.ts
Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
Composer/packages/server/src/locales/en-US.json
Composer/packages/server/src/models/asset/__tests__/assetManager.test.ts
Composer/packages/server/src/models/asset/assetManager.ts
Composer/packages/server/src/models/bot/botProject.ts
Composer/packages/server/src/services/project.ts
Composer/packages/server/src/utility/project.ts

This change allows any number of bots to be created by a template, enabling multi-skill scenarios. 
Previously our code assumed there would be one bot project resulting from the file -> new action. 
This change detects whether the result of the create is a single project or multiple projects. It then processes any projects found, resulting in N-number of fully instantiated projects available to open in Composer.
It then returns the root bot to the client so that it can open it and all child bots.
#minor
https://www.loom.com/share/e6c545242a9e4f409eb54d28cb7cc2f2

feat: support multibot templates during in new creation flow

---

Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx

The project settings page was leaving stale values visible when switching between a root bot or any of its skills in the left-hand-side list. This fixes that by reloading the values from the settings when the visible projectId changes.
closes #5785 
These are a before and after comparison of clicking the "EchoBot-5" label:

fix: reset settings fields when a new projectId loads

---

Composer/yarn.lock

**issue**
**fix**
update the version of url-parse to 1.5.1
#minor

fix: security alerts from url-parse

---

Composer/packages/client/src/constants.ts

This adds the `scope: microsoft` parameter to the feed that is used as the source of templates in the new creation flow.

fix: Restrict template feed to those published by Microsoft

---

Composer/packages/client/src/recoilModel/selectors/extensions.ts
Composer/packages/lib/shared/src/featureFlagUtils/index.ts
Composer/packages/types/src/featureFlags.ts

Make the new creation flow feature flag visible on the application settings page.  This gates access to the new flow, package manager, and the new connection management area of the bot settings.
fixes #5757

fix: make new creation flow feature flag visible, combine package manager feature

---

Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
Composer/packages/client/src/components/WebChat/utils/conversationService.ts
Composer/packages/server/src/directline/middleware/__tests__/conversationHandler.test.ts
Composer/packages/server/src/directline/middleware/conversationHandler.ts
Composer/packages/server/src/directline/store/entities/botEndpoint.ts
Composer/packages/server/src/directline/store/entities/conversation.ts

This PR fixes a bug in which secrets are not passed to update conversation handler that happens during restart conversation.
Fixes #minor

fix: Pass updated MSAppID and MsPass on restart

---

Composer/packages/server/package.json
Composer/yarn.lock

Fixes #5975
Underlying issue was caused by cached templates not being returned because of a missing break.  They are missed only on production composer because of the order of directories passed in. Fix is to update to the latest version of bf-generate-library to pick up the fix.

fix: Update to latest generator to fix #5975

---

Composer/packages/client/src/pages/design/DebugPanel/DebugPanel.tsx
Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsTabHeader.tsx
Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogItemHeader.tsx
Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/index.ts
Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/types.ts
Composer/packages/client/src/pages/design/DebugPanel/styles.ts
Composer/packages/client/src/recoilModel/atoms/appState.ts

This PR adds a red indicator to the webchat inspector if its not the current tab and new errors have happened. It also removes the unread indicator from the Problems tab.
refs #5918

feat: Support unread notification marker on Webchat inspector

---

Composer/packages/client/src/recoilModel/dispatchers/project.ts

When we install a package, the settings only get updated on server side(cache and hard disk). On client side, the settingState (cache state) does not have the property like "plugins". So we should continue to use settings got from server side and merge sensitive property on client side localStorage.
Closes #5935
data got from server:
after merge sensitive property, we have the authoring key

fix: reload project method does not load settings correctly

---

Composer/packages/client/src/recoilModel/dispatchers/navigation.ts

**Root cause**
when we click the action in the VisualEditor, client will call focusTo to update the designPageLocationState. But the focusTo always update the root bot state. So if we click the skill bot action then navigate to the root bot, the dialog name is from the skill bot and the currentDialog will be undefined.
**Fix**
use the correct projectID to update the designPageLocationState
closes #5978

fix: Diagnostics location navigation issue

---

extensions/packageManager/src/components/FeedModal.tsx
extensions/packageManager/src/components/WorkingModal.tsx
extensions/packageManager/src/pages/Library.tsx

1) improve performance and reduce calls to the "get installed" api, which was causing the UI to flicker and be slow.  
2) ask user to double confirm close of edit feeds modal if they are mid-edit
3) update the text and handling of the installing/uninstalling progress indicator
fixes #5933 
fixes #5934 
fixes #5943

fix: small bug fixes in the ui for package manager

---

Composer/package.json
Composer/packages/client/__tests__/pages/botProjectsSettings/AdapterSettings.test.tsx
Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx
Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterSettings.tsx

This pulls the name of the adapter from the schema and the link to its docs from its uiSchema, combining the two to make a link that will lead users to whatever the adapter sets its help link to.
closes #5907 
(values blocked out just so we're not exposing them; the real box of course has the actual values)

feature: put link to documentation in modal

---

Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx

Reverts the height issue in our advanced settings editor.
https://github.com/microsoft/BotFramework-Composer/pull/5928/files#diff-971523261f66177d194b51799eeb7a8a710720c76d00e757eb801016a4a3dd8cL41
#minor

fix: Make sure advanced settings editor is to 100% height

---

Composer/packages/server/src/controllers/eject.ts
Composer/packages/server/src/locales/en-US.json
Composer/packages/server/src/utility/project.ts
Composer/packages/types/src/runtime.ts
extensions/runtimes/src/index.ts

This PR removes the new runtime from the eject list, removing the duplicated "C#" option.
behind the scenes, this is done by filtering on the existence of the rutnime's eject method, which has been (appropriately) removed from the new v2 runtime.
Fixes #5979

fix: exclude new runtime from ejection list

---

Composer/packages/client/src/pages/language-generation/LGPage.tsx
Composer/packages/client/src/router.tsx

**Root cause**
1. The Router catches the url common/*, and doesn't get the correct dialog id. 
2. the baseUrl doesn't been added to the useEffect dependencies, so the show code button will use stale base url and navigate to the wrong page.
**fix**
1. remote the common/* router, then the url will be cached by the dialogId/*
2. add base Url to the useEffect dependencies
closes #6029

fix: Bot Response page show wrong content for common lg file

---

Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
Composer/packages/client/src/utils/publishStatusPollingUpdater.ts

provision process shown in publish list
The process poor is shared by provision & publish. So the provision process will be shown in publish page when get publish status without jobId
Store jobId in client and add job id in get publish status api
#minors

fix: provision process shown in publish list

---

Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx
Composer/packages/client/src/recoilModel/dispatchers/project.ts

The bug should already exist for months, but does not show up until recent change on file persistence layer.
Reason: 1. after deleting bots, the file persistence layer does another comparison and resends requests to delete files that are already deleted. 
2. During deleting bots,it does another call to getBoilerplateVersion because of settings changed which is unnecessary.
Fix: 1. clear filePersistence state after deleting bots files.
2. split useEffect in RuntimeSetting to avoid interfere each other.
Closes #6042 
error request: 
after fix:

fix: delete bot bug

---

Composer/packages/client/src/pages/botProject/adapters/ABSChannels.tsx
Composer/packages/client/src/pages/botProject/styles.ts
Composer/packages/server/src/locales/en-US.json

The column widths on the settings page didn't line up with each other; this fixes that.
#minor

fix: make column widths consistent

---

Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx

The adapter settings modal wasn't reading the values for defaults from the schema; it was just initializing the values as empty if there was no existing value object to load.
closes #5906

fix: read default values from schema when building modal

---

Composer/packages/client/src/pages/publish/Publish.tsx

publish  is successful however a failure is being reported in the notifications pane
The updatedBot status which is used to choose the notification type is not the newest.
Merge the newest status for updatedBot
closes #5899

fix: publish is successful however a failure is being reported in the notifications pane

---

Composer/packages/client/src/pages/botProject/adapters/AdapterSection.tsx

Fixed the Adapter section of the settings to have a unique scrollToId, confirmed that the get started button scrolls to this section.
fixes #6116

fix: give adapter section a unique scrollToId

---

Composer/packages/server/src/locales/de.json
Composer/packages/server/src/locales/es.json
Composer/packages/server/src/locales/fr.json
Composer/packages/server/src/locales/it.json
Composer/packages/server/src/locales/ko.json
Composer/packages/server/src/locales/tr.json
Composer/packages/server/src/locales/zh-Hans.json
Composer/scripts/l10nCheck.js

Some of the l10n files ended up with curly braces without the single-quotes around them; this was causing the app to crash in those locales (German, Spanish, French, and Simplified Chinese).
closes #5496

fix: repair unquoted braces in l10n files

---

Composer/package.json
Composer/scripts/l10nCheck.js

We need our CI to be aware of possible problems in L10n files, so this adds a new yarn command to our package.json which runs the l10n:check script and then build:dev, intended to replace the existing build:dev step in our CI flow. This also fixes a small bug in the script that was causing it not to notice some issues.
#minor

fix: add new build:ci and fix l10ncheck bug

---

Composer/packages/client/src/recoilModel/dispatchers/builder.ts

since this already exists as a warning in the warnings pane, remove the additional pop up warnings directly.
closes #6138

fix: remove the notification pop up for luis language warning when click start bot

---

Composer/package.json

We noticed the pre-commit hook was not being run anymore on windows since #6090. It's unclear why that was happening.
Adding a specific glob for extension files works properly.
closes #6316

chore: fix formatting code pre-commit on windows

---

Composer/packages/tools/built-in-functions/src/builtInFunctionsMap.ts

<details>
<summary>Details</summary>
</details>
Currently the description for `toLower` and `toUpper` is reversed. I have tested the functionality and this is correct, just the description is incorrect.
#minor

fix: Fixes description for toLower and toUpper built-in functions

---

Composer/packages/electron-server/src/appMenu.ts

Adds a "Copy" button to Composer's "About" dialog that allows the user to copy the version information to the clipboard.
Also justified the about information to the left of the dialog.
Fixes #6203
**BEFORE**
**AFTER**

feature: Added ability to copy Composer's "About" info

---

Composer/packages/electron-server/src/auth/oneAuthService.ts

If we already have tenantId, client will call get arm token api directly, we need to initialized oneauth before the api call.
close #6351

fix: fix one auth not initialize

---

Composer/packages/server/src/models/bot/__tests__/orchestratorBuilder.test.ts
Composer/packages/server/src/models/bot/builder.ts
Composer/packages/server/src/models/bot/process/orchestratorBuilder.ts
Composer/packages/server/src/models/bot/process/orchestratorWorker.ts
Composer/packages/server/src/models/bot/process/types.ts

**issue**
composer will do orchestrator build every time. some big bot may take 15min. It is a long time to wait even the lu files don't update.
**fix**
Add the cache of LabelResolvers for orchestrator build. the build worker will re-use the resolvers and reduce the re-training time.
In my local test, the first time will use 15min and the second only use 800ms.
#minor

fix: add cache for orchestrator build to reduce the re-build time

---

Composer/packages/client/package.json
Composer/yarn.lock

#minor
[INFO] |CVE-2021-24033                          |react-dev-utils 7.0.5                   |High

chore: Bumps react-dev-utils to 11.0.4

---

Composer/packages/client/src/recoilModel/dispatchers/orchestrator.ts
Composer/packages/server/src/controllers/orchestrator.ts

The download model notification pops whenever we use Orchestrator, even when not necessary.  This is a minor fix to not show the notification unless the model download is actually started.
#minor

fix: Orchestrator don't show notification if model already exists

---

Composer/packages/lib/indexers/src/botIndexer.ts

User receives LUIS "locale not supported" warnings even if their bot is using Orchestrator everywhere instead of LUIS.  We make the LUIS recognizer check explicit to prevent this warning when using Orchestrator.
#minor

fix: Should not show LUIS locale warnings if bot is exclusively using Orchestrator 

---

Composer/packages/client/package.json
Composer/packages/client/src/pages/design/VisualPanelHeader.tsx

The breadcrumb array needs to get action names, and we have a function that pulls them from the UI schema as needed. However, this function wasn't getting the schema passed into it in some cases.
closes #6374

fix: read plugin config for action names in breadcrumb array

---

Composer/packages/lib/shared/src/constant.ts
Composer/packages/server/src/controllers/asset.ts
Composer/packages/server/src/models/asset/assetManager.ts

QNA template instantiates empty bot template under the hood and when we changed the empty bot generator name to the @microosft/ name we did not update the naming in Composer. This PR updates that logic and moves that template named to a shared constant
fixes #6383

fix: qna template to create right empty bot generator

---

Composer/packages/lib/code-editor/src/lg/modalityEditors/StringArrayEditor.tsx
Composer/packages/lib/code-editor/src/lg/modalityEditors/StringArrayItem.tsx

Fixed issue inserting functions in LG
Closes #6379

fix: Fixed issue inserting functions in LG

---

Composer/packages/adaptive-form/src/components/FormTitle.tsx
Composer/packages/client/src/pages/design/VisualPanelHeader.tsx
Composer/packages/client/src/recoilModel/dispatchers/dialogs.ts
Composer/packages/lib/indexers/src/dialogIndexer.ts
Composer/packages/lib/shared/src/dialogFactory.ts

**Root cause**
The form editor and breadscrum only use the $designer.name to show the label. The project Tree will use $designer.name and dialog.id to show the item label. So when the name is undefined, the display name will be different.
**fix**
label =  $designer.name ?? dialog.id
closes #6387
closes #6375

fix: the dialog name does not update in the navigation pane when changed in the properties panel

---

Composer/packages/client/package.json
Composer/packages/client/scripts/start.js
Composer/yarn.lock

Rollback react-dev-utils version to 9.1.0 until we get a resolution on 
https://github.com/facebook/create-react-app/issues/9804
Fixes #6389

fix: react-dev-utils version

---

Composer/packages/client/src/pages/design/VisualEditor.tsx

Adds a gray Composer icon to the flow editor when a selected dialog has no triggers
Fixes #6377 
**BEFORE:**
**AFTER:**

fix: Added gray Composer icon to 'no triggers' dialog state

---

Composer/packages/client/src/pages/publish/Publish.tsx

There was code in Composer's source that was fetching an ARM token on all publish requests regardless of the publish type, when this should only have been done when publishing to Azure web apps / functions.
This was causing an unnecessary login prompt when trying to publish to PVA after importing.
This is a temporary fix until the code is moved into the Azure publish extensions where it belongs.
Fixes #6377

fix: Get an ARM token only when publishing to Azure

---

Composer/packages/client/src/components/CreationFlow/v2/CreateOptions.tsx
Composer/packages/client/src/pages/design/creationModal.tsx
Composer/packages/client/src/recoilModel/dispatchers/project.ts
Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
Composer/packages/client/src/recoilModel/selectors/project.ts
Composer/packages/server/src/controllers/project.ts
Composer/yarn.lock

This fixes the "add new skill" flow when the new creation flow is enabled.
Changes include:
* Detect skill flow and redirect appropriately depending on current value of new_creation feature flag
* Do post-creation steps for added skill
fixes #6427

fix: use new create flow during add skill if enabled

---

Composer/packages/client/src/recoilModel/dispatchers/storage.ts
Composer/packages/server/src/services/featureFlags.ts

Fixes an issue where the server would return a 500 after default flags have been removed or renamed but the data.json had not been updated. Also adds an in app error if this happens in the future (only in dev).
closes #6426

fix: load feature flags if default keys have changed

---

Composer/packages/client/src/components/ProjectTree/ExpandableNode.tsx
Composer/packages/client/src/components/ProjectTree/treeItem.tsx

This simplifies the CSS a little and adds some new styling to get us our summary expand/collapse triangles back.
closes #6181

fix: make CSS show triangles in project tree

---

Composer/packages/server/package.json
Composer/yarn.lock

Taking a change from bf-cli to fix an Orchestrator incremental training issue. Smoke-tested and problem no longer exists.
closes #6429

fix: Orchestrator labels get corrupted with entity data upon successive training

---

Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts

Previously projectId state change in the new create flow happened before opening root bot and skills which resulted in undo state for the projectID to not be configured accordingly and ultimately caused the history object to not instantiate for the created botProj (resulted in error modal with message: history.clear is not a function).
This small change saves projectID after running openRootBotAndSkills which ensures the history obj for the created bot proj is configured correctly and does not result in the aforementioned error
#minor

fix: Fixing projectId state save for new creation flow

---

Composer/packages/client/src/shell/actionApi.ts
Composer/packages/client/src/shell/utils.ts

Adds cut/copy/paste for nested Lg template with structured responses.
closes #6447
https://user-images.githubusercontent.com/1483492/111669627-39f36100-87d4-11eb-8236-d5e8bba6ba4e.mp4

fix: Fixes cut/copy/paste for nested Lg template with structured responses

---

Composer/packages/server/package.json
Composer/yarn.lock

Fixes permissions on `libicudata.68.dylib` and `libicuuc.68.dylib` in `orchestrator-core` for Mac.  This should allow the Composer updater to delete the old version of Composer without complaining about write-errors
#minor

fix: Update bf-orchestrator to 4.12.0-beta.20210322.314475a

---

Composer/packages/lib/shared/src/skillsUtils/index.ts
Composer/packages/server/src/models/bot/botProject.ts
extensions/azurePublish/src/node/index.ts
extensions/azurePublish/src/node/luisAndQnA.ts

The isUsingAdaptiveRuntime code is repeated in several places across the code.  
It has too narrow a check for adaptive runtime types.
This moves the check to @bfc/shared and widens the check on the runtime setting.
#minor
N/A

chore: Shared check for using adaptive runtime

---

Composer/packages/adaptive-form/src/components/fields/IntentField.tsx
Composer/packages/client/src/components/TriggerCreationModal/TriggerCreationModal.tsx
Composer/packages/client/src/components/TriggerCreationModal/resolveTriggerWidget.tsx
Composer/packages/client/src/pages/publish/Publish.tsx
Composer/packages/extension-client/src/hooks/useRecognizerConfig.ts
Composer/packages/lib/code-editor/src/lu/LuLabelingMenu.tsx
Composer/packages/server/src/locales/en-US.json

- Adds insert/tag menu to create trigger modal when default recognizer is luis
- Updates tooltip and help link for trigger phrases label when default recognizer is luis
- Prevents floating labeling menu where there are no Luis ML entities
#minor

fix: Lu editing improvement fixes

---

Composer/packages/adaptive-form/src/utils/resolveFieldWidget.ts

When the user selected an enum option, the field resolved to a StringField instead of a SelectField.
Closes #6168

fix: Fixed SelectField dropdown arrow

---

Composer/packages/client/src/pages/botProject/PublishTargets.tsx
Composer/packages/client/src/pages/botProject/skill-configuration/AllowedCallers.tsx
Composer/packages/client/src/pages/botProject/skill-configuration/SkillToggle.tsx
Composer/packages/client/src/pages/botProject/skill-configuration/index.tsx
Composer/packages/client/src/pages/botProject/styles.ts
Composer/packages/server/src/locales/en-US.json

Add warning to empty allowed callers list
#minor

fix: Add warning to empty allowed callers list

---

Composer/packages/server/src/server.ts
Composer/packages/server/src/settings/env.ts
Composer/packages/server/src/utility/cleanHostedBots.ts
extensions/localPublish/src/index.ts

**issue**
We support the clean the local runtime date already, but the folder path is not correct when use the electron.
**fix**
1. use the correct the folder path to clean the electron runtime data.
2. add the check function to clean the local runtime folder when starting composer.
closes #5331

fix: clean the hostedBots/botid folder when deleting a bot

---

Composer/packages/client/src/pages/knowledge-base/table-view.tsx

- Display: Create new kb from scratch after created from url, the url Kb last qna pair will show in the new kb qna pair when adding new pair.
- Reason: the new qna pair index is not match the selected qna group
- Solution: set the qna pair index as the selected qna group's startIndex
- Display: Create new qna pair failed after delete empty qna pair. 
- Reason: the empty qna pair is not deleted but set `isCreateQnaSection` as false when clicking delete button, so  the `updateQnaSection` is invoked when re-create the qna pair, but the sectionId is none. The action will trigger the error modal.
- Solution: delete the empty qna pair.
closes #6657

fix: qna section display errs

---

Composer/packages/client/src/pages/publish/BotStatusList.tsx
Composer/packages/client/src/pages/publish/publishPageUtils.tsx
Composer/packages/client/src/pages/publish/type.ts
Composer/packages/client/src/recoilModel/selectors/project.ts
Composer/packages/server/src/locales/en-US.json
extensions/azurePublish/src/node/index.ts

This provides the basic link and copies the manifest URL to the clipboard.
A future PR will improve the copy experience to include a callout when copied via a more general purpose mechanism.
closes #6597

feature: Added skill manifest URL to publish page

---

Composer/packages/client/src/recoilModel/dispatchers/provision.ts
Composer/packages/server/src/controllers/provision.ts

Some users were seeing a 431 HTTP response when attempting to provision Azure resources.
This applies the same fix from https://github.com/microsoft/BotFramework-Composer/pull/5700 to the provisioning endpoint.
#minor

fix: ARM token for provisioning is now passed via body.

---

Composer/packages/tools/built-in-functions/jest.config.js
Composer/packages/tools/built-in-functions/package.json
Composer/packages/tools/built-in-functions/src/__tests__/builtInFunctionsUtils.test.ts
Composer/packages/tools/built-in-functions/src/builtInFunctionsMap.ts
Composer/packages/tools/built-in-functions/tsconfig.build.json

Adds test to built in functions, adds missing declarations and typos
closes #6674

fix: Adds test to built in functions, adds missing declarations and typos

---

Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx
Composer/packages/client/src/components/Header.tsx
Composer/packages/client/src/recoilModel/selectors/project.ts

adjust the mechanism used to determine if a project needs LUIS or QNA to support multi-bot projects. This moves code from the header component into a recoil selector.
fixes #6649

fix: detect "Get started" dependencies in all projects not just current project

---

extensions/azurePublish/src/node/provision.ts

add retry logic for adding app password while provisioning
#minor

fix: add retry logic for adding app password

---

Composer/packages/server/src/locales/en-US.json
Composer/packages/server/src/utility/project.ts

Writes a nuget config file into the project to allow it to resolve the pre-release SDK packages required to build the new runtime.
This should be TEMPORARY, and should be removed from the code once the GA SDK packages have shipped to Nuget.
Fixes #6705

fix: write a nuget config file to the project root

---

Composer/packages/client/src/pages/publish/Notifications.tsx
Composer/packages/server/src/locales/en-US.json

Fix plurality language for publishing notification
closes #6676

fix: Plurality language for publishing notification

---

Composer/babel.l10n.config.js

The l10n:babel extracts strings from the source code. 
It is currently including lib folders which contain built JS with the same formatMessage calls as the TS source.
This creates a lot of extra files in the l10ntemp folder which later l10n commands have to process - slowing the build.
This PR excludes those folders using the wildcard search pattern in the ignore section of the babel config file.
I tried to use the regex format, but it doesn't seem to work and babel won't output information about matches.
#minor 
Old yarn l10n build time (on my dev machine): 115 s
New yarn l10n build time (on my dev machine): 95 s
Savings: 20 s

chore: Improve l10n build performance

---

Composer/packages/electron-server/src/main.ts

Fixes an issue where deeplinks would not work correctly on mac when Composer was not already running.
fixes #6616

fix: handle protocol launches on macos from cold start

---

Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx
Composer/packages/client/src/pages/botProject/BotProjectsSettingsTabView.tsx
Composer/packages/client/src/pages/botProject/PublishTargets.tsx
Composer/packages/client/src/pages/publish/Publish.tsx
Composer/packages/client/src/pages/publish/components/projectList/ListItem.tsx
Composer/packages/client/src/pages/publish/components/projectList/ProjectList.tsx

At long last, the publishing profiles rejoin the publishing functionality on the publish page... this time, in a TAB!
Fixes #6710

fix: move publishing profiles into a tab on the publish page

---

Composer/packages/client/src/recoilModel/dispatchers/provision.ts
Composer/packages/server/src/locales/en-US.json
extensions/azurePublish/src/node/index.ts
extensions/azurePublish/src/node/provision.ts

When provisioning if one resource fails, this returns partial success and puts up a warning notification.
The profile is also saved on partial success.
The user will be able to open the profile target and try provisioning again.
closes #5959
Manually introduced error to show this partial success (uses the standard warning card for the notification)
Prod7 profile was saved

feature: Provisioning partial success handling

---

extensions/azurePublish/src/node/azureResourceManager/azureResourceManager.ts
extensions/azurePublish/src/node/azureResourceManager/azureResourceManagerConfig.ts
extensions/azurePublish/src/node/index.ts
extensions/azurePublish/src/node/provision.ts

Per the work item, parse the language from the runtime key and pass as workerRuntime to Azure functions provisioning.
closes #6528 
N/A

feature: Pass workerRuntime value from runtime key when provisioning Azure functions

---

Composer/packages/client/src/components/ManageLuis/ManageLuis.tsx
Composer/packages/client/src/components/ManageQNA/ManageQNA.tsx
Composer/packages/client/src/components/ManageSpeech/ManageSpeech.tsx
Composer/packages/client/src/pages/botProject/BotProjectsSettingsTabView.tsx

Set isBlocking to true on these 3 modals so they cannot be improperly dismissed while busy provisioning services.
fixes #6722
Fixes #6721

fix: Make LUIS, QNA and Speech blocking modals

---

Composer/packages/client/src/pages/botProject/BotProjectsSettingsTabView.tsx
Composer/packages/lib/shared/src/constant.ts
Composer/packages/server-workers/src/workers/templateInstallation.worker.ts

- Add missing mapping to facilitate deeplinking to qna and luis tab from getting started pane
- Changing error logging so more informative error message is surfaced to UI error modal
- Fixing QNAMaker bug caused by outdated empty bot package name. 
fixes #6721 
fixes #6770 
fixes #6745

fix: Fixing deep link for QNA and Luis

---

Composer/packages/client/__tests__/pages/botProjectsSettings/PublishTarget.test.tsx
extensions/azurePublish/package.json
extensions/azurePublish/src/node/index.ts
extensions/pvaPublish/src/node/index.ts

Per the work item, removed (Preview) from publish target names
fixes #6778 
N/A

fix: Removed preview from publish type names

---

extensions/packageManager/src/components/FeedModal.tsx
extensions/packageManager/src/node/feeds/feedInterfaces.ts
extensions/packageManager/src/node/feeds/npm/npmFeed.ts
extensions/packageManager/src/node/index.ts
extensions/packageManager/src/pages/Library.tsx

* Update package manager to expose the default search query field and pre-release option for each feed.
* Allow user to search against feeds using the feed's search capabilities
Fixes #6037 
Fixes #6038

feat: Expose default search query, pre-release flag and type for each feed.

---

Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx

Add links for devops and app insights to get started. These open links in a new window.
fixes #6555

feat: Add devops and app insights to get started

---

extensions/azurePublish/src/components/ResourceGroupPicker.tsx
extensions/azurePublish/src/components/azureProvisionDialog.tsx
extensions/azurePublish/src/node/provision.ts

When I did partial provisioning, I broke the save of tenant ID.
Good news though, it uncovered and issue on the edit mode of the dialog
#minor 
N/A

fix: Fixed broken tenant ID on save

---

Composer/packages/lib/indexers/package.json
Composer/packages/server/package.json
Composer/packages/tools/language-servers/language-understanding/package.json
Composer/yarn.lock

**Fixed**
update the bf-lu package version to make luis and qna publish support proxy. (wait for the npm package)
**Need to fix**
1. create bot
2. azure login
3. auth related
These three stages still don't support the proxy now. These maybe related to the node-fetch package.
#minor

fix: make composer support https proxy

---

Composer/packages/client/src/pages/publish/BotStatusList.tsx
extensions/azurePublish/src/node/index.ts
extensions/localPublish/src/index.ts

fix: bot can't start or publish by cleaning unused code

---

Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
Composer/packages/client/src/router.tsx

Small UI changes to resolve two UI bugs. 
First bug is that the loading text was hard to read during bot creation so that has been formatted to be rendered in its own modal similar to the spinner one sees when installing a new package
Second bug was the positioning of the toggle for advanced settings which overlapped the json editor and led to character overlap between the toggle and text in the JSON editor. 
fixes #6663 
fixes #6801

fix: loading spinner text to be more readable, appSettings toggle overlap bug

---

Composer/packages/client/src/components/ManageSpeech/ManageSpeech.tsx

fix an issue where the condition for disabled fields was reversed  inside the speech enablement widget.
#minor

fix: reverse condition for disabled fields

---

extensions/azurePublish/src/components/azureProvisionDialog.tsx

This is a part of fixing issue #6776.  This handles the case where the access token provided cannot be decoded successfully and the component sticks in the loading state. 
With the loading state not getting stuck, we can investigate if the Azure authentication gets stuck in the electron case.
#6776 
#minor

fix: Fixed loading sequence with token error msg

---

Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatActivityLogItem.tsx

This PR adds the trace type next to trace items in the Web Chat log.
Fixes #6749
**BEFORE:**
**AFTER:**

fix: Added trace type to Web Chat log

---

Composer/packages/client/src/pages/botProject/adapters/ABSChannels.tsx

Applies the resourceGroup field from the publishing profile rather than using the "name" field during the connections configuration.  Previously, resourceGroup and name were always identical, but can now be different.
fixes #6731

fix:  use resourceGroup name from publishing profile if one exists

---

Composer/packages/client/src/Onboarding/content.tsx
Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx
Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterSettings.tsx
Composer/packages/client/src/pages/design/VisualEditor.tsx
Composer/packages/client/src/pages/design/VisualPanelHeader.tsx
Composer/packages/client/src/pages/home/Home.tsx
Composer/packages/client/src/pages/setting/app-settings/electronSettings.tsx
Composer/packages/client/src/utils/hooks.ts

Fixes the followings:
1. deleting a dialog when it's selected in the tree crashes the app
2. react unique key warnings
3. react mutate state on an unmounted component
closes #6812

fix: deleting a dialog when it's selected in the tree crashes the app

---

Composer/packages/server/src/controllers/publisher.ts
Composer/packages/server/src/locales/en-US.json
Composer/packages/types/src/telemetry.ts

Add msAppId and subscriptionId to PublishingProfileCompleted
#minor
@garypretty

fix: Add msAppId and subscriptionId to PublishingProfileCompleted telemetry

---

.vscode/launch.json
Composer/packages/client/src/components/ProjectTree/TopicsList.tsx
Composer/packages/server/src/externalContentProvider/__tests__/powerVirtualAgentsProvider.test.ts
Composer/packages/server/src/externalContentProvider/powerVirtualAgentsProvider.ts
Composer/packages/server/src/models/bot/botProject.ts
Composer/packages/ui-plugins/select-dialog/src/ComboBoxField.tsx
extensions/pvaPublish/src/node/publish.ts

Also includes other minor UX updates.
refs #6047

feat: include pva topics by default

---

Composer/packages/ui-plugins/select-dialog/src/SelectDialogMenu.tsx

Fixes an issue where the dialogs where still filtered after a user has exited the menu.
fixes #7216

fix: reset filter upon dismissing menu

---

Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx

Bad conditional led to runtime type dropdown to never show in creation when it should only not show in PVA scenarios. Comparison syntax fixed.
fixes #7174

fix: runtime dropdown regression in creation flow

---

Composer/packages/client/src/pages/setting/app-settings/AppSettings.tsx
Composer/packages/client/src/pages/setting/app-settings/SettingDropdown.tsx
Composer/packages/server/src/locales/en-US.json

Fixes: The locale dropdown options menu does not render below the dropdown. Instead it renders off to the side.
closes #7214

fix: app settings - language settings dropdown

---

extensions/localPublish/src/index.ts

This PR excludes the `luis:endpointKey` value from the command line arguments if neither the endpoint or authoring kye is present.
Passing in a blank value for this can cause windows to misintepret the following keys, which can make QNA fail.
Fixes #7220

fix: Do not pass blank luis endpoint value to runtime

---

Composer/packages/client/src/pages/botProject/adapters/ABSChannels.tsx

Prefer the `botName` field over the `name` field if set, when dealing with connections.
This allows the name to be different than botName, which is the case in the ABS handoff scenario.
Fixes #7158

fix: prefer the botName field instead of the name field when managing connections

---

Composer/packages/client/src/components/GetStarted/GetStarted.tsx
Composer/packages/client/src/components/Header.tsx
Composer/packages/client/src/components/Notifications/NotificationContainer.tsx
Composer/packages/client/src/components/Notifications/NotificationPanel.tsx
Composer/packages/client/src/utils/zIndices.ts

Notification toast should have higher/highest Z order
minor fixes:
same width for all panels (minimal fix)
get started panel header and dismiss button css issues
closes #7194
https://user-images.githubusercontent.com/1483492/115774851-f22d9f80-a366-11eb-8932-f50a589fd3cc.mp4

fix: Notification toast should have higher/highest Z order

---

extensions/azurePublish/src/components/azureProvisionDialog.tsx

Region for Microsoft Bot Channels Registration resource type will now show as 'global' .
fixes #6680

fix: Region for Microsoft Bot Channels Registration is now 'global'

---

Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
Composer/packages/client/src/components/DisableFeatureToolTip.tsx
Composer/packages/server/src/locales/en-US.json
extensions/pvaPublish/src/node/publish.ts

Marketing does not allow abbreviating Power Virtual Agents.

fix: replace PVA with Power Virtual Agents

---

Composer/packages/client/src/recoilModel/Recognizers.tsx

Composer move lu and qna parse to the backend, the recognizers may be generated when the lu parse result is empty. 
generate the recognizers after all files are parsed.
closes #7141

fix: Empty setting for recognizer configuration when switch bot

---

Composer/packages/client/src/components/AddRemoteSkillModal/CreateSkillModal.tsx
Composer/packages/client/src/components/AddRemoteSkillModal/SelectIntent.tsx
Composer/packages/client/src/pages/design/Modals.tsx
Composer/packages/client/src/pages/design/SideBar.tsx
Composer/packages/client/src/recoilModel/dispatchers/botProjectFile.ts
Composer/packages/client/src/recoilModel/dispatchers/project.ts
Composer/packages/server/src/locales/en-US.json

fix several issue: 
1. when manifest dispatch modal is null or intent is null, just add the skill without trigger.
2. when deleting skill, find the relevant trigger to delete.
3. If not find the relevant trigger, just delete the skill.
close #7144 
close #7245

fix: delete wrong trigger when delete skill and its trigger

---

Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatActivityLogItem.tsx
Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatLogContent.tsx
Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatNetworkLogItem.tsx

The Web Chat log panel was spitting out an error about the log item components not having unique keys.
#minor

fix: Moved Web Chat log item keys outside of component

---

Composer/packages/client/config/env.js
Composer/packages/client/src/pages/about/About.tsx
Composer/packages/electron-server/src/main.ts
Composer/packages/electron-server/src/preload.js
Composer/packages/server/src/constants.ts
Composer/packages/server/src/models/bot/builder.ts
Composer/packages/server/src/server.ts
Composer/packages/server/src/utility/getVersion.ts

Fixes an issue where the preload.js script could not be loaded due to `app` being undefined in the renderer process.

fix: refactor way we get COMPOSER_VERSION

---

Composer/packages/lib/code-editor/src/lu/LuLabelingMenu.tsx

Show LUEditor labeling menu below any Fabric layer
fixes #6799 
https://user-images.githubusercontent.com/1483492/115908116-94f52500-a41e-11eb-9d7f-d013a02673ab.mp4

fix: Show LUEditor labeling menu below any Fabric layer

---

Composer/packages/client/config/env.js
Composer/packages/client/src/pages/about/About.tsx

fix: Updated links on About page

---

Composer/packages/client/src/pages/design/exportSkillModal/content/AddCallers.tsx
Composer/packages/electron-server/package.json

fix: allower callers displayed like available to edit.
closes #7147

fix: allower callers displayed like available to edit

---

Composer/packages/client/src/components/PluginHost/PluginHost.tsx
Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx
Composer/packages/client/src/pages/plugin/PluginPageContainer.tsx
extensions/azurePublish/src/components/azureProvisionDialog.tsx

Makes shell available in all plugin contexts which exposes the telemetry client.
fixes #7273

fix: re-enable telemetry events in azure provision dialog

---

Composer/packages/lib/code-editor/src/BaseEditor.tsx

Allow Monaco editor allow scrolling on parent elements.
close #7351

fix: Monaco editor allow scrolling

---

Composer/packages/client/src/components/AddRemoteSkillModal/CreateSkillModal.tsx
Composer/packages/client/src/components/ProjectTree/ExpandableNode.tsx
Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
Composer/packages/client/src/router.tsx
Composer/packages/client/src/utils/hooks.ts
Composer/packages/client/src/utils/pageLinks.ts
Composer/packages/server/src/models/bot/builder.ts
extensions/packageManager/src/pages/Library.tsx

This fixes the logic around entering the plugin manager when a skill is focused; the URL now includes both the root and skill IDs as it does for many of the other links. This involved a change to the router, and some additional logic to make sure we disable parts of the sidebar that don't apply to remote skills. This also includes a cosmetic fix to the ProjectTree to make remote bots line up with everything else as they should.
closes #7159
Correct indentation for remote bots, and no skill shown in the package manager list. Clicking on the package manager link now directs to the manager for the root bot, not whichever skill it's pointed to.
Grayed-out sidebar icons

fix: better display and logic around handling remote skills

---

Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx
Composer/packages/client/src/components/GetStarted/GetStartedTask.tsx
Composer/packages/client/src/components/GetStarted/types.ts

Show DisableFeatureToolTip UI only in PVA context
Fixes #7340

fix: Resolve PVA check logic missing

---

Composer/packages/adaptive-form/src/components/fields/RecognizerField/RecognizerField.tsx
Composer/packages/types/src/telemetry.ts

feat: Add RecognizerChanged telemetry event
Closes #7278

feat: Add RecognizerChanged telemetry event

---

Composer/packages/server/src/services/project.ts

Remove bot project from the recent projects list if it doesn't exist anymore
#minor

fix: Remove bot project from the recent projects list if it doesn't exist anymore

---

Composer/packages/client/__tests__/pages/botProjectsSettings/AdapterSettings.test.tsx
Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx

The adapter modal was interpreting `{field: undefined}` as that field still being present, so this fixes that and adds a unit test to make sure this doesn't happen again.
closes #7224

fix: correct logic for validating connection modal

---

Composer/packages/client/src/components/TriggerCreationModal/resolveTriggerWidget.tsx
Composer/packages/server/src/locales/en-US.json

Remove the `LUIS` text from the Trigger Dialog - minor change to imply this trigger can also be used for other recognizers.
fixes #7019
Removed `(LUIS)` from the copy

chore: Remove LUIS text from Trigger Dialog

---

Composer/packages/client/src/router.tsx

fix unable to navigate to plugin page, introduced in #7330.
fixed by adding back route config in no skill case.
refs #7330
when select on root bot
when select on skill bot

fix: plugin page router

---

Composer/packages/server/src/models/bot/builder.ts

Catches an error from QNA that indicates that the search service may need to be upgraded.
Fixes #7217

fix: Catch common QNA maker error about limits

---

extensions/packageManager/src/node/index.ts

Part of the package install process is to write a line to the appsettings.components array for code-driven components.
Since these components may or may not have schema, we need to use the package TAGS to determine if they should be included.
A previous PR used the `msbot-component` tag, but this proved to be too broad as it includes the declarative-only components that SHOULD NOT be added to this list.
This PR changes the logic to look for one of a series of feature-specific tags.
Fixes #7403

fix: use feature-specific tags rather than msbot-component

---

extensions/azurePublish/src/node/azureResourceManager/azureResourceManager.ts

The azure provisioning was not returning the location field expected in the provisioning result.
fixes #7288

fix: luis provisioning to return location

---

Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx

By default, a local bot will be set up with ONLY a LUIS authoring key. The authoring key can be used up to 1000 times a month as an endpoint key, which works for local testing.
However, if this limit is reached, the bot will stop working and throw LUIS errors.
This PR introduces a warning thaat appears on the bot settings page if a LUIS authoring key is set without an endpoint key.
The warning tells the user to publish to Azure if this limit is reached, and links to information about the key limits.
Fixes #7146

fix: Add a warning about the luis authoring key 1000/month limit 

---

Composer/packages/client/src/components/CreationFlow/v2/AddBotModal.tsx
Composer/packages/client/src/constants.ts
Composer/packages/client/src/pages/design/SideBar.tsx
Composer/packages/client/src/pages/design/creationModal.tsx

This PR makes the UI changes to match the desired add skills UI for R13 which is described in the figma that is linked from the below issue.
fixes #7115 
**Toolbar drop down change**
**New Choice Modal**
**If you select 'add existing'**
**If you select 'add blank'**

fix: add skills flow refactored to desired R13 spec

---

extensions/azurePublish/src/components/util.ts

The utils was missing noting azure functions are provisioned when the hostname is present.
fixes #7453 
N/A

fix: Add azure functions existing when hostname there

---

extensions/azurePublish/src/components/azureProvisionDialog.tsx

1. Moved the buttons to the right when the sign out button is not shown.
2. Removed the sign out button, when is user is not signed in.
fixes #7236 
fixes #7162

fix: Fixed the buttons position on the provisioning modal & removed the sign out button when not required.

---

Composer/packages/extension-client/src/hooks/__tests__/useRecognizerConfig.test.tsx
Composer/packages/extension-client/src/hooks/useRecognizerConfig.ts

Hides recognizers if they do not exist in the app schema.
fixes #7468

fix: hide recognizers if they don't exist in the app schema

---

Composer/cypress/integration/HomePage.spec.ts
Composer/packages/client/src/pages/home/Home.tsx

Since we don't have a clear definition on what the behavior should be for copying both parent bots and skills nor a clear solution on how to implement the behavior, we are disabling the 'Save as' button on the home page in R13 with the intention of adding the feature back in a future release.
ref #6808

chore: Temporarily removes save as button for R13

---

Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx

Adds an optional "Publish your bot" button to get started once a user has added a complete publishing profile.
Fixes #6555

fix: Add Publish your bot to get started list

---

Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx
Composer/packages/client/src/components/ImportModal/ImportModal.tsx
Composer/packages/client/src/constants.ts

The naming constraints for BF created bots do not apply for PVA bots. Dashes are allowed.
Also converts invalid characters to dashes upon import so there is no error.
fixes #7486

fix: allow dashes for pva bot names

---

Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx
Composer/packages/server/src/locales/en-US.json

Text describing Microsoft AppId in the settings view was inaccurate, This PR changes the text to the desired copy outlined in the below issues
fixes #7426

fix: correct the MS AppID text in the settings view

---

Composer/packages/client/src/shell/utils.ts
Composer/packages/lib/code-editor/src/lg/ModalityPivot.tsx
Composer/packages/lib/code-editor/src/lg/constants.ts
Composer/packages/lib/code-editor/src/lg/modalityEditors/AttachmentModalityEditor.tsx
Composer/packages/lib/code-editor/src/utils/structuredResponse.ts
Composer/packages/lib/shared/__tests__/lgUtils/stringBuilders/lgStringUtils.test.ts
Composer/packages/lib/shared/src/lgUtils/index.ts
Composer/packages/lib/shared/src/lgUtils/stringBuilders/lgStringUtils.ts
Composer/packages/test-utils/src/react/jest.config.ts
Composer/packages/ui-plugins/lg/src/LgWidget/useLgTemplate.ts

fixes #7564
opens https://github.com/microsoft/BotFramework-Composer/issues/7394

chore: Revert "fix: Update attachment template format to support PVA"

---

Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
Composer/packages/client/src/components/Header.tsx

This PR adds an `id` field to the start bot so it can be targetted with the teaching bubble.
Fixes #7560

fix: address a regression in the start bot button that caused final 'get started' bubb not to pop

---

Composer/package.json
Composer/packages/server/package.json
Composer/yarn.lock
extensions/packageManager/package.json
extensions/packageManager/yarn.lock

Bumps wait-on to v5.3.0 which includes a axios version upgrade to address a security vulnerability (https://snyk.io/vuln/SNYK-JS-AXIOS-1038255)
closes #7647

chore: bump wait-on to v5.3.0

---

Composer/packages/client/__tests__/pages/botProjectsSettings/PublishTarget.test.tsx
Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx
Composer/packages/lib/ui-shared/src/components/ProvisionHandoff/ProvisionHandoff.tsx
Composer/packages/server/src/locales/en-US.json
extensions/azurePublish/src/components/ChooseProvisionAction.tsx
extensions/azurePublish/src/components/azureProvisionDialog.tsx
extensions/azurePublish/src/node/resourceTypes.ts
extensions/pvaPublish/src/components/pvaDialog.spec.tsx
extensions/pvaPublish/src/components/pvaDialog.tsx
extensions/pvaPublish/src/node/index.ts

This is the updated copy for provisioning and publishing P0 items as of 5/4/21.
Fixes #7583 
Screenshots

fix: Update provision & publishing copy (#7583)

---

extensions/samples/assets/shared/.gitignore

Remove the appsettings file from the default .gitignore file that is inserted as part of the boilerplate content.
This change is necessary because the appsettings file contains settings that are critical to the function of the bot -- OUTSIDE of the various keys and credentials that may be present.
fix #7677

fix: remove appsettings file from default gitignore

---

Composer/packages/client/src/components/Page.tsx
Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx

This adds some CSS to restore the gray border beneath the page header.
closes #7656

fix: restore line beneath page header

---

Composer/packages/server/src/services/project.ts
extensions/packageManager/src/node/index.ts

* Add the `components` field to the migrated settings during migration
* During the component install process, check against the fields absence and create if missing
* Move call to res.json below other tasks (this was causing errors to be swallowed)
Fixes #7670

fix: Add components field to migrated settings.

---

Composer/packages/lib/shared/src/dialogFactory.ts

Per Switch [schema](https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SwitchCondition.schema#L17), this conditional is expecting a `StringExpression`,  and I was feeding it an integer. 
Strangely, Composer did not show a validation error on this bug until recently.  Thanks @tdurnford  and @hatpick  for explaining the validation logic in Composer.
With this fix, template doesn't throw anymore errors and bot can be built.
fixes #7700

fix: Feed string, not int, to Switch per schema

---

Composer/packages/client/src/pages/botProject/PublishTargets.tsx
Composer/packages/client/src/pages/publish/Publish.tsx
Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts

base on #7519, fix publish target types missing in provision dialog
refs #7519

fix: fix publish target types missing in provision dialog

---

Composer/packages/client/src/pages/botProject/CreatePublishProfileDialog.tsx
Composer/packages/client/src/pages/design/exportSkillModal/constants.tsx
Composer/packages/client/src/pages/design/exportSkillModal/generateSkillManifest.ts
Composer/packages/client/src/pages/design/exportSkillModal/index.tsx

fix: generate manifest file when creating new publish target
Bind generateManifest & publish function after creating or selecting publish target.
closes #7655

fix: generate manifest file when creating new publish target

---

Composer/packages/client/src/pages/botProject/create-publish-profile/ProfileFormDialog.tsx

Some of the newer templates were not designed to be publishable to Power Virtual Agents, and so when a user tries to publish one of these bots to PVA it provides a bad experience.
This PR provides a mechanism that allows us to hide certain publishing profile types -- one of them being the PVA profile -- from the publishing profile dropdown.
Fixes #7703, #7467
**BEFORE:**
**AFTER:**

fix: Hides the PVA publish profile from the profle creation dropdown

---

Composer/packages/lib/code-editor/src/lg/constants.ts
Composer/packages/lib/code-editor/src/lg/modalityEditors/AttachmentModalityEditor.tsx

Revert template changes in PR #7593 to support PVA
Closes #7394

fix: Revert changes to adaptive card templates to support PVA

---

Composer/packages/client/src/components/WebChat/WebChatHeader.tsx
Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
Composer/packages/client/src/components/WebChat/__tests__/WebChatHeader.test.tsx

This PR addresses a scenario where "Restart Conversation" was hit quite a few times in under a second. In certain situations, it freezes Composer. This is a partial fix to avoid Composer getting into this state by a) throttling the button (1s) b) Disabling it while the bot is being restarted c) Disabling the button until the asynchronous operation of restarting the conversation completes.
The second half of the fix would be in a separate PR. This would involve performing cleanup tasks on electron before-quit event. The cleanup tasks include code written to manually close the directline server, runtime log server and the express server. This could be leveraged for closing dangling bot runtimes as well.
Refs #7788

fix: Throttle restart conversation

---

Composer/packages/server/src/services/project.ts

Closes #7769 
Blob transcript field name on migration needs to have `connectionString` and `containerName`. Adjusting migration code to reflect that config transform.
Testing: Tested migration with blob transcript in old format, verified blob transcript properly migrated by visually inspecting the settings, plus verifying the storage in Azure
Also tested the migration where there is no blob transcript, and verified that the target project has no transcript.

fix: Migration: adjust target blob transcript field names

---

Composer/packages/lib/code-editor/src/lg/hooks/useStringArray.ts

Updates the `useStringArray` hook to always use an intermediate template for the text and speak modalities in the LG Response Editor.
Closes #7841

fix: Always use intermediate lg template for text and speak modalities

---

Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx
Composer/packages/client/src/components/Header.tsx
Composer/packages/client/src/recoilModel/atoms/appState.ts
Composer/packages/client/src/recoilModel/dispatchers/application.ts
Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts

Issue
- Hash routing does not work with multi bot templates due to hash lost in redirects.
- We should use recoil state for things like detecting if panes are open or not
Solution
-Move teachingbubble render state to recoil and respective calls to manage that new state value         
fixes #7734

fix: resolving getting started teaching callout not rendering

---

Composer/package.json
Composer/yarn.lock

Resolve dns-packet to 1.3.4 to fix CVE-2021-23386
#minor

chore: Resolve dns-packet to 1.3.4 to fix CVE-2021-23386

---

Composer/packages/adaptive-form/src/components/fields/IntellisenseFields.tsx

Intellisense on property editor missing user-variables
fixes #7949

fix: Intellisense on property editor missing user-variables

---

Composer/packages/client/src/recoilModel/dispatchers/multilang.ts

luEditor use intent.fileId, it need to be updated when add a language lu file.
close #8003

fix: multilang lu editing bug

---

Composer/packages/lib/indexers/package.json
Composer/packages/tools/language-servers/language-understanding/package.json
Composer/yarn.lock

In https://github.com/microsoft/BotFramework-Composer/pull/7399, the bf-lu package was upgraded to dev-20210602 version. 
There are two more places using bf-lu. In this PR, I also upgraded the package version here.
#minor

chore: Upgrade bf-lu to latest dev version

---

Composer/packages/client/src/components/TriggerCreationModal/TriggerCreationModal.tsx
Composer/packages/client/src/components/TriggerCreationModal/resolveTriggerWidget.tsx

Fix by maintain a shadow lufile appending  created trigger intent, then editor will get the context.
close #7517

fix: trigger creation LUIS entity labelling

---

extensions/azurePublish/yarn.lock

#minor 
Due to the package of bf-lu version in `/extensions/azurePublish` is outdated. And I just upgraded the bf-lu to the latest dev build in Composer recently. The dependency bot's PRs for upgraded ws and browserslist are not using the right version of bf-lu.
So I did the upgrade in this PR.
Bumps ws from 7.4.4 to 7.4.6.
Bumps browserslist from 4.16.3 to 4.16.6.
Related PRs:
https://github.com/microsoft/BotFramework-Composer/pull/7933
https://github.com/microsoft/BotFramework-Composer/pull/7961

chore: bump ws from 7.4.4 to 7.4.6 and browserslist from 4.16.3 to 4.16.6. in /extensions/azurePublish

---

Composer/package.json
Composer/yarn.lock

PRs have been failing on security detection because of `css-what`; it and `css-select` both need to be upgraded in order to resolve this.
#minor

chore: upgrade css-what and css-select

---

Composer/package.json
Composer/packages/client/package.json
Composer/packages/server/package.json
Composer/yarn.lock

#minor
Fix the component governance CI failure

chore: (security) update ejs to 3.1.6

---

Composer/packages/adaptive-flow/package.json
Composer/packages/lib/indexers/package.json
Composer/packages/tools/language-servers/language-generation/package.json
Composer/yarn.lock

Improve the performance while a normal template contains long body.
update the botbuilder-lg version in composer. The time of a 4M file parse is reduced from 42s to 10s
#minor
refs microsoft/botbuilder-js#3593
refs #7246

perf: [LG]Improve the performance of parsing long body

---

Composer/packages/ui-plugins/prompts/src/ExpectedResponsesField.tsx

The expected responses' placeholder is the same under different recognizers. The placeholder of regex recognizer is like
this may confuse users.
**fix**
update the placeholder for regex recognizer
refs #7779
fixes #7816

fix: update the expected responses placeholder

---

Composer/package.json
Composer/packages/client/package.json
Composer/packages/lib/code-editor/package.json
Composer/packages/tools/language-servers/language-understanding/package.json
Composer/yarn.lock
extensions/azurePublish/yarn.lock
extensions/azurePublishNew/yarn.lock
extensions/localPublish/yarn.lock
extensions/pvaPublish/yarn.lock
extensions/sample-ui-plugin/yarn.lock
extensions/yarn.lock

bump normalize-url from 4.5.0 to 4.5.1 in /Composer
bump normalize-url from 4.5.0 to 4.5.1 in /extensions/azurePublish 
bump glob-parent from 5.1.1 to 5.1.2 in /extensions/localPublish
bump merge-deep from 3.0.2 to 3.0.3 in /Composer
bump browserslist from 4.7.3 to 4.16.5 in /Composer
bump ssri from 7.1.0 to 7.1.1 in /Composer
bump hosted-git-info from 2.8.8 to 2.8.9 in /extensions/azurePublish
bump lodash from 4.17.20 to 4.17.21 in /extensions/localPublish
bump hosted-git-info from 2.7.1 to 2.8.9 in /Composer
bump ua-parser-js from 0.7.19 to 0.7.28 in /Composer 
closes #8045 
closes #8044 
closes #8043 
closes #8027 
closes #7917
closes #7863
closes #7746
closes #7745
closes #7717
closes #7704

chore: bump some dependencies to higher version

---

.github/workflows/main.yml

The actions/cache@v2 has been updated and we can try the latest example of caching for yarn to see if we can speed up this CI build.
#minor
**Before**
**After**
**Example of cache hit**

chore: Add back yarn caching

---

extensions/samples/assets/shared/scripts/DeploymentTemplates/template-with-preexisting-rg.json
extensions/samples/assets/shared/scripts/provisionComposer.js

Customer reported that provisioning hand-off script defaults many resources to the resource group name.  Updated the script to pass the resource name to the ARM template.  Updated the arm template to default several values to the name parameter rather than defaulting to the resource group name.
fixes #7966
A set of resources provisioned by Composer
A set of resources provisioned by the hand-off script before the fix
A set of resources provisioned by the hand-off script after the fix

fix: Provisioning hand-off should use resource name not resource group name

---

Composer/packages/client/__tests__/components/getStarted.test.tsx
Composer/packages/client/src/components/GetStarted/GetStartedLearn.tsx
Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx
Composer/packages/client/src/components/GetStarted/GetStartedTask.tsx

Developed unit tests for `GettingStarted` component:
```<GetStartedLearn />
√ should render the component (142 ms)
<GetStarted />
√ should render the component (333 ms)
√ should render lg and lu steps (unconditional required steps) (181 ms)
√ should render packages and insights steps (unconditional optional steps) (159 ms)
√ should render readMe next step (168 ms)
√ should not render readMe next step (143 ms)
√ should render LUIS and QNA (156 ms)
√ should not render LUIS and QNA (134 ms)
√ should render lu and qna checked (146 ms)
√ should render lu and qna unchecked (124 ms)
√ should not render create publish profile step (180 ms)
√ should render create publish profile step and not complete profile step (153 ms)
√ should render complete profile step (152 ms)
√ should render publish step …
```

chore: add get started tests

---

Composer/packages/electron-server/scripts/copy-artifacts.js

**root cause**
runtime folder has been removed in #7870. But the electron build still copy the runtime folder and will throw error
#minor

fix: electron build failed to copy runtime folder

---

extensions/azurePublishNew/src/components/provisioningWizards/HandOffToAdminWizard.tsx
extensions/azurePublishNew/src/components/shared/ChooseResourcesList.tsx
extensions/azurePublishNew/src/components/shared/wizard/Wizard.tsx
extensions/azurePublishNew/src/hooks/useHandOffInstructions.ts
extensions/azurePublishNew/src/recoilModel/atoms/handOffToAdminState.ts
extensions/azurePublishNew/src/recoilModel/dispatchers/handOffToAdminDispatcher.ts
extensions/azurePublishNew/src/recoilModel/dispatchers/index.ts

1. Added HandOffToAdmin step
2. Fixed height issues in the wizard
3. Fixed selection issue in the choose resource list component.
refs #7632

feat: Added HandOffResourcesToAdmin step

---

Composer/packages/server/src/models/bot/__tests__/orchestratorBuilder.test.ts

FT was broken after some lib updates.   Composer doesn't run this test (because it's very bandwidth heavy, we disable this by default in our jest config), but Orchestrator team does in their validation.
#minor

fix: Orchestrator broken Feature Test

---

Composer/packages/server/src/models/asset/assetManager.ts

In a recent change #7870, all the existing bot templates that existed in `/extensions/samples/assets/projects` were removed. There was a piece of code inside of `BotProject.init()` that would use the `.botproj` file of the first bot template in that directory as a skeleton to be filled out for old bots that needed to create a project file.
Since there are no longer any bot templates in that directory, this piece of code always returns `undefined` and no `.botproj` file is created for old bots. **This was causing bots imported from PVA to throw an error when being opened because of a missing project file**
This PR takes the old `.botproj` skeleton that was present in the EchoBot sample and puts it into the code to be referenced by old bots.
#minor

fix: Added in-code default bot project file to use for old bots

---

extensions/azurePublish/src/node/deploy.ts

Previously, the logic to reset skillHostEndpoint in the publish process is:
- when skillHostEndpoint has value, reset it to https://${hostname}.azurewebsites.net/api/skills
This will cause an issue that when the bot has never been started from local, it will not be set in the publish process. which will cause a runtime error. 
This fix is to Set skillHostEndpoint when settings.skill has value. 
Closes #7856

fix: Update the skillHostEndpoint when settings.skill has value

---

Composer/packages/server/src/externalContentProvider/powerVirtualAgentsProvider.ts
extensions/pvaPublish/src/node/constants.ts
extensions/pvaPublish/src/node/utils.spec.ts
extensions/pvaPublish/src/node/utils.ts

Follow-up PR to #8169
Forgot to add GCC support to publish as well.
#minor
Response payload from publish (notice the testUrl):
```
{
operationId: '1d13b314-1e8d-49c2-bbf1-baf0096624e1',
startTimeUtc: '2021-06-24T16:43:35.9768906+00:00',
lastUpdateTimeUtc: '2021-06-24T16:44:04.0133777+00:00',
diagnostics: [
{
code: 'FileIsIgnored',
range: null,
severity: 'Warning',
source: 'fresh-bot-for-composer.botproj',
message: "File 'fresh-bot-for-composer.botproj' is unknown for the system and was ignored during the import."
}
],
state: 'Done',
comment: null,
importedContentEtag: 'W/"none"',
testUrl: 'https://gcc.api.powerva.microsoft.us/environments/2d90f6e4-1a37-474e-b573-d0048387debb/bots/37f66313-8c31-4f6c-a84b-6d36151095c1/topics/all'
}
```

fix: Added support for GCC env to PVA publishing

---

Composer/packages/client/src/components/TriggerCreationModal/TriggerCreationModal.tsx
Composer/packages/client/src/components/TriggerCreationModal/TriggerDropdownGroup.tsx
Composer/packages/client/src/utils/__tests__/auth.test.ts
Composer/packages/client/src/utils/__tests__/buildUtil.test.ts
Composer/packages/client/src/utils/__tests__/dialogUtil.test.ts
Composer/packages/client/src/utils/__tests__/fileUtil.test.ts
Composer/packages/client/src/utils/__tests__/luFileStatusStorage.test.ts
Composer/packages/client/src/utils/__tests__/luUtil.test.ts
Composer/packages/client/src/utils/__tests__/navigation.test.ts
Composer/packages/client/src/utils/convertUtils/__tests__/designerPathEncoder.test.ts
Composer/packages/client/src/utils/convertUtils/__tests__/parsePathToFocused.test.ts
Composer/packages/client/src/utils/convertUtils/__tests__/parsePathToSelected.test.ts
Composer/packages/client/src/utils/convertUtils/__tests__/parseTypeToFragment.test.ts
Composer/packages/client/src/utils/dialogUtil.ts
Composer/packages/integration-tests/cypress/integration/DesignPage.spec.ts

Falls back to the label defined in the trigger ui schema when creating new triggers unless there is a more appropriate name.
closes #7943

feat: use trigger schema to populate $designer.name for new triggers

---

Composer/packages/client/src/components/AddRemoteSkillModal/CreateSkillModal.tsx
Composer/packages/client/src/recoilModel/selectors/dialogs.ts

**in the PR**
if the root dialog is orchestrator recognizer type or user chooses orchestrator type before connecting the skill, add the trigger to the root dialog.
closes #7448

fix: add trigger to the root dialog when adding a new skill

---

extensions/localPublish/src/index.ts

**root cause**
The system shell will strip off quotes around parameters, so the program gets the unquoted value at the end. Spawning a process bypasses this step as it bypasses the shell, so the program gets those literal quotes as part of the parameter and doesn't know how to handle them appropriately.
**fix**
use { shell: true }. This will pass the spawn request through the shell
fixes #8205

fix: Quotes in node spawn arguments make the runtime fail

---

Composer/packages/client/src/components/WebChat/WebChatComposer.tsx
Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
Composer/packages/client/src/components/WebChat/__tests__/WebchatPanel.test.tsx
Composer/packages/client/src/components/WebChat/types.ts
Composer/packages/client/src/components/WebChat/utils/WebChatTypes.d.ts
Composer/packages/client/src/components/WebChat/utils/conversationService.ts
Composer/packages/client/src/recoilModel/selectors/project.ts
Composer/packages/client/src/utils/luUtil.ts

1. A bad import from webchat-component caused the rendering of adaptive cards to break. Fixed the import to be from webchat.
2. The conversation is memoized for until a new bot is opened. This makes the webchat hold on to stale MsAppId and MsPassword when the secrets are updated. Adding secret as a dependancy as well to change conversationID along with secret.
@boydc2014 @luhan2017 Could you give this branch a go if this fixes it?
Fixes #8226

fix: Adaptive card rendering issue in Webchat & Rerender on appId change

---

Composer/packages/electron-server/electron-builder-config.json

`orchestrator-core` changed to `@microsoft/orchestrator-core` for 4.14, the electron-builder config is updated to reflect this so that the mac/linux electron builds can start. Windows build does not have problems even without this fix because for some reason electron-builder's binary detection only works correctly in Windows for this lib.  
manual nightly build with this change here for verification: <https://fuselabs.visualstudio.com/Composer/_build/results?buildId=255945&view=results>
#minor

chore: orchestrator-core changed to @microsoft/orchestrator-core

---

Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WatchTab/WatchTabContent.tsx
Composer/packages/client/src/pages/design/DebugPanel/WatchVariablePicker/WatchVariablePicker.tsx
Composer/packages/types/src/telemetry.ts

Adds two telemetry events to the Watch tab:
> Event Name: StateWatchPropertyAdded
Fires when a user adds a property to watch.
Should include a custom property called 'property' which contains the property path being watched.
>Event Name: StateWatchPropertyRemoved
Fires when a user removes a watched property.
Should include a custom property called 'property' which contains the property path being removed.
Fixes #7948

chore: Added telemetry to watch tab

---

Composer/packages/lib/indexers/__tests__/validations/expressionValidation.test.ts
Composer/packages/lib/indexers/src/validations/expressionValidation/index.ts
Composer/packages/lib/indexers/src/validations/expressionValidation/validation.ts

**root cause**
all expressions are considered as starting with "=", so the "string()" is cut off, and expression parser will check the function "tring()".
**fix**
1. check the "=" before parsing
2. update the unit tests
#minor

fix: If/else conditions causes warning/error

---

extensions/localPublish/src/index.ts

should set running bots' port to avoid the conflict during finding a port for each request.
Closes #7765

fix: race condition on finding port while starting all bots

---

Composer/packages/integration-tests/cypress/integration/HomePage.spec.ts

The rollback of the runtime dropdown to default to web app broke integration tests.
#minor
N/A

fix: Remove previous integration fix that is causing a problem

---

Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticFilters.tsx
Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/RuntimeOutputLog/RuntimeOutputLog.tsx
Composer/packages/client/src/pages/design/DebugPanel/WatchVariablePicker/WatchVariablePicker.tsx

Allow restart conversation to take the updated secret and locale when restarting the webchat conversation.
@boydc2014  @luhan2017 Could you give this branch a test before we merge?
In addition, this PR has some misc style fixes
Fixes #8226

fix: Update conversation object when secret and locale changes

---

Composer/packages/server/src/models/bot/__tests__/botProject.test.ts

This PR comments out the unit tests in botproject that seem to make API calls to consume the manifest.
@alanlong9278 a couple of changes required
1. Let us not await on API calls in unit tests and instead just use mocked responses.
2. Lets not commit actual URL's to the repo.
3. The 10000ms waiting on the test ruins the efficiency of the test suite. Let us not force wait on the unit test beyond the default jest test timeout. 
Cc @luhan2017 
#minor

fix: Comment out skill manifest unit tests

---

Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/ActionCard/ActionCardBody.tsx

Reverts change to support node body background color. We will need to defer that work until the ui schema for BeginSkill is updated to be correct.
fixes #8253

fix: fix begin skill action node

---

Composer/packages/electron-server/scripts/mac.js

There was a recent change that is now generating a `mockManifest.zip` file inside of the `/electron-server/` directory, which is interfering with a build script that generates the `latest-mac.yml` file. It is causing the wrong content to be written to this .yml file which is breaking auto update for Mac.
**Correct contents:**
```yaml
version: 2.0.0-nightly.255969.45d2dd7
releaseDate: '2021-07-01T06:09:06.959Z'
githubArtifactName: BotFramework-Composer-2.0.0-nightly.255969.45d2dd7-mac.zip
path: BotFramework-Composer-2.0.0-nightly.255969.45d2dd7-mac.zip
sha512: >-
sgQT81CnThQ5AqQ17NO7e3Zfqizn7KNh6j+GYqsBdeO0UJbBtlQhlAa5FNgTxvsCdczg/oNTnFjbJ6xZzgAp3g==
```
**Incorrect contents:**
```yaml
version: 2.0.0-nightly.256348.6e1b66
releaseDate: '2021-07-02T17:52:53.628Z'
githubArtifactName: …
```

fix: Updated mac .yml generation script

---

Composer/packages/client/src/components/AddRemoteSkillModal/CreateSkillModal.tsx
Composer/packages/lib/shared/src/skillsUtils/index.ts

1) When a .zip is parsed, but the .json manifest is not found, display the exception
2) When checking schema compat, check just the version and not the entire schema path
fixes #8260
closes https://github.com/microsoft/BotFramework-Composer/issues/8260

fix: Ensure manifest.json not found in zip displays error

---

Composer/packages/tools/language-servers/language-understanding/src/LUServer.ts

closes #8215 
In this PR, Lu editor would be capable to suggest entities defined in a imported lu file.
For example:
There is 3 entities defined in common.en-us.lu
```
@ ml myname
@ ml yourname
@ ml testExpr
```
In current lu file, it could suggest both imported entities and entities defined in the current file:

fix: Add suggestion for imported entities in Lu editing

---

extensions/azurePublish/src/node/provision.ts

log error message on final retry when "app create" or "add password" fails, assuming its an error from the Azure Graph API that returns error.message
refs #8249, #8283

fix: log error message on final retry when "app create" or "add password" fails

---

extensions/azurePublish/src/node/schema.ts

add `luisResource` to the default schema for Azure Publishing
fixes #8244

fix: luisresource missing from import

---

Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx
Composer/packages/client/src/plugins/api.ts
Composer/packages/extension-client/src/hooks/usePublishApi.ts
extensions/azurePublish/src/components/api.tsx
extensions/azurePublish/src/components/azureProvisionDialog.tsx
extensions/azurePublish/src/node/index.ts

AzurePublish extension was always adding luis and qna as optional resources instead of required resources in the provision flow regardless of the underlying bot needing LUIS or QNA.
There is already a selector in client recoil state that does the parsing to determine whether LUIS/QNA are required in the current bot files (`allRequiredRecognizersSelector`)
This PR adds an accessor function for `allRequiredRecognizersSelector` that can be called through the Publish Plugin API such that the plug in can correctly categorize whether or not LUIS and QNA are optional.
fixes #6775

fix: categorizing LUIS and QNA resources correctly as required or optional in provision flow

---

Composer/packages/client/src/App.tsx
Composer/packages/client/src/components/Notifications/useSurveyNotification.ts
Composer/packages/client/src/constants.tsx
Composer/packages/client/src/recoilModel/atoms/appState.ts
Composer/packages/client/src/recoilModel/dispatchers/application.ts

The HaTS survey wasn't saving the time it was taken to local storage, which was causing the "has it been long enough" check to always be true. Also, the useSurveyNotification hook wasn't recalculating eligibility, so if you were eligible once, you were eligible forever and the box would keep appearing.
#minor

fix: correctly update time survey was taken

---

Composer/packages/tools/language-servers/language-understanding/src/LUServer.ts

closes #8295 
For higher level imports, the LU editor now is able to suggest all entities defined. 
For example, in form dialog:
Another example:
Empty.en-us.lu imports test.en-us.lu, test.en-us.lu imports compact2.en-us.lu and level2.en-us.lu, level2.en-us.lu imports level3.en-us.lu. Once user editing in Empty.en-us.lu, the editor can suggest all entities defined in all imported files.

fix: Add support of suggesting all entities in multiple import levels

---

extensions/azurePublish/src/components/api.tsx

The required LUIS or QnA needs to be filtered to the project being provisioned.
fixes #6775
N/A

fix: Filter recognizers to project ID

---

Composer/packages/client/src/pages/design/SideBar.tsx
Composer/packages/lib/indexers/src/dialogIndexer.ts

**root cause**
1.  indexer doesn't check undefined value when finding the referred dialogs
2.  the warning use the children as the referred dialogs, but actually we need the parent 
**fix**
1. check the undefined value
2. find the correct references to a dialog
Closes #8342

fix: Dialog deletion warning shows undefined when removing a dialog without any callers

---

Composer/packages/client/src/components/ManageService/ManageService.tsx
Composer/packages/client/src/components/QnA/CreateQnAModal.tsx
Composer/packages/client/src/components/QnA/ReplaceQnAFromModal.tsx

Several modal components were firing API calls to fetch Azure subscriptions even if they were not visible on screen. This PR adds a check for the visibility to ensure we aren't doing unnecessary fetches.
This will prevent weird popups from appearing when a token expires.
fixes #8367

fix: before fetching subscriptions, ensure modal is visible

---

Composer/packages/lib/shared/src/settings.ts
Composer/packages/types/src/publish.ts
extensions/azurePublish/src/node/deploy.ts
extensions/azurePublish/src/node/schema.ts

Added field to the publish profile for customers with ASE deployments to use to set the custom ASE SCM host domain.
fixes #8400

fix: Support optional scm host domain for ASE

---

Composer/packages/client/src/components/ErrorBoundary.tsx

This will cause all ResizeObserver errors to get swallowed by the window's custom error handler. These events are harmless and have been leading to issues.
close #8361

fix: silently ignore ResizeObserver errors

---

Composer/packages/adaptive-flow/src/adaptive-flow-editor/renderers/NodeWrapper.tsx
Composer/packages/adaptive-form/src/components/Comment.tsx
Composer/packages/adaptive-form/src/components/ExpandableText.tsx
Composer/packages/adaptive-form/src/components/__tests__/Comment.test.tsx
Composer/packages/client/src/pages/design/createDialogModal.tsx
Composer/packages/lib/shared/src/dialogFactory.ts

Updates various things found during the bug bash:
- Correctly wraps long words
- Preserves whitespace in the tooltip on the flow
- Uses the dialog description as a comment when creating a new dialog
- Updates the initial experience when creating a comment to be more user-friendly
fixes #8333 
fixes #8331 
closes #8328
closes #8327

fix: UX/UI updates to comments

---

Composer/packages/client/__tests__/pages/design/Design.test.tsx
Composer/packages/client/src/pages/design/VisualPanelHeader.tsx

set breadcrumb width to (85%, 15%), introduced in #7720
close #8361

fix: breadcrumb resizing issue

---

Composer/packages/client/src/pages/home/Home.tsx

Replaces the no-longer-current "open the product tour" text on the home screen when there are no projects loaded with a rephrased link to starting a new bot.
closes #8337

fix: rephrase no-recent-bots box

---

Composer/packages/client/src/components/DropdownWithAllOption/DropdownWithAllOption.tsx
Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticFilters.tsx
Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsTabContent.tsx
Composer/packages/client/src/recoilModel/atoms/appState.ts
Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts

This PR
1. Resets the show warning and show error states in the DebuPane to true when swapping bots
2. When a bot project is opened it defaults to "All" option to show errors and warnings across bots. When a new skill is added to the solution it sets it again to "All" option.
Fixes #8345

fix: Problems pane reset

---

Composer/packages/client/src/pages/design/exportSkillModal/content/Description.tsx

fix: can't connect to remote skill: "Cannot read property 'default' of undefined"
manifest content endpoints have an empty object item
initial set endpoints is empty array.
closes #8479

fix: can't connect to remote skill: "Cannot read property 'default' of undefined"

---

Composer/packages/extension/package.json
Composer/packages/server/package.json
Composer/yarn.lock
extensions/packageManager/yarn.lock

Compliance fix - remove dependencies on tar 6.1.0 and below, all tar deps resolve to 6.1.6 now
#minor

fix: Update Orchestrator core and extensions Tar dependency to 6.1.6

---

extensions/azurePublish/src/node/deploy.ts

Fix how we form the publishEndpoint. Check for undefined or empty scmHostDomain value.
Cause of the bug: the nullish coalescing operator (`??`) returns falsey for `undefined` but returns truthy for empty strings. All "Import Existing Resources" profiles include `scmHostDomain: ''` now so the expression would result in an invalid publishEndpoint URI.
fixes #8489

fix: build publishEndpoint should check for empty string and undefined

---

Composer/packages/adaptive-form/src/components/AdaptiveForm.tsx

**Root cause**
Form editor will use designer id to generate the < SchemaField /> id. And the < Dropdown /> will use the root id to generate some other tag id. Then < Dropdown /> will use document.querySelector to search some ids. But if the designerid in the pattern `root[designerid]` is start with digit, composer will throw syntax error. It's related to the querySelector and the css selector id
**Fix**
use '-' to replace the '[]'
closes #8545
closes #8515

fix: <Dropdown/> syntax error in form editor

---

Composer/packages/client/src/components/AppComponents/SideBar.tsx
Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
Composer/packages/client/src/components/Header.tsx
Composer/packages/client/src/components/NavItem.tsx
Composer/packages/client/src/utils/pageLinks.ts

Add styling to the Composer header and left nav that resembles PVA v1.0, for purposes of next week's demo.
Header
- Updated background color to the PVA teal
- Updated font style of text
- Hid BotController buttons
- Added placeholder Office365 waffle icon (no onClick handler)
- Added "PVA 2.0" prefix to bot name
Left nav:
- Adjusted nav item styles and colors
- Changed nav item logo and name from Create to Topics
- Changed nav item logo for Publish to match PVA
- Changed nav item name from Configure to Manage
- Kept other Composer nav items there but in disabled state (pending feedback; could hide/replace with PVA placeholders)
Figma: https://www.figma.com/file/frQviquVRVWnyr1JcAxrAz/Authoring-PVA-2.0?node-id=1238%3A7309
Left nav collapsed:
Left nav expanded:

PVA V2 Demo: Apply PVA styling to header and left nav

---

Composer/packages/client/src/components/Toolbar.tsx
Composer/packages/client/src/pages/design/CommandBar.tsx

- Collapse Edit dropdown in CommandBar over to individual action buttons and hide dropdowns
- Apply styling for buttons (including hover state)
Figma: https://www.figma.com/file/frQviquVRVWnyr1JcAxrAz/Authoring-PVA-2.0?node-id=1196%3A2168
Hover state:

PVA v2 Demo: Collapse Edit dropdown to individual action buttons

---

Composer/packages/client/src/components/Header.tsx
Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
Composer/packages/client/src/components/WebChat/utils/conversationService.ts
Composer/packages/client/src/pages/design/CommandBar.tsx
Composer/packages/server/src/controllers/project.ts
Composer/packages/server/src/router/api.ts
Composer/packages/server/src/services/project.ts

Adds the ability to talk to the current PVA bot via Web Chat.
**Important notes:**
To make this work you must do the following:
1. Get an access token from the PVA portal and paste it into Local Storage via the dev tools window under the key `PVA-2-DEMO-TOKEN`
2. Add the PVA bot's metadata to the bot's entry in the project location map in `data.json`:

Added PVA web chat integration

---

Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx
Composer/packages/client/src/components/Toolbar.tsx
Composer/packages/client/src/pages/design/DesignPage.tsx
Composer/packages/client/src/pages/design/VisualPanelHeader.tsx
Composer/packages/client/src/pages/design/styles.ts
Composer/packages/client/src/recoilModel/atoms/appState.ts

PVA v2 Demo styling updates for a few components:
- Replaced "Add" and "Filter" buttons in project tree header with header title
- Added ability to expand / collapse the project tree using "X" button in project tree header and an expand button in the design Toolbar.
- Removed the <Split> component for the demo; note this means that the tree width cannot be resized.
- Replaced the breadcrumb header with a simple label indicating the dialog name.
https://www.figma.com/file/frQviquVRVWnyr1JcAxrAz/Authoring-PVA-2.0?node-id=1240%3A7582

PVA V2 Demo - Project tree expand/collapse

---

extensions/localPublish/src/index.ts

There is a seemingly random occurring error in Composer with the message 'cannot read property stdout of undefined'. 
The issue is traced down to a call within the local publish extension where Composer does not null check a Process object prior to calling functions on it and there are times in which this function is called with a null process obj. 
Testing indicates that a simple null check fixes the issue and enables true errors to surface for bots that are erroneous as well as working bots to continue working without the error popping up as well.
fixes #8547 
fixes #8564

fix: Add null check to avoid asserting on undefined process obj

---

Composer/packages/client/src/App.tsx
Composer/packages/server/src/controllers/auth.ts
Composer/packages/server/src/router/api.ts
extensions/pvaStorage/src/pvaBotClient.ts

This PR includes the following changes:
- When retrieving the OBI content from PVA, we now omit the content snapshot so we always get the most up-to-date assets (fixes failures on subsequent saves)
- The PVA token injected into the server via `process.env.PVA_DEMO_TOKEN` is now plumbed into the client and stored in local storage to be used by Web Chat

Added some fixes to the PVA storage extension for the demo

---

Composer/packages/form-dialogs/src/components/property/PropertyCardContent.tsx

fixes #8627 
The issue was that the auto-field creation from templates was filtering out properties it should have included.

fix: enumerations were not displayed.

---

Composer/packages/electron-server/package.json
releases/2.1.1.md

- feat: Add ability to configure template feed ([#8553](https://github.com/microsoft/BotFramework-Composer/pull/8553)) ([@pavolum](https://github.com/pavolum))
- feat: support remote $refs in dialog schema. ([#8456](https://github.com/microsoft/BotFramework-Composer/pull/8456)) ([@a-b-r-o-w-n](https://github.com/a-b-r-o-w-n))
- Added support to import / publish flows for PVA GCC High env ([#8554](https://github.com/microsoft/BotFramework-Composer/pull/8554)) ([@tonyanziano](https://github.com/tonyanziano
- fix: Add null check to avoid asserting on undefined process obj ([#8587](https://github.com/microsoft/BotFramework-Composer/pull/8587)) ([@pavolum](https://github.com/pavolum))
- fix: <Dropdown/> syntax error in form editor ([#8560](https://github.com/microsoft/BotFramework-Composer/pull …

release: 2.1.1

---

Composer/packages/lib/indexers/src/validations/expressionValidation/validation.ts

**Root cause**
In the current design, if the expression contain string type ,we don't parse the expression. And the the return type use binary number to store. But indexer only use the first element of the types and use "===" to check the type. we need to check all types in the array and use bit operation.
**Fix**
check all types and do bit operation
closes #8472

fix: the Value field of a Trace Activity is throwing warnings

---

Composer/packages/lib/code-editor/src/JsonEditor.tsx
extensions/azurePublish/src/node/schema.ts

Allows the json editor to consume json schemas to validate data.
refs #8523

fix: use object url for json editor schema

---

Composer/packages/electron-server/scripts/installOneAuth.js

This PR bumps the OneAuth library version from 1.15.0 to 1.36.0 which includes a lot of bug fixes. One of which caused an IcM to be opened on Composer.
Fixes #8708

fix: Bumped OneAuth version to 1.36.0

---

Composer/packages/ui-plugins/schema-editor/src/schema.ts
Composer/packages/ui-plugins/select-dialog/src/DialogOptionsField.tsx
Composer/packages/ui-plugins/select-dialog/src/SelectDialogMenu.tsx
Composer/packages/ui-plugins/select-dialog/src/__tests__/DialogOptions.test.tsx
azure-pipelines.yml

The dialog schemas are indexed by dialog id which is the file name for composer dialogs and the display name for topics. The dialog data references the topics internal guid and was failing to find the dialog schema with this id.

fix: show PVA topic's dialog options

---

Composer/packages/lib/indexers/src/utils/luUtil.ts

fixes #8475 
Change luis authoring a prebuilt entity name reserved error to warning.
.

fix: change luis editor prebuilt entity error to warn

---

Composer/packages/client/src/pages/botProject/AllowedCallers.tsx
Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx
Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
Composer/packages/client/src/pages/botProject/RuntimeSettings.tsx
Composer/packages/client/src/pages/botProject/SkillBotExternalService.tsx
Composer/packages/client/src/pages/botProject/SkillHostEndPoint.tsx
Composer/packages/client/src/pages/botProject/adapters/AdapterSection.tsx
Composer/packages/client/src/pages/botProject/shared/SettingTitle.tsx
Composer/packages/client/src/pages/botProject/styles.ts
Composer/packages/lib/ui-shared/src/components/SectionTitle.tsx
Composer/packages/lib/ui-shared/src/components/index.ts
extensions/azurePublish/src/components/ChooseProvisionAction.tsx
extensions/azurePublishNew/src/components/provisioningWizards/steps/CreateResourceInstructionsStep.tsx
extensions/azurePublishNew/src/components/provisioningWizards/steps/HandOffInstructionsStep.tsx
extensions/azurePublishNew/src/components/provisioningWizards/steps/ImportInstructionsStep.tsx

Add accessible headings in place of visual headings to improve navigation when using a screen-reader. Added for Configure and Create publishing profile pages.
Added a shared component to handle titles as well.
Note: made `extensions/azurePublishNew` changes so it stays consistent to `extensions/azurePublish`, but wasn't able to test `extensions/azurePublishNew` changes. Even after enabling the publishing method on client side, it still doesn't render new UI reporting 404 errors back. Appreciate any help here.
- [VSTS 70096](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70096)
- [VSTS 70110](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70110)

fix: a11y add headings for Configure and Create publishing profile pages

---

Composer/packages/client/src/components/CreationFlow/FileSelector.tsx

Adds a missing heading title for the 4th column on Create a bot project screen, files section.
- [VSTS 70096](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70096)

fix: a11y add missing heading title for Create a bot project file section

---

Composer/packages/client/src/index.css

Fix anchor focus ring color in Electron by overriding user-agent specified color with `#000000`. This makes anchor focus outline color consistent across browsers as well.
We use plain anchors in different places. To me this seems the best option to fix issues bellow.
[VSTS 70089](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70089)
[VSTS 70440](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70440)

fix: a11y anchor focus ring color contrast in electron

---

Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
Composer/packages/client/src/pages/publish/BotStatusList.tsx

Fixes the following keyboard navigation issues:
- On "Configure your bot" screen, "Development Resources" tab keyboard focus gets lost after closing modals. The issue happens because modal trigger buttons get disabled when "Set up Language Understanding" and "Set up QnA Maker" modals are opened. Removed modal trigger buttons disabling logic to fix the issue.
- On "Publish your bots" screen, "Publish" tab, "Publish target" drop-down causes navigation to the "Publishing profile" tab when it receives a focus event. The issue is caused by Dropdown component triggering `onChange` handler when keyboard focus received. Fixed by ignoring focus events for the particular "Manage profiles" drop-down item. Turned the drop-down to controlled one, so it always follows `item.publishTarget` selection …

fix: a11y keyboard interactions for configure and publish screens

---

Composer/packages/adaptive-form/src/components/FieldLabel.tsx
Composer/packages/adaptive-form/src/components/__tests__/FieldLabel.test.tsx
Composer/packages/client/__tests__/components/BotRuntimeController/publish-luis-modal.test.tsx
Composer/packages/client/src/components/BotRuntimeController/publishDialog.tsx
Composer/packages/client/src/components/CreationFlow/DefineConversation.tsx
Composer/packages/client/src/components/FieldWithCustomButton.tsx
Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx
Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
Composer/packages/client/src/pages/botProject/SkillBotExternalService.tsx
Composer/packages/client/src/pages/botProject/SkillHostEndPoint.tsx
Composer/packages/client/src/pages/botProject/create-publish-profile/ProfileFormDialog.tsx
Composer/packages/client/src/pages/botProject/styles.ts
Composer/packages/client/src/pages/design/exportSkillModal/content/SelectProfile.tsx
Composer/packages/client/src/pages/setting/app-settings/SettingDropdown.tsx
Composer/packages/client/src/pages/setting/app-settings/TemplateFeedForm.tsx
Composer/packages/client/src/pages/setting/app-settings/styles.ts
Composer/packages/client/src/styles.ts
Composer/packages/form-dialogs/src/components/common/HelpTooltip.tsx
Composer/packages/lib/code-editor/src/components/HelpIconTooltip.tsx
Composer/packages/lib/code-editor/src/components/ItemWithTooltip.tsx
Composer/packages/lib/ui-shared/src/components/Field.tsx
Composer/packages/lib/ui-shared/src/components/HelpTooltip.tsx
Composer/packages/lib/ui-shared/src/components/SectionTitle.tsx
Composer/packages/lib/ui-shared/src/components/__tests__/Field.test.tsx
Composer/packages/lib/ui-shared/src/components/index.ts

This PR contains changes to achieve the following goals:
- Make labels to be linked with inputs in a way FluentUi does it
- Make help tooltips to be accessible via keyboard and able to be read via screen-readers
- Make field components usage more consistent across the code base
To achieve these goals the following changes were made:
- Added own `TextField` and `DropdownField` shared components extending FluentUi corresponding components: mainly adding a help tooltip properties
- Implemented `useLabelWithTooltip` hook to be utilized in extended components 
- Added `HelpTolltip` shared component to be used in place of current tooltip with icon use and the new components as well
- Refactored codebase to utilize introduced components
- [VSTS …

a11y: Make labels and help tooltips more accessible

---

Composer/packages/adaptive-form/src/components/SchemaField.tsx

fix: reset to default or const when field value is undefined

---

Composer/packages/client/src/recoilModel/dispatchers/publisher.ts

This fixes an issue where the Orchestrator multi-language settings can disappear when the bot is using locales that are not supported by LUIS. 
The `dialogsWithLuProviderSelectorFamily` selector needs to be used to provide the `luProvider` property on the dialog. 
Without this property, `botindexer::filterLUISFilesToPublish` will always filter languages based on what LUIS supports.  When using Orchestrator, we don't want this filtering to occur, since Orchestrator supports all the languages that the Composer UI supports. 
Internal IcM. fixes #minor

fix: Make sure Orchestrator languages are not filtered when publishing

---

Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx
Composer/packages/lib/code-editor/src/components/toolbar/ToolbarButtonMenu.tsx
Composer/packages/lib/code-editor/src/hooks/useSearchableMenuListCallback.tsx
Composer/packages/lib/code-editor/src/lu/DefineEntityButton.tsx
Composer/packages/lib/code-editor/src/lu/hooks/useLabelingMenuItems.tsx

This improvements UX when navigating via keyboard through contextual menus and search/filter fields in the following ways:
- Search/filter is cleared on the first Escape key press, and gets closed on the second one
- When contextual menu is used with filter or search field, it respects arrows keys in addition to Escape key for toggling the menu.
These improvements resulted in the following changes:
- Swapped `onDismiss` for contextual menu items with `onMenuDismissed` since the later doesn't block the menu from being dismissed in contrast to the former.
- Added the logic to return focus back on filter blur action
- Refactored contextual menus hooks to avoid repeating code
- [VSTS 70101](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70101)
#minor

a11y: improve contextual menus and filtering

---

Composer/packages/adaptive-form/src/components/expressions/ExpressionSwitchWindow.tsx
Composer/packages/client/src/pages/botProject/BotProjectInfo.tsx
Composer/packages/lib/code-editor/src/components/toolbar/ToolbarButtonMenu.tsx

Fixes contrast ratio issues found for some of controls, making text contrast ratio above 4.5. See screenshots and linked bugs for more details
Switched some places to `neutralPrimary` for text color as it is the preferred text color to `black`.
- [VSTS 70114](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70114)
- [VSTS 70437](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70437)
- [VSTS 70442](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70442)
#minor

a11y: fix controls contrast ratio

---

Composer/packages/client/src/components/ProjectTree/treeItem.tsx

This fixes keyboard navigation issues with more button on Projects tree, More buttons are displayed for every parent containing active child, so the change makes consistent the ability to focus a button with button visibility. 
Updated tree focus styles as well to make focus indication more consistent.
- [VSTS 70106](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70106)
#minor

a11y: allow keyboard navigation for any tree item more button with active child

---

Composer/packages/adaptive-flow/src/adaptive-flow-editor/renderers/NodeMenu.tsx
Composer/packages/lib/ui-shared/src/components/IconMenu.tsx

A minor refactor to improve node menu focus styles.
- [VSTS 70423](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70423)
#minor

a11y: fix node menu focus styles

---

Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx

This fixes the following issues:
- Unable to go through filtered tree items via keyboard as the filter immediately gets closed after a blur event
- Narrator doesn't announce search results and related instructions for filter
The former issue is fixed by preserving the search query in case the query is not empty. If the query is empty blur causes the filter to close. I'd like to note that the filtered state is preserved until a user explicitly clears the search query. To me, this should be the desired behavior.
The later issue has more to note about:
- Refactored announcement to use `Announced` component from FluentUI built-ins. Tested with NVDA and it works.
- Since Narrator still has issues with announcing status/alert roles used by the Announced component, added an explicit …

a11y: improve tree filtering keyboard navigation and announcement

---

Composer/packages/client/src/components/MultiLanguage/AddLanguageModal.tsx

This  includes the following changes:
- Link search input with label
- Add announcement for search results
- Add announcement for checked languages
- Arrange checkboxes into the list for better screen-reader user experience
- Add a workaround for narrator to read announcements under some circumstances
- [VSTS 70109](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70109)
- [VSTS 70102](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70102)
- [VSTS 70111](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70111)
#minor

a11y: Improve Copy content for translation modal

---

Composer/packages/electron-server/package.json
releases/2.1.2.md

#minor
Merge 2.1.2 release branch into main

chore: Merge 2.1.2 release branch into main

---

Composer/packages/client/src/pages/botProject/AllowedCallers.tsx
Composer/packages/client/src/pages/botProject/adapters/ABSChannels.tsx

Fixed the following issues with Settings controls:
- Make Bot allowed caller controls more descriptive so screen reader users can distinguish controls from different rows
- Fix empty label for the Channels publishing profile dropdown
- Fix keyboard interactions for the Channels publishing profiles dropdown
- [VSTS 70444](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70444)
- [VSTS 70446](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70446)
- [VSTS 70449](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70449)
#minor

a11y: fix reamining setting controls empty labels

---

Composer/packages/server/src/server.ts

In prod, we were incorrectly passing the `port` to `DLServerContext.getInstance` before checking if that port was available. This PR ensures that all references to `port` are used after we get the correct port. 
Fix #8956

fix: Fix incorrect port getting passed to DLServerContext.getInstance

---

extensions/packageManager/src/pages/Library.tsx

When installing a package, in case of a network failure, the error passed to the `importComponent` catch block doesn't contain `err.response.status` field, so it throws a new error preventing the modal from being closed.
The PR adds an optional chaining operator for `error` to prevent the issue.
The PR should fix the following a11y bug as well. Can't check this as narrator started to crash in this place after the fix (looks like a narrator bug)
- [VSTS 70520](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70520)
#minor

fix: Packages stuck at "Installing package..." screen on network failure

---

Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
Composer/packages/client/src/components/BotRuntimeController/BotControllerMenu.tsx
Composer/packages/client/src/pages/design/DebugPanel/DebugPanel.tsx

This fixes the following issues
- Focus stucks on bot controller menu when navigating with keyboard
- Focus doesn't get to the opened debug panel when navigating to run details
- No region aria provided for debug pane
The following changes were made to address these issues:
- Replace Callout component with FocusTrapCallout to handle focus inside the menu correctly
- Add an effect to place focus to the debug panel when panel gets opened
- Configure FocusTrapCallout to allow focusing elements outside of the callout
- Add required aria attributes to the debug panel root
- [VSTS 70527](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70527)
#minor

a11y: improve bot controller keyboard handling

---

Composer/packages/client/src/components/CellFocusZone.tsx
Composer/packages/client/src/components/EditableField.tsx
Composer/packages/client/src/hooks/useAfterRender.ts
Composer/packages/client/src/pages/knowledge-base/styles.ts
Composer/packages/client/src/pages/knowledge-base/table-view.tsx
Composer/packages/client/src/pages/language-generation/table-view.tsx
Composer/packages/client/src/pages/language-understanding/styles.ts
Composer/packages/client/src/pages/language-understanding/table-view.tsx

The PR aims to address the following issues found on pages with lists containing nested forms, including: "Bot Responses", "Knowledge (QnA)" and "Knowledge Base" pages.
Here is the list of issues addressed:
- Unable to navigate to fields nested in DetailsList cells using keyboard
- Some buttons are hidden while navigating via keyboard ("Clear field" button, "Add new" item button)
- Save via keyboard Enter key doesn't work under several circumstances
- Shift+Enter should persist caret position and the field in focus while adding a new line
- Visual focus indication for focused fields works unstable
- No error announcement
- No way to blur selected fields when the focus is on the DetailsList cell field
Highlights on changes made:
- Implement a CellFocusZone component to handle focus in …

a11y: fix table-forms keyboard navigation

---

Composer/packages/client/src/components/CreationFlow/CreateOptions.tsx

Opening multiple modals simultaneously confuses screen readers. This fixes the issue by allowing only one modal to be showed at the same time.
- [VSTS 70108](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70108)
The `AzureBotDialog` is placed beneath "Select the template" dialog (notice double dark overlay)
#minor

a11y: show one modal at once for bot creation flow

---

Composer/packages/electron-server/electron-builder-config.json
Composer/packages/electron-server/package.json
Composer/packages/electron-server/src/appMenu.ts
Composer/packages/electron-server/src/electronWindow.ts
Composer/packages/electron-server/src/splash/splashScreen.ts
Composer/yarn-berry.lock
Composer/yarn.lock

Test PR to test electron upgrade

chore: update electron

---

Composer/packages/adaptive-form/src/components/fields/BooleanField.tsx
Composer/packages/adaptive-form/src/components/fields/OpenObjectField/ObjectItem.tsx
Composer/packages/adaptive-form/src/components/fields/OpenObjectField/OpenObjectField.tsx
Composer/packages/adaptive-form/src/components/fields/SelectField.tsx
Composer/packages/adaptive-form/src/components/fields/StringField.tsx

These fields are visually indicated as required. so add `aria-required` attribute for screenreaders.
Alternative approach is might be in using a `required` property. It has more things to fix though:
- Need to remove double asterisk indication
- When placed in a native field, native tooltip pops-up which can't be customized
- [VSTS 70102](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70102)
#minor

a11y: Add aria-required attribute to Form Editor required fields

---

Composer/packages/client/src/pages/botProject/create-publish-profile/ProfileFormDialog.tsx

Aria label should start from visible content. This PR fixes the occurrence pointed out in the linked bug.
- [VSTS 70094](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70094)
#minor

a11y: fix aria-label content

---

Composer/packages/client/src/components/ProjectTree/ExpandableNode.tsx
Composer/packages/client/src/components/ProjectTree/treeItem.tsx

This improves aria for the Project Tree control.
Includes the following changes:
- Remove redundant aria-label causing two elements in the chain to have the same name
- Remove redundant tabIndex and move keyboard handler to the place where the keyboard event happens
- Make aria-labels to follow the rule: visible content goes first in the label
- [VSTS 70524](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70524)
#minor

a11y: fix project tree roles and aria

---

Composer/packages/adaptive-form/src/components/fields/IntellisenseFields.tsx
Composer/packages/adaptive-form/src/components/fields/StringField.tsx
Composer/packages/extension-client/src/types/form.ts
Composer/packages/intellisense/src/components/CompletionElement.tsx
Composer/packages/intellisense/src/components/CompletionList.tsx
Composer/packages/intellisense/src/components/Intellisense.tsx

The PR adds accessibility properties for the intellisense component, wires them with input components and fixes some observations.
List of changes:
- Added `aria` attributes set into `Intellisense` component, so it to be passed down to any input rendered
- Updated fields. where it makes sense. to include a11y parameters passed by Intellisense
- Added scrollIntoView for CompletionElement to ensure the selected element is in the view
- Refactored CompletionList a11y properties. Now list has a listbox role when showing suggestions
- [VSTS 70456](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70456)
#minor

a11y: add support for intellisense

---

Composer/packages/lib/code-editor/src/components/toolbar/FieldToolbar.tsx
Composer/packages/lib/code-editor/src/components/toolbar/ToolbarButtonMenu.tsx
Composer/packages/lib/code-editor/src/components/toolbar/__tests__/ToolbarButtonMenu.test.tsx

Add missing labels to icon-only buttons inside of the Code Editor toolbar
- [VSTS-70425](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70425)
#minor

a11y: add labels for editor toolbar

---

azure-pipelines.yml

Fixes #minor
Implementation of yarn v3 resulted in Component Governance analysis failing to find security vulnerabilities: CG does not handle the new v3 yarn-berry.lock files.
Add a script to generate imitation yarn v1 yarn.lock files just before CG analysis runs.

build: Fix Component Governance in Composer DevOps pipeline

---

Composer/packages/server/package.json
Composer/packages/server/src/directline/utils/webSocketServer.ts
Composer/packages/server/src/locales/en-US.json
Composer/packages/server/src/server.ts
Composer/yarn-berry.lock
extensions/azurePublish/yarn-berry.lock
extensions/localPublish/package.json
extensions/localPublish/src/index.ts
extensions/localPublish/src/runtimeLogServer.ts
extensions/localPublish/yarn-berry.lock

- Ensure we use the latest `portfinder` version available
- Adjust default start port for every `portfinder` call, so if two calls happen simultaneously, they don't try to acquire the same port
- Add logging for `portfinder` errors and port used before listening
- If `portfinder` fails, try using preferred port, letting listen to fail and provide more sensible error
#minor

fix: improve portfinder usage

---

Composer/packages/client/config/env.js

The current revision is missing in development environment. The command provided gives the following error on my machine:
```
fatal: Needed a single revision
```
In addition the output is null when `stdio` is set to `"ignore"`.
Accessibility testers now use Composer built from sources for testing on the web. This fix will help them reporting current revision correctly.
#minor

fix: version hash display in development builds

---

Composer/packages/adaptive-form/src/components/AddButton.tsx
Composer/packages/adaptive-form/src/components/FieldLabel.tsx
Composer/packages/adaptive-form/src/components/fields/OpenObjectField/OpenObjectField.tsx
Composer/packages/client/src/components/CreationFlow/FileSelector.tsx
Composer/packages/client/src/components/MultiLanguage/AddLanguageModal.tsx
Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx
Composer/packages/client/src/components/QnA/CreateQnAFromUrl.tsx
Composer/packages/client/src/components/QnA/EditQnAFromScratchModal.tsx
Composer/packages/client/src/components/QnA/EditQnAFromUrlModal.tsx
Composer/packages/client/src/components/TriggerCreationModal/TriggerCreationModal.tsx
Composer/packages/client/src/pages/botProject/BotLanguage.tsx
Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx
Composer/packages/client/src/pages/home/CardWidget.tsx
Composer/packages/intellisense/src/components/Intellisense.tsx
Composer/packages/lib/code-editor/src/hooks/useEditorToolbarPopExpandItem.tsx
Composer/packages/lib/code-editor/src/hooks/useNoSearchResultMenuItem.tsx
Composer/packages/lib/ui-shared/src/components/ProvisionHandoff/ProvisionHandoff.tsx
Composer/packages/server/src/locales/en-US.json
extensions/azurePublish/yarn-berry.lock
extensions/azurePublishNew/yarn-berry.lock
extensions/packageManager/yarn-berry.lock

Fixes [75910](https://fuselabs.visualstudio.com/Composer/_queries/edit/75910)
<details>
<summary>Screenshot</summary>
</details>
Fixes [75891](https://fuselabs.visualstudio.com/Composer/_queries/edit/75891)
<details>
<summary>Screenshot</summary>
</details>
Fixes [75867](https://fuselabs.visualstudio.com/Composer/_queries/edit/75867)
<details>
<summary>Screenshot</summary>
</details>
Fixes [75868](https://fuselabs.visualstudio.com/Composer/_queries/edit/75868)
List of changes:
- Add list and list-item roles for the Bot Languages list
- Add aria-labels for the list
- Add keyboard navigation support for the list
- Add focus state indication for list-items
- Show list-item action buttons on list item focus
<details>
<summary>Screenshot</summary>
</details>
Fixes …

a11y: fix August pass issues

---

Composer/packages/client/src/pages/about/About.tsx
Composer/packages/client/src/pages/about/styles.js
Composer/packages/server/src/locales/en-US.json
Composer/packages/server/src/locales/it.json

This adds requested accessibility compliance link to Composer About page.
[76008](https://fuselabs.visualstudio.com/Composer/_queries/edit/76008/)
The link is only visible on Italian locale:
English and other locales remain untouched:
#minor

a11y: add italy compliance link

---

Composer/packages/adaptive-form/src/components/CollapseField.tsx
Composer/packages/client/src/components/EditableField.tsx
Composer/packages/client/src/components/FieldWithCustomButton.tsx
Composer/packages/client/src/pages/knowledge-base/styles.ts
Composer/packages/lib/code-editor/src/components/toolbar/PropertyTreeItem.tsx
Composer/packages/lib/code-editor/src/components/toolbar/ToolbarButtonMenu.tsx
extensions/azurePublish/src/components/azureProvisionDialog.tsx
extensions/azurePublish/yarn-berry.lock

Fixes [75832](https://fuselabs.visualstudio.com/Composer/_workitems/edit/75832/)
<details>
<summary>Screenshots</summary>
</details>
Fixes [75830](https://fuselabs.visualstudio.com/Composer/_workitems/edit/75830/)
<details>
<summary>Screenshots</summary>
</details>
Fixes [75833](https://fuselabs.visualstudio.com/Composer/_workitems/edit/75833/)
<details>
<summary>Screenshots</summary>
</details>
Fixes [75854](https://fuselabs.visualstudio.com/Composer/_workitems/edit/75854/)
<details>
<summary>Screenshots</summary>
</details>
Fixes [75828](https://fuselabs.visualstudio.com/Composer/_workitems/edit/75828/)
<details>
<summary>Screenshots</summary>
</details>
#minor

a11y: more fixes for the last pass

---

Composer/packages/client/src/pages/design/styles.ts
Composer/packages/client/src/pages/publish/styles.ts
Composer/packages/client/src/pages/setting/SettingsPage.tsx

Follow-up PR improving reflow support for Publish and Settings.
- Now settings have proper height
- Can open debug panel on Publish page
#minor

a11y: minor reflow improvements

---

Composer/packages/adaptive-flow/src/adaptive-flow-editor/utils/cursorTracker/tabMove.ts
Composer/packages/adaptive-form/src/components/CollapseField.tsx
Composer/packages/client/src/pages/design/SideBar.tsx
Composer/packages/lib/code-editor/src/components/toolbar/__tests__/ToolbarButtonMenu.test.tsx
Composer/packages/lib/code-editor/src/hooks/useSearchableMenuListCallback.tsx
Composer/packages/lib/code-editor/src/lu/__tests__/InsertEntityButton.test.tsx
extensions/azurePublish/yarn-berry.lock

- a11y: announce search inside menus 
Fixes [75831](https://fuselabs.visualstudio.com/Composer/_workitems/edit/75831/)
<details>
<summary>Screenshot</summary>
</details>
- a11y: announce trigger removal 
Fixes [75771](https://fuselabs.visualstudio.com/Composer/_workitems/edit/75771/)
<details>
<summary>Screenshot</summary>
</details>
- a11y: improve designer tab handling 
Fixes [70108](https://fuselabs.visualstudio.com/Composer/_workitems/edit/70108)
<details>
<summary>Screenshots</summary>
</details>
#minor

a11y: fix remaining issues

---

.github/workflows/docker.yml
Composer/packages/client/src/components/WebChat/WebChatPanel.tsx
Composer/packages/client/src/components/WebChat/utils/conversationService.ts
Composer/packages/client/src/constants.tsx
Composer/packages/electron-server/src/main.ts
Composer/packages/server/src/controllers/publisher.ts
Composer/packages/server/src/directline/store/dlServerState.ts
Composer/packages/server/src/directline/utils/webSocketServer.ts
Composer/packages/server/src/server.ts
Composer/packages/server/src/settings/env.ts
Dockerfile
extensions/localPublish/src/index.ts
extensions/localPublish/src/runtimeLogServer.ts

Bind composer server to localhost unless the host is specified by `COMPOSER_HOST` environment variable. The variable can be set to `0.0.0.0` to restore previous behavior for server builds only, (isn't supported in Electron currently).
#minor

fix: bind composer server to localhost

---

Composer/packages/integration-tests/cypress/integration/LuisDeploy.spec.ts
Composer/packages/integration-tests/cypress/support/commands.d.ts
Composer/packages/integration-tests/cypress/support/commands.ts
Composer/packages/integration-tests/cypress/support/index.ts

This fixes end-to-end tests for Composer and ensures `cy.request(...)` has CSRF token set.
#minor

fix: ensure CSRF token is passed through cy.request

---

extensions/package.json
extensions/scripts/build.js
extensions/yarn-berry.lock

Adds a typechecking step when building extensions to guard against type changes during package upgrades, etc.
#minor

build: add typechecking to extension build script

---

extensions/packageManager/src/components/LibraryList.tsx
extensions/packageManager/src/components/styles.ts
extensions/packageManager/src/pages/Library.tsx

Found a couple of regressions while testing Composer in package manager:
- The search item wasn't placed properly in command bar
- Virtual scrolling broke for packages list
#minor

fix: package manager visual regressions

---

Composer/packages/server/src/directline/middleware/__tests__/attachmentHandler.test.ts
Composer/packages/server/src/directline/middleware/attachmentHandler.ts
Composer/packages/server/src/middleware/logNetworkTraffic.ts

This PR fixes an issue when uploading an image file from Composer's WebChat and then accessing it through the `/v3/attachments/<attachment id>/views/original` endpoint failed on displaying it (saying `it cannot be displayed because it contains errors`).
**Detailed changes**
- Send only one value through the `Response.send` function.
- Support other data types than just JSON strings in the `logNetworkTraffic` file.
Fixes #9492
The following image shows both Emulator and WebChat working as expected.

fix: [#9492] Fix WebChat createGetAttachmentHandler image file serving

---

Composer/packages/lib/indexers/src/validations/expressionValidation/index.ts
extensions/azurePublish/yarn-berry.lock
extensions/azurePublishNew/yarn-berry.lock

This PR fixes the issue by adding a new way of indexing the values in the cache. It will store the type along with the values in the cache after checking for errors to avoid overwriting the data and saving unuseful information.
Fixes #9517
These images show the user sample and a Microsoft template working successfully with the new indexing.

fix: [#9517][CSS] PRO | COMPOSER | In <dialogName>.triggers[0].actions[0]: Text: alwaysPrompt the return type does not match

---

Composer/packages/client/src/App.tsx
Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
Composer/packages/electron-server/src/main.ts
Composer/packages/lib/code-editor/src/components/toolbar/__tests__/ToolbarButtonMenu.test.tsx
extensions/azurePublish/yarn-berry.lock
extensions/localPublish/src/index.ts

This reworks exit flow:
- Added exit indication and fixed client exit cycle (by @sw-joelmut)
- Reworked server exit functionality to account for platform specifics and enforce proper exit (by @OEvgeny)
fixes #9059

fix: rework app exit to account for running bots

---

Composer/packages/server/src/directline/middleware/__tests__/createBotFrameworkAuthentication.test.ts
Composer/packages/server/src/directline/middleware/createBotFrameworkAuthentication.ts

This PR fixes the `jwt.decode is not a function` error thrown after upgrading [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) dependency to version 9.
The reason for the failure was that, in version 9 of jsonwebtoken the decode method is enumerable and the import used in Composer only worked for non-enumerable properties.
We added an individual import for the _decode_ property and that solved the issue.
Fixes #9543
Here we can see a composer bot working in WebChat after the changes.

fix: [#9543] Composer does not recognize valid bearer token

---

Composer/packages/client/src/App.tsx
Composer/packages/client/src/recoilModel/parsers/lgWorker.ts
Composer/packages/client/src/recoilModel/parsers/types.ts
Composer/packages/client/src/recoilModel/parsers/workers/lgParser.worker.ts
Composer/packages/client/src/recoilModel/utils/mapOptimizer.ts

#minor
This PR reduces the memory usage when parsing the LgFiles ([lgParse.worker](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/client/src/recoilModel/parsers/workers/lgParser.worker.ts)) by adding a `MapOptimizer` to the `LgFilesCache`.
This optimizer consists of, based on a capacity limit, the process will start removing LgFile parse results to free up space from memory. Additionally, it takes into account all the references and relationships between other LgFiles.
> **Note**: The `MapOptimizer` capacity limit is set to store a maximum of 10 parsed LgFiles, this amount can be modified through code.
The following image shows loading 9 bot responses with the `MapOptimizer` capacity size of 3 (for testing purposes), seeing the improvement in memory usage.

fix: Optimize memory usage when parsing LgFiles

---

Composer/packages/electron-server/package.json
releases/2.1.3.md

- feat: allow to disable OneAuth Eugene Olonov
- feat: reflow improvements ([#9454](https://github.com/microsoft/BotFramework-Composer/pull/9454)) Eugene
- feat: extend CSRF token protection to all api routes ([#9422](https://github.com/microsoft/BotFramework-Composer/pull/9422)) Eugene
- fix: Optimize memory usage when parsing LgFiles ([#9614](https://github.com/microsoft/BotFramework-Composer/pull/9614)) Joel Mut
- fix: [#9528] Unable to add two PVA bot skills through bot framework composer with the option connect to a skill ([#9549](https://github.com/microsoft/BotFramework-Composer/pull/9549)) Cecilia Avila
- fix: rework app exit to account for running bots ([#9532](https://github.com/microsoft/BotFramework-Composer/pull/9532)) Eugene
- fix: yarn hashes for local pacakges dont match …

2.1.3 release

---

Composer/packages/client/public/index.html
Composer/packages/client/public/manifest.json

The HTML Page `<title>` did not match the spelling of the product.
I have simply updated the `Title` and the `Manifest` file so that publicly it will show `"Bot Framework Composer"` rather than previously (incorrectly) showing as `"BotFramework Composer"`
Closes #9716

fix: [#9716] correct page title and manifest
