microsoft/BotFramework-Composer

- Composer/packages/client/package.json
- Composer/packages/extensions/obiformeditor/package.json
- Composer/packages/lib/indexers/package.json
- Composer/yarn.lock
Some old version myget packages were deleted. 
So update all these to latest version.
Closes https://github.com/microsoft/BotFramework-Composer/issues/1526
closes https://github.com/microsoft/BotFramework-Composer/issues/1525
> update some dependencies' version

- .github/workflows/main.yml
> Ignore failures for e2e

- Composer/packages/server/src/server.ts
Include login.microsoft.com and *.botframework.com to allowed frame hosts.
refs #1521
> fix: update content security policy

- Composer/packages/client/package.json
- Composer/packages/lib/shared/package.json
- Composer/yarn.lock
Fixes an issue when building the app in docker.
Fixes #1566
> fix: add nanoid to shared package dependencies

- azure-pipelines.yml
Disable azure pipeline CI while I work on e2e tests in parallel
refs #1586
> ci: disable az pipeline

- Composer/Dockerfile
- Composer/yarn.lock
> fix: docker build

- Composer/packages/client/src/pages/design/styles.js
> chore: reduce form width to 400px

- Composer/packages/client/package.json
- Composer/yarn.lock
> chore: add browserslist to dependencies

- .github/workflows/main.yml
- Composer/yarn.lock
> ci: do not fail CI if coveralls step fails

- Composer/packages/server/assets/projects/RespondingWithCardsSample/ComposerDialogs/common/common.lg
> fix: fix minor LG ref syntax in CardSample

- CHANGELOG.md
- scripts/generate-changelog.js
> docs: update changelog

- .github/ISSUE_TEMPLATE/bot-framework-composer-bug.md
- .github/ISSUE_TEMPLATE/bot-framework-composer-feature-request.md
- .github/ISSUE_TEMPLATE/bot-framework-composer-other.md
- .github/PULL_REQUEST_TEMPLATE.md
Some hygiene on github issue & pull request templates.
* commented out instructional text
* remove redundant sections
* added 'Other' issue template
* fixed label in feature request
refs #1766
> chore: update github templates

- Composer/packages/extensions/obiformeditor/src/Form/fields/RecognizerField/InlineLuEditor.tsx
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
If this is a bug fix, please describe the root cause and analysis of this problem.
Fixes #1748 
> fix: avoid re-render tiggered by upper  state change

- Composer/packages/extensions/visual-designer/src/components/nodes/steps/DefaultRenderer.tsx
- Composer/packages/lib/shared/src/appschema.ts
**SetProperties**
**DeleteProperties**
> Show proper contents for new types: SetProperties, DeleteProperties

- BotProject/CSharp/BotProject.csproj
Since the decouple PR is not merged, we still need bot manager packages update
closes #1734 
> fix: Update botproject packages

- Composer/packages/extensions/obiformeditor/src/FormEditor.tsx
The data in the form editor was controlled as a local state.
update the local data when data from shell changed. 
closes #1784 
> fix: undo/redo does not reflect in form

- Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/CancelDialog/CancelDialog.dialog
- Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/ForeachPageStep/ForeachPageStep.dialog
- Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/ForeachStep/ForeachStep.dialog
- Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/IfCondition/IfCondition.dialog
- Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/RepeatDialog/RepeatDialog.dialog
- Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/SwitchCondition/SwitchCondition.dialog
- Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/common/common.lg
some expression is not mapped to the LG.
refs #1862 
> fix: use composer to update the ControllingConversationFlowSample

- Composer/packages/extensions/visual-designer/src/components/menus/NodeMenu.tsx
Changed the delete icon in the in the Visual Designer from 'Cancel' to 'Delete'.
Closes #1888
> fix: Updated delete icon in the Visual Designer

- Composer/packages/extensions/obiformeditor/src/Form/fields/PromptField/Validations.tsx
Updated the options for the `ExpressionWidget` in the `ValidationItem` component to hide the label in the list view.
Closes #1890
> fix: Removed label from validations list

- CHANGELOG.md
- scripts/generate-changelog.js
> release: update changelog

- Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
> fix: use luIntents to populate intent dropdown when creating a trigger

- Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
> fix: intent dropdown in trigger wizard

- Composer/packages/client/src/components/ProjectTree/styles.ts
- Composer/packages/client/src/pages/design/styles.js
Background color update
We probably need to update the color of the image in the second screenshot. 
Closes #1903
> style: update background color

- Composer/packages/client/tsconfig.json
- Composer/packages/server/tsconfig.json
- Composer/tsconfig.base.json
> build: add declarationMap compiler option to base ts config

- Composer/packages/extensions/obiformeditor/src/schema/uischema.ts
- Composer/packages/extensions/visual-designer/src/schema/uischema.tsx
- Composer/packages/lib/shared/src/appschema.ts
- Composer/packages/lib/shared/src/labelMap.ts
- Composer/packages/lib/shared/src/types/schema.ts
- Composer/packages/lib/shared/src/viewUtils.ts
Follows #1817 
Support BeginSkill in Composer side
> support BeginSkill in Composer

- Composer/packages/extensions/visual-designer/src/components/nodes/templates/FormCard.tsx
Style change for formCard in visual editor
fixes #1701
> style: style change for formCard in visual editor

- Composer/packages/extensions/obiformeditor/demo/src/editorschema.json
- Composer/packages/extensions/visual-designer/demo/src/samples/todo/AddToDo.json
- Composer/packages/extensions/visual-designer/demo/src/stories/VisualSDKDemo.js
- Composer/packages/extensions/visual-designer/src/schema/uischema.tsx
- Composer/packages/lib/shared/src/appschema.ts
- Composer/packages/lib/shared/src/labelMap.ts
- Composer/packages/lib/shared/src/types/schema.ts
- Composer/packages/lib/shared/src/viewUtils.ts
- Composer/packages/server/schemas/editor.schema
> chore: remove 'InitProperty' type in Composer

- Composer/packages/lib/shared/src/appschema.ts
> fix: Default ActivityProcessed to true (bool)

- Composer/packages/client/src/pages/design/index.tsx
- Composer/packages/extensions/visual-designer/src/editors/ObiEditor.tsx
- Composer/packages/extensions/visual-designer/src/utils/jsonTracker.ts
- Composer/packages/lib/shared/src/dialogFactory.ts
> fix: make MoveSelection work (not target master)

- Composer/packages/client/src/pages/language-generation/table-view.tsx
> fix: beenUsed status in lg all up view

- Composer/packages/client/src/store/reducer/index.ts
- Composer/packages/server/src/models/connector/csharpBotConnector.ts
- Composer/packages/server/src/models/environment/defaultEnvironment.ts
Fix a bug when open a bot after runtime running, the connect status was not reset.
close #2213
> fix: fix connect status

- Composer/packages/client/src/pages/design/index.tsx
- Composer/packages/client/src/pages/notifications/NotificationHeader.tsx
> a11y: Accessibility issue

- BotProject/Templates/CSharp/BotProject.csproj
> feat: Update BotProject.csproj package version to nuget 4.8.0 and 4.8.0-rc0

- Composer/packages/server/assets/projects/TodoRecognizerSetSample/ComposerDialogs/Main/Main.dialog
- Composer/packages/server/assets/projects/TodoSample/ComposerDialogs/Main/Main.dialog
> fix: Change templates to use $type over $kind

- .github/ISSUE_TEMPLATE/bot-framework-composer-bug.md
> chore: update bug issue template to create correct label

- Composer/packages/tools/language-servers/language-generation/src/LGServer.ts
- Composer/packages/tools/language-servers/language-generation/src/utils.ts
closes #2330 
Adding support of auto-complete/auto-suggest for Activity and Cards
Here is a demo:
> fix: Auto-complete/auto-suggest for Activity and Cards

- Composer/packages/client/src/CreationFlow/DefineConversation/index.tsx
- Composer/packages/client/src/CreationFlow/LocationBrowser/FileSelector.tsx
- Composer/packages/client/src/CreationFlow/LocationBrowser/LocationSelectContent.tsx
- Composer/packages/client/src/CreationFlow/OpenProject/index.tsx
- Composer/packages/client/src/CreationFlow/index.js
- Composer/packages/client/src/pages/design/createDialogModal.tsx
- Composer/packages/server/src/services/storage.ts
- Composer/packages/server/src/settings/env.ts
- Composer/packages/server/src/settings/index.ts
- Composer/packages/server/src/store/migrations.ts
Reverts microsoft/BotFramework-Composer#2274
> Revert "fix: add disk names"

- Composer/packages/ui-plugins/luis/src/index.ts
fixes https://github.com/microsoft/BotFramework-Composer/issues/2399
> fix: lu serialization from form component

- Composer/packages/client/src/App.tsx
> fix: highlight design page nav item 

- Composer/packages/client/src/CreationFlow/CreateOptions/index.js
> fix: small typo on create from scratch page

- Composer/packages/client/src/pages/design/styles.ts
> fix: add scrollbar for form

- Composer/packages/extensions/adaptive-form/src/components/fields/ObjectArrayField.tsx
Fixes the message read on the "name" field to be more informative.
Closes #2130
> a11y: update a11y label in ObjectArrayField

- Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
- Composer/packages/client/src/pages/design/index.tsx
- Composer/packages/client/src/utils/dialogUtil.ts
- Composer/packages/client/src/utils/qnaUtil.ts
> update trigger wizard

- Composer/packages/tools/language-servers/language-generation/package.json
- Composer/packages/tools/language-servers/language-generation/src/builtinFunctionsMap.ts
closes #2605 
adaptive expressions in LG LSP upgrade to the latest version
suggestions for type checking functions are available now
> fix: Switch to the latest version of adaptive expressions and enable suggestions for type checking functions

- Composer/packages/server/src/models/bot/skillManager.ts
use composer log component instead of console.log
closes #2621
> fix: remove skill fetch server  console log

- Composer/packages/extensions/visual-designer/src/components/lib/EdgeUtil.tsx
- Composer/packages/extensions/visual-designer/src/components/menus/IconMenu.tsx
- Composer/packages/extensions/visual-designer/src/components/menus/NodeMenu.tsx
- Composer/packages/extensions/visual-designer/src/editors/StepEditor.tsx
Add aria-label to node, remove `data-name` & `name` from svg.
fixes #2009
> a11y: Add aria-label to node

- Composer/packages/client/src/components/TestController/loading.tsx
Will announce loading status now.
Ref #2068
> a11y: Accessibility 2068

- Composer/packages/client/src/pages/about/index.tsx
- Composer/packages/client/src/pages/about/styles.js
We changed the UI. I think there are issues left only in about page. The others are solved.
Ref #2091
> a11y: Accessibility 2091

- Composer/packages/client/src/CreationFlow/DefineConversation/index.tsx
auto focus on Name field once opening dialog
Refs #2015
> a11y: accessibility issue 2015

- Composer/packages/client/src/pages/language-generation/table-view.tsx
will read the new item added
Refs #2052
> a11y: Accessibility 2052

- Composer/packages/extensions/adaptive-form/src/components/FieldLabel.tsx
- Composer/packages/extensions/adaptive-form/src/components/FormRow.tsx
- Composer/packages/extensions/adaptive-form/src/components/SchemaField.tsx
- Composer/packages/extensions/adaptive-form/src/components/fields/ArrayField.tsx
- Composer/packages/extensions/adaptive-form/src/components/fields/BooleanField.tsx
- Composer/packages/extensions/adaptive-form/src/components/fields/IntentField.tsx
- Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx
- Composer/packages/extensions/adaptive-form/src/components/fields/ObjectArrayField.tsx
- Composer/packages/extensions/adaptive-form/src/components/fields/OneOfField/OneOfField.tsx
- Composer/packages/extensions/adaptive-form/src/components/fields/OpenObjectField/index.tsx
- Composer/packages/extensions/adaptive-form/src/components/fields/RecognizerField.tsx
- Composer/packages/extensions/adaptive-form/src/components/fields/SelectField.tsx
- Composer/packages/extensions/adaptive-form/src/components/fields/StringField.tsx
- Composer/packages/extensions/extension/src/types/form.ts
- Composer/packages/server/schemas/sdk.schema
- Composer/packages/ui-plugins/emit-event/src/EventNameField.tsx
- Composer/packages/ui-plugins/expressions/src/ExpressionField.tsx
- Composer/packages/ui-plugins/json/src/JsonField.tsx
- Composer/packages/ui-plugins/lg/src/LgField.tsx
- Composer/packages/ui-plugins/select-dialog/src/ComboBoxField.tsx
- Composer/packages/ui-plugins/select-skill-dialog/src/ComboBoxField.tsx
Added the required indicator to field labels in the AdaptiveForm package. Also added support for setting `const` and `default` values from the schema in the form data on mount.
Closes #2428 
Closes #2430
> feat: Added required indicator to field labels in the AdaptiveForm package

- Composer/packages/client/src/shell/useShell.ts
- Composer/packages/client/src/store/action/dialog.ts
- Composer/packages/extensions/extension/src/hooks/useDialogApi.ts
> fix: use ref to replace the stale dialogMap

- Composer/packages/client/src/components/Header/index.jsx
I accidentally deleted this line of code in #2721 . 😅
[Source](https://github.com/microsoft/BotFramework-Composer/pull/2721/files#diff-9c357b6e0a2f716a8cce3f50b251f607L22)
Fixes #2226
**Before:**
**After:**
> fix: Restored bot name in header.

- Composer/packages/client/src/shell/luApi.ts
> fix: [Not target master] lu id with locale

- Composer/packages/client/src/App.tsx
- Composer/packages/client/src/components/Header/index.jsx
- Composer/packages/client/src/components/Header/styles.js
- Composer/packages/server/assets/projects/RespondingWithCardsSample/language-generation/en-us/common.en-us.lg
- Composer/yarn.lock
closes #2709
Also does some minor styling cleanup around in <Header />
> fix: Fixes Cards template

- Composer/packages/extensions/visual-designer/src/components/renderers/ElementMeasurer.tsx
close #2773 
https://microsoft.sharepoint.com/:v:/t/ConversationalAI785/EfMmjZEmjlRFgxb9Rs3RR18B48wmnqyNxbwBn1XAopY3mw?e=y6C5DW
> fix: fix Visual Edtitor layout issue after refreshing the page 

- BotProject/Templates/CSharp/BotProject.csproj
Update the sdk package to 4.9.0-preview.200427-125093 which brings in the empty lg file fix. 
fixes #2802
> fix: Update BotProject.csproj 4.9.0-preview.200427-125093

- Composer/packages/client/src/pages/skills/index.tsx
> fix: skill blank page

- Composer/packages/ui-plugins/prompts/src/PromptField/UserInput.tsx
revert value property of prompt field in form
fix #2819
> fix: revert value property of prompt field in form

- Composer/packages/client/__tests__/components/CreationFlow/DefineConversation/index.test.tsx
- Composer/packages/client/__tests__/components/CreationFlow/index.test.tsx
- Composer/packages/client/src/components/CreationFlow/DefineConversation/index.tsx
- Composer/packages/client/src/components/CreationFlow/LocationBrowser/LocationSelectContent.tsx
- Composer/packages/client/src/components/CreationFlow/OpenProject/index.tsx
- Composer/packages/client/src/components/CreationFlow/index.tsx
- Composer/packages/client/src/pages/home/index.tsx
Fix some bugs found during bot creation.
1. The location got reset during the process of decoding url. The location is set to '' and sent to server. So the server creates the new bot at default location.
2. The preset name is undefined when save as a bot because the templateId is not passed to that component. The corresponding url is also changed to 'projectId/templateId/save'
3. Add/Modify some Unit test.
closes #2798
> fix: bot creation at an unexpected location

- Composer/packages/server/assets/projects/EchoBot/echobot.dialog
- Composer/packages/server/assets/projects/EchoBot/language-generation/en-us/common.en-us.lg
- Composer/packages/server/assets/projects/EmptyBot/emptybot.dialog
- Composer/packages/server/assets/projects/EmptyBot/language-generation/en-us/common.en-us.lg
> fix: Update Echobot and Empty samples to include a greeting template

- Composer/packages/client/src/pages/design/styles.ts
> fix: border in visual editor

- Composer/packages/lib/shared/src/viewUtils.ts
> [Not target master] fix the displayed title of customized action

- Composer/packages/client/__tests__/components/CreationFlow/DefineConversation/index.test.tsx
- Composer/packages/client/src/components/CreationFlow/LocationBrowser/FileSelector.tsx
- Composer/packages/client/src/components/CreationFlow/LocationBrowser/LocationSelectContent.tsx
- Composer/packages/server/src/services/storage.ts
- Composer/packages/server/src/settings/index.ts
- Composer/packages/server/src/store/data.template.ts
- Composer/packages/server/src/store/migrations.ts
1. show windows style path
2. filter folder start with . or $
3. initial default path is set to Users/{userName}
Closes #2972
> fix: unify file folder

- Composer/packages/client/src/pages/design/styles.ts
> fix: layout issue when visual editor has no actions

- Composer/packages/electron-server/package.json
> feat: Bumps composer-electron to 0.0.2

- Composer/packages/electron-server/package.json
> fix: Bumps electron-server to 0.0.3

- Composer/cypress/integration/TriggerCreation.spec.ts
- Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
- Composer/packages/client/src/utils/dialogUtil.ts
- Composer/packages/lib/shared/src/viewUtils.ts
Also move missing message events into the activities form.
closes #2988
> fix: bring back custom events to trigger modal

- Composer/packages/extensions/adaptive-form/src/defaultUiSchema.ts
- Composer/packages/extensions/visual-designer/src/schema/defaultFlowSchema.tsx
- Composer/packages/lib/shared/src/copyUtils/CopyConstructorMap.ts
- Composer/packages/lib/shared/src/deleteUtils/index.ts
- Composer/packages/lib/shared/src/labelMap.ts
- Composer/packages/lib/shared/src/types/schema.ts
- Composer/packages/lib/shared/src/viewUtils.ts
- Composer/packages/lib/shared/src/walkerUtils/walkLgResources.ts
- Composer/packages/ui-plugins/select-skill-dialog/src/__tests__/BeginSkillDialogField.test.tsx
- Composer/packages/ui-plugins/select-skill-dialog/src/__tests__/constants.ts
- Composer/packages/ui-plugins/select-skill-dialog/src/formSchema.ts
Rename skillDialog in composer
> chore: rename skillDialog in composer

- Composer/packages/client/config/env.js
- Composer/packages/client/src/pages/about/index.tsx
> fix: clean up about page

- Composer/packages/client/src/pages/home/ItemContainer.tsx
- Composer/packages/client/src/pages/home/index.tsx
- Composer/packages/client/src/pages/home/styles.ts
> feat: add tutorial tiles

- Composer/packages/electron-server/package.json
> feat: 0.0.4

- runtime/dotnet/azurefunctions/Microsoft.BotFramework.Composer.Functions.csproj
- runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
> feat: 4.9.1 runtime packages

- runtime/dotnet/core/Microsoft.BotFramework.Composer.Core.csproj
- runtime/dotnet/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj
> fix: Update core and custom action

- Composer/packages/extensions/extension/src/types/flowSchema.ts
- Composer/packages/extensions/visual-designer/src/index.tsx
- Composer/packages/extensions/visual-designer/src/schema/defaultFlowSchema.tsx
> fix: change custom action nodes theme color to Gray20

- Composer/packages/client/config/env.js
> fix: release label update to 4.9.1

- Composer/packages/lib/code-editor/src/JsonEditor.tsx
Fixes an issue when loading an array.
fixes #3116
> fix: only apply json defaults when schema is type object

- Composer/plugins/README.md
That's all I did.
It's just a quick link fix.
fixes #3135 
None.
> fix: Fixed broken link

- Composer/packages/server/src/models/storage/localDiskStorage.ts
> fix: Adds generated folder to zip archive

- Composer/plugins/samples/assets/shared/README.md
Remove a field from the sample config to match the app
#minor
> docs: remove field from sample config

- .github/workflows/main.yml
The workflow is timing out currently and reporting as a failure. So let's disable this until we can investigate.
#minor
> ci: disable docker build workflow

- runtime/dotnet/tests/InputsTests.cs
> fix: dotnet test case failure

- Composer/packages/lib/bot-deploy/src/botProjectDeploy.ts
fix absolute url issue in azure publish. Missing change from #3274 
close #3228
> fix: fix absolute url issue in azure publish

- runtime/dotnet/ComposerRuntime.sln
- runtime/dotnet/azurefunctions/Microsoft.BotFramework.Composer.Functions.csproj
- runtime/dotnet/azurefunctions/Startup.cs
- runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
- runtime/dotnet/core/Microsoft.BotFramework.Composer.Core.csproj
- runtime/dotnet/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj
1. Update azure function to dotnet 3.1 to work with custom actions
2. Update sdk package from 4.9.2->4.9.3
fixes #3267 
Tested result for custom runtime for azure functions:
> fix: Azure Function Customized Action fix and 4.9.2->4.9.3

- Composer/packages/client/config/env.js
- Composer/packages/electron-server/package.json
> fix: Update version fields for 1.0.1

- Composer/packages/client/__tests__/utils/dialogUtil.test.js
- Composer/packages/extensions/adaptive-form/src/defaultUiSchema.ts
- Composer/packages/lib/shared/src/labelMap.ts
Updated a few help links with aka.ms links.
#minor
> docs: help links

- Composer/packages/server/src/services/storage.ts
A file's name that contains dialog is recognized as a bot.
Closes #3330
> fix: the pattern to identify a bot

- Composer/packages/extensions/adaptive-form/src/defaultUiSchema.ts
- Composer/packages/lib/shared/src/labelMap.ts
> fix: relabel "End Dialog Turn" to "End Turn" for clarity

- Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
- Composer/packages/client/src/store/action/qna.ts
- Composer/packages/client/src/store/parsers/qnaWorker.ts
- Composer/packages/client/src/store/parsers/types.ts
- Composer/packages/client/src/store/parsers/workers/qnaParser.worker.ts
- Composer/packages/lib/indexers/package.json
- Composer/packages/lib/indexers/src/utils/qnaUtil.ts
- Composer/yarn.lock
> code clean

- Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
- Composer/packages/client/src/pages/notifications/useNotifications.tsx
- Composer/packages/client/src/pages/qna/table-view.tsx
- Composer/packages/client/src/store/action/qna.ts
- Composer/packages/client/src/store/parsers/qnaWorker.ts
- Composer/packages/client/src/store/parsers/types.ts
- Composer/packages/client/src/store/parsers/workers/qnaParser.worker.ts
- Composer/packages/lib/indexers/package.json
- Composer/packages/lib/indexers/src/utils/qnaUtil.ts
- Composer/yarn.lock
> Qna recognizer update

- Composer/packages/server/package.json
- Composer/yarn.lock
Added bf-generate package to server with matching preview version of CLI.
#minor
[#3488](https://github.com/microsoft/BotFramework-Composer/issues/3488)
N/A
> feature: Added bf-generate reference to server

- .vscode/launch.json
Added a launch config to the root `.vscode/launch.json` that launches the Electron main process and allows the developer to set breakpoints.
#minor
> chore: Added config to debug Electron main process.

- Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
- Composer/packages/client/src/components/ProjectTree/styles.ts
- Composer/packages/client/src/pages/design/DesignPage.tsx
- Composer/packages/client/src/pages/qna/code-editor.tsx
- Composer/packages/client/src/pages/qna/index.tsx
- Composer/packages/client/src/pages/qna/inlineCodeEditor.tsx
- Composer/packages/client/src/pages/qna/styles.ts
- Composer/packages/client/src/pages/qna/table-view.tsx
- Composer/packages/client/src/store/reducer/index.ts
- Composer/packages/client/src/utils/dialogUtil.ts
- Composer/packages/lib/code-editor/src/LuEditor.tsx
- Composer/packages/lib/indexers/package.json
- Composer/packages/lib/indexers/src/qnaIndexer.ts
- Composer/packages/lib/indexers/src/utils/qnaUtil.ts
- Composer/packages/lib/shared/src/labelMap.ts
- Composer/packages/lib/shared/src/types/indexers.ts
- Composer/packages/lib/shared/src/types/schema.ts
- Composer/packages/lib/shared/src/viewUtils.ts
> Qna enchance

- Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
- Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
- Composer/packages/client/src/components/ProjectTree/styles.ts
- Composer/packages/client/src/components/ProjectTree/treeItem.tsx
- Composer/packages/client/src/pages/qna/table-view.tsx
- Composer/packages/extensions/adaptive-form/src/defaultUiSchema.ts
- Composer/packages/lib/shared/src/labelMap.ts
> addWarning

- Composer/packages/lib/shared/src/dialogFactory.ts
> update trigger initialization

- Composer/packages/extensions/adaptive-form/src/defaultUiSchema.ts
- Composer/packages/lib/shared/src/labelMap.ts
- Composer/packages/lib/shared/src/viewUtils.ts
> feat: Adds SignOutUser action

- Composer/packages/client/src/pages/qna/styles.ts
- Composer/packages/client/src/pages/qna/table-view.tsx
- Composer/packages/lib/indexers/src/utils/qnaUtil.ts
> fix known bugs

- docs/internal/GeoffsRecoilAssessment.md
Creating a PR of this document so that team can review and comment using the PR process.
No task.
None.
#minor
> doc: Added assessment of recoil

- Composer/packages/client/src/pages/qna/table-view.tsx
- Composer/packages/lib/indexers/src/index.ts
- Composer/packages/lib/indexers/src/qnaIndexer.ts
- Composer/packages/lib/indexers/src/utils/qnaUtil.ts
- Composer/packages/lib/shared/src/types/indexers.ts
- Composer/packages/server/src/controllers/project.ts
> Rebuild qna

- Composer/packages/lib/shared/src/viewUtils.ts
> add qna trigger type

- Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
- Composer/packages/client/src/pages/qna/table-view.tsx
- Composer/packages/client/src/recoilModel/dispatchers/project.ts
- Composer/packages/client/src/utils/dialogUtil.ts
- Composer/packages/lib/indexers/src/utils/qnaUtil.ts
> Refine qna crud

- Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
- Composer/packages/client/src/pages/design/DesignPage.tsx
- Composer/packages/client/src/utils/dialogUtil.ts
- Composer/packages/lib/shared/src/dialogFactory.ts
- Composer/packages/server/src/controllers/project.ts
> update trigger action

- runtime/dotnet/azurewebapp/Schemas/readme.md
- runtime/dotnet/azurewebapp/Schemas/update-schema.ps1
Fixes some issues when files weren't present before trying to move or remove them.
refs #3733
> fix: make update-schema.ps1 more resilient

- Composer/packages/tools/language-servers/language-generation/src/lgParser.ts
Fixes an issue where forked processes would be re-created every time an electron window would open.
fixes #3735
> fix: re-use lg parser process

- Composer/packages/server/package.json
- Composer/packages/server/src/controllers/formDialog.ts
- Composer/packages/server/src/controllers/project.ts
- Composer/packages/server/src/models/bot/botProject.ts
- Composer/packages/server/src/router/api.ts
- Composer/yarn.lock
Added discovery API methods
#minor
#3488
N/A
> feat: Added discovery APIs

- Composer/packages/server/src/models/storage/localDiskStorage.ts
> fix export bug

- Composer/packages/client/src/recoilModel/dispatchers/dialogs.ts
- Composer/packages/lib/indexers/src/utils/dialogCheckUtil.ts
> fix: dialog ref lg/lu name formate to lowercase

- Composer/packages/client/src/components/ProjectTree/TriggerCreationModal.tsx
- Composer/packages/client/src/constants.ts
> fix trigger bug

- Composer/packages/server/package.json
- Composer/plugins/lib/bot-deploy/src/botProjectDeploy.ts
fix lubuild in azure publishing, same as pr: https://github.com/microsoft/BotFramework-Composer/pull/3764
#minor
> fix: fix lubuild error while publishing to azure

- Composer/packages/client/src/pages/publish/createPublishTarget.tsx
fix publish profile name duplication
#minor
> fix: fix name repeated detection in publish profile

- Composer/packages/client/src/pages/skills/index.tsx
- Composer/packages/client/src/pages/skills/skill-settings.tsx
> feat: Wire up password in skills page

- Composer/packages/lib/shared/src/schemaUtils/circular.ts
- Composer/yarn.lock
Adds `schema` to circular references to avoid stack overflow when parsing schema.
#minor
> fix: update circular reference list for schema parsing

- Composer/packages/client/__tests__/components/triggerCreationModal.test.tsx
- Composer/packages/client/__tests__/shell/triggerApi.test.tsx
> qna-recognizer add tests

- Composer/packages/client/src/pages/language-understanding/table-view.tsx
- Composer/packages/client/src/recoilModel/dispatchers/lu.ts
Fix update lu file not work when updated intent is new created.
close #3860
> fix: LU intent inline update

- Composer/plugins/samples/assets/projects/AskingQuestionsSample/askingquestionssample.dialog
- Composer/plugins/samples/assets/projects/AskingQuestionsSample/language-generation/en-us/askingquestionssample.en-us.lg
fix missing `designerId` 
close #3869
> fix: AskingQuestionsSample sample bot

- Composer/packages/extensions/adaptive-flow/src/adaptive-flow-renderer/configs/builtinSchema.tsx
- Composer/packages/lib/shared/src/labelMap.ts
- Composer/packages/lib/shared/src/types/schema.ts
- Composer/packages/server/schemas/sdk.schema
- Composer/packages/ui-plugins/composer/src/defaultMenuSchema.ts
closes #3873 
follows #3862 
- Adding support to TelemetryTraceEvent in Flow Editor
- Update Composer/server/.../sdk.schema to v4.10
> feat: adding support to TelemetryTraceEvent in Flow Editor

- Composer/packages/client/src/components/CreationFlow/CreationFlow.tsx
- Composer/packages/client/src/pages/design/DesignPage.tsx
bugfix about import qna url, like the gif shows.
> fix: import url bugfix

- Composer/packages/client/__tests__/utils/qnaUtil.test.ts
- Composer/packages/lib/indexers/src/utils/qnaUtil.ts
> test: add qnaUtil test

- Composer/packages/extensions/adaptive-form/src/components/fields/RecognizerField.tsx
Bugfix: The recognizer type in form doesn't update when change the value.
fix #3916
> fix: recognizer dropdown fix

- Composer/packages/client/config/env.js
- Composer/packages/client/src/pages/knowledge-base/ImportQnAFromUrlModal.tsx
- Composer/packages/client/src/pages/knowledge-base/__tests__/importQnAFromUrlModal.test.tsx
- Composer/packages/ui-plugins/lg/src/index.ts
> fix: 1.1 cleanup

- Composer/packages/server/schemas/sdk.schema
- runtime/dotnet/azurefunctions/Microsoft.BotFramework.Composer.Functions.csproj
- runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
- runtime/dotnet/azurewebapp/Schemas/sdk.schema
- runtime/dotnet/core/Microsoft.BotFramework.Composer.Core.csproj
- runtime/dotnet/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj
> feat: move to 4.10.2 runtime packages

- Composer/packages/client/src/components/ErrorPopup/ErrorPopup.tsx
> fix: electron open error link should open in browser

- releases/1.1.0.md
Minor wording and formatting modifications. 
#minor
> doc: update 1.1.0.md

- runtime/dotnet/azurefunctions/Startup.cs
- runtime/dotnet/azurewebapp/Startup.cs
1. Fix current settings loading not working for older bot developed by composer
2. Mainly null object handling 
#minor
> fix: current settings loading not working for older bot developed by composer

- Composer/packages/client/config/env.js
- Composer/packages/electron-server/package.json
- releases/1.1.1.md
> release: Update for 1.1.1 release

- Composer/packages/client/__tests__/components/CreationFlow/LocationBrowser/FileSelector.test.tsx
- Composer/packages/client/locales/en-US.json
- Composer/packages/client/src/components/CreationFlow/FileSelector.tsx
> fix: UI text in 'new bot' should start upper case

- .github/CODEOWNERS
Need to update the owners for composer to include myself and Soroush.
#minor
N/A
> chore: Updated owners for PRs

- Composer/packages/adaptive-form/src/utils/uiOptionsHelpers.ts
- Composer/packages/intellisense/src/components/IntellisenseTextField.tsx
> chore: Adding missing variable in array of dependency in React hook

- Composer/packages/client/src/recoilModel/dispatchers/__tests__/lg.test.tsx
- Composer/packages/client/src/recoilModel/dispatchers/lg.ts
- Composer/packages/client/src/recoilModel/dispatchers/lu.ts
> fix: New LG template not sync to other locale files

- Composer/packages/server/src/locales/en-US.json
This is another batch of strings that got missed in a recent PR; we should merge this to keep our locale files in sync.
refs #3913
> fix: update l10n file

- runtime/dotnet/azurefunctions/Microsoft.BotFramework.Composer.Functions.csproj
- runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
- runtime/dotnet/azurewebapp/Schemas/sdk.schema
- runtime/dotnet/core/Microsoft.BotFramework.Composer.Core.csproj
- runtime/dotnet/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj
Update runtime package to 4.10.5, which includes the following fix:
fixes #4118
> feat: Update runtime package to 4.10.5

- .github/workflows/main.yml
- Composer/packages/server/src/controllers/__tests__/publisher.test.ts
update the yarn cache key
#minor
> chore: remove the ci yarn cache [TEST]

- Composer/packages/client/__tests__/components/CreationFlow/index.test.tsx
Fixes an issue with test failing on windows due to / vs \
#minor
N/A
> fix: Fixed platform specific location expectation

- extensions/runtimes/src/index.ts
fix the runtime template path in runtime plugin.
close #4415
> fix: fix publish failure due to runtime template path error

- README.md
> docs: added MIT licience badge in README.md

- Composer/packages/server/schemas/sdk.en-US.uischema
- Composer/packages/server/schemas/sdk.uischema
Updated .uischema from bf-dialog merge against the .uischema improvements I added to the SDK for form dialogs.
#minor
#4149 
N/A
> feat: Update UI from SDK

- extensions/localPublish/src/index.ts
change the name for localPublish plugin, make it match with other places in composer.
close #4449
> fix: local publish can not find plugin

- Composer/packages/server/src/models/bot/builder.ts
crosstrain can't find the qna import file.
In #3919 has solved the issue. 
#minor
> fix: regression of lu and qna import resolver

- Composer/scripts/compileExtensions.js
> fix: check package.json existence in script `compileExtensions.js`

- Composer/packages/server/package.json
- Composer/yarn.lock
Updates the library to the latest.
#minor
> chore: update bf-generate-library

- Composer/packages/adaptive-flow/src/adaptive-flow-editor/hooks/useEditorEventApi.ts
> fix: multi-selection state of Visual Editor cannot be cleared

- Composer/packages/server/src/controllers/__tests__/publisher.test.ts
Issue was caused by loading plugin timeout. I mock the ExtensionContext instead of loading plugin to fix it.
close #4555
> fix: fix publish ut timeout

- Composer/packages/server/package.json
- Composer/yarn.lock
This somehow made it back into the package.json.
#minor
> chore: remove orchestrator

- Composer/packages/client/__tests__/components/createQnAModal.test.tsx
- Composer/packages/client/src/components/QnA/CreateQnAFromUrlModal.tsx
- Composer/packages/client/src/pages/design/DesignPage.tsx
- Composer/packages/client/src/pages/knowledge-base/QnAPage.tsx
- Composer/packages/client/src/pages/knowledge-base/table-view.tsx
- Composer/packages/client/src/recoilModel/atoms/botState.ts
- Composer/packages/client/src/recoilModel/dispatchers/qna.ts
> fix: create QnA bot wizard missing "create from scratch" option

- Composer/packages/client/src/pages/design/DesignPage.tsx
> fix: update 'Disable/Enable' buttons state in realtime

- runtime/dotnet/azurewebapp/Startup.cs
This PR just always enable AllowedCallersClaimsValidator in composer runtime.
We didn't remove isSkill settings in this PR, will have follow ups when we get an agreement on that.
fixes #4501
> fix: Always enable AllowClaimValidator

- Composer/packages/server/schemas/sdk.cs.schema
- Composer/packages/server/schemas/sdk.de.schema
- Composer/packages/server/schemas/sdk.en-US.schema
- Composer/packages/server/schemas/sdk.es.schema
- Composer/packages/server/schemas/sdk.fr.schema
- Composer/packages/server/schemas/sdk.hu.schema
- Composer/packages/server/schemas/sdk.it.schema
- Composer/packages/server/schemas/sdk.ja.schema
- Composer/packages/server/schemas/sdk.ko.schema
- Composer/packages/server/schemas/sdk.nl.schema
- Composer/packages/server/schemas/sdk.pl.schema
- Composer/packages/server/schemas/sdk.pt-BR.schema
- Composer/packages/server/schemas/sdk.pt-PT.schema
- Composer/packages/server/schemas/sdk.ru.schema
- Composer/packages/server/schemas/sdk.schema
- Composer/packages/server/schemas/sdk.sv.schema
- Composer/packages/server/schemas/sdk.tr.schema
- Composer/packages/server/schemas/sdk.zh-Hans.schema
- Composer/packages/server/schemas/sdk.zh-Hant.schema
- runtime/dotnet/azurewebapp/Schemas/sdk.schema
Update schema title.
close #4656
> fix: Change Microsoft.UpdateActivity title from "Send an activity" to "Update an activity"

- extensions/samples/src/index.ts
> fix: Variable name

- Composer/packages/server/src/models/settings/defaultSettingManager.ts
- runtime/dotnet/azurewebapp/Startup.cs
migrate the old bots' setting to the latest version.
closes #4721
> fix: add skillConfiguration settings for old bot

- extensions/azurePublish/src/luisAndQnA.ts
the old version bf-lu need id to find the import files.
add id and path for importresolver
refs #4709
close #4703
> fix: azure publish failed

- Composer/packages/client/src/pages/form-dialog/VisualFormDialogSchemaEditor.tsx
- Composer/packages/client/src/recoilModel/persistence/FilePersistence.ts
- Composer/packages/client/src/recoilModel/persistence/types.ts
- Composer/packages/form-dialogs/src/demo/DemoApp.tsx
- Composer/packages/lib/indexers/src/index.ts
- Composer/packages/lib/indexers/src/utils/fileExtensions.ts
- Composer/packages/server/src/models/bot/botProject.ts
- Composer/packages/types/src/indexers.ts
.form extension for form dialog schema files
close #4674
> fix: .form extension for form dialog schema files

- Composer/packages/server/schemas/sdk.schema
- Composer/packages/server/schemas/sdk.uischema
- runtime/dotnet/azurefunctions/Microsoft.BotFramework.Composer.Functions.csproj
- runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
- runtime/dotnet/azurewebapp/Schemas/sdk.schema
- runtime/dotnet/azurewebapp/Schemas/sdk.uischema
- runtime/dotnet/core/Microsoft.BotFramework.Composer.Core.csproj
- runtime/dotnet/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj
> feat: update sdk package to 4.11.0

- Composer/packages/client/src/pages/setting/app-settings/AppSettings.tsx
Due to issues with some formatMessage calls, need to rollback adding the langs to the dropdown.
#minor
N/A
> fix: Removed other languages for now.

- Composer/packages/client/src/shell/lgApi.ts
- Composer/packages/client/src/shell/luApi.ts
Updates the lg and lu update handlers to be invoked on the leading AND trailing edges of the debounce period, fixing a serialization issue.
#minor
> fix: update debounced update handlers

- Composer/packages/adaptive-flow/src/adaptive-flow-editor/hooks/useEditorEventApi.ts
> fix: Move doesn't work

- Composer/packages/server/src/models/storage/localDiskStorage.ts
> fix: export to .zip

- Composer/packages/server/package.json
- Composer/yarn.lock
Updates to the latest bf-generate-lib.
#minor
> chore: Update bf-generate-lib

- extensions/pvaPublish/package.json
- extensions/pvaPublish/src/node/publish.ts
- extensions/pvaPublish/src/node/types.ts
- extensions/pvaPublish/src/node/utils.spec.ts
- extensions/pvaPublish/src/ui/pvaDialog.tsx
- extensions/pvaPublish/tsconfig.json
- extensions/pvaPublish/yarn.lock
On some users' machines, when building from source they were seeing build time errors due to the lack of `@types/node-fetch`.
This PR adds the `node-fetch` types and adds some strict type checking in the `tsconfig` settings.
#minor
> chore: Added more strict type checking to pva publish extension

- Composer/packages/adaptive-flow/package.json
- Composer/packages/lib/indexers/package.json
- Composer/packages/tools/language-servers/language-generation/package.json
- Composer/yarn.lock
update the lg lib version.
The root cause is https://github.com/microsoft/botbuilder-js/pull/3077
closes #4848
> fix: lg api use the wrong offset on the original file

- Composer/packages/electron-server/PROTOCOL.md
- extensions/packageManager/src/node/index.ts
closes #4902 
Change the URL for package manager's default feed to point at the new component repo.
> chore: Update the URL of the component feed

- Composer/packages/adaptive-flow/package.json
- Composer/packages/client/src/pages/knowledge-base/table-view.tsx
- Composer/packages/lib/indexers/package.json
- Composer/packages/tools/language-servers/language-generation/package.json
- Composer/yarn.lock
cherry-pick these two #4871 #4892
#minor
> chore: cherry-pick lg and qna commit to v1.2.2

- Composer/cypress/integration/LeftNavBar.spec.ts
- Composer/cypress/integration/LuisDeploy.spec.ts
- Composer/cypress/integration/Onboarding.spec.ts
- Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
- Composer/packages/client/src/components/BotRuntimeController/BotControllerMenu.tsx
- Composer/packages/client/src/router.tsx
- Composer/packages/client/src/utils/hooks.ts
- Composer/packages/client/src/utils/pageLinks.ts
- Composer/packages/server/src/controllers/__tests__/settings.test.ts
Change start bots controller to a toggle.
@liweitian I had to make a change to setLocale as it gets an undefined locale and messes the entire LG view like below
#minor
> fix: Toggle interaction on start bots

- Composer/packages/client/src/components/DiagnosticsHeader.tsx
- Composer/packages/client/src/pages/design/DesignPage.tsx
- Composer/packages/client/src/pages/diagnostics/Diagnostics.tsx
- Composer/packages/client/src/utils/navigation.ts
> fix: Add diagnostics header on the design page

- Composer/packages/client/src/pages/setting/SettingsPage.tsx
- Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
- Composer/packages/client/src/utils/pageLinks.ts
> fix: url bug on setting page

- runtime/dotnet/customaction/Action/MultiplyDialog.cs
- runtime/dotnet/customaction/CustomActionComponentRegistration.cs
add missing copyright headers for composer runtime
fixes #4923
> fix: add missing copyright headers

- Composer/packages/client/src/recoilModel/dispatchers/multilang.ts
- Composer/packages/client/src/router.tsx
> fix: Local sync bug

- Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
- Composer/packages/client/src/pages/setting/SettingsPage.tsx
- Composer/packages/client/src/pages/setting/router.tsx
- Composer/packages/client/src/recoilModel/dispatchers/multilang.ts
- Composer/packages/client/src/recoilModel/dispatchers/navigation.ts
- Composer/packages/client/src/recoilModel/dispatchers/project.ts
- Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
- Composer/packages/client/src/router.tsx
- Composer/packages/client/src/utils/navigation.ts
- Composer/packages/client/src/utils/pageLinks.ts
- Composer/scripts/e2e.js
Settings page urls standardized.
Closes #4937
> fix: Settings page url

- Composer/packages/client/src/pages/form-dialog/FormDialogPage.tsx
- Composer/packages/client/src/recoilModel/dispatchers/formDialogs.ts
- Composer/packages/server/package.json
- Composer/yarn.lock
Fixes view dialog functionality from the list of form dialog schemas.
Updates bf-generate-library with minor fixes in merge.
#minor
> fix: Allows "view dialog" from form dialog schema page

- Composer/package.json
- Composer/packages/electron-server/babel.l10n.config.js
Fixes issues with extracting strings particularly in electron package.
#minor
> fix: [l10n] Fixes issues with extracting strings particularly in electron package.

- Composer/packages/client/src/components/TextFieldWithCustomButton.tsx
- Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
- Composer/packages/client/src/pages/botProject/BotProjectSettingsTableView.tsx
- Composer/packages/client/src/pages/botProject/DeleteBotButton.tsx
- Composer/packages/client/src/pages/botProject/ExternalService.tsx
- Composer/packages/client/src/pages/botProject/PublishTargets.tsx
- Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
- Composer/packages/client/src/pages/botProject/SkillBotExternalService.tsx
- Composer/packages/client/src/pages/design/DesignPage.tsx
- Composer/packages/client/src/pages/publish/BotStatusList.tsx
- Composer/packages/client/src/utils/navigation.ts
- Composer/packages/lib/indexers/src/botIndexer.ts
- Composer/packages/lib/shared/src/diagnostic.ts
luis or qna key missing error will navigate to settings page and scroll to related fields
Manager Profiles button in publish page will navigate to settings page and scroll to related fields
Closes #4974
> fix: scroll to settings page component

- Composer/packages/adaptive-flow/src/adaptive-flow-editor/AdaptiveFlowEditor.tsx
fix: can not resize pane
closes #4952 #4965
> fix: can not resize pane

- Composer/packages/client/src/pages/publish/Publish.tsx
- Composer/packages/client/src/pages/publish/PublishStatusList.tsx
Fix: pop up err notifications when sorting publish history
Error:
#minor
> fix: sort publish history err

- Composer/packages/server/src/locales/en-US.json
This is just another automated update to our l10n files to take recent changes into account.
#minor
> chore: update l10n files to match recent changes

- Composer/packages/adaptive-flow/__tests__/adaptive-flow-editor/renderers/EdgeMenu.test.tsx
- Composer/packages/client/src/recoilModel/dispatchers/__tests__/botProjectFile.test.tsx
- Composer/packages/client/src/recoilModel/dispatchers/__tests__/skill.test.ts
Removing fit in tests to avoid running them individually in jest.
#minor
> chore: Remove fit for tests

- Composer/packages/electron-server/package.json
Composer's version was not correctly represented in the `main` branch
#minor
> chore: Updated version to 1.2.1

- Composer/packages/client/src/pages/botProject/RootBotExternalService.tsx
- Composer/packages/client/src/pages/botProject/SkillBotExternalService.tsx
change luis name to luis application name
Closes #5179
> fix: change luis name to luis application name

- extensions/packageManager/readme.md
the bf dialog command was slightly out of date
#minor
> fix: update bf dialog:merge command in package library docs

- Composer/packages/client/src/recoilModel/dispatchers/storage.ts
- Composer/packages/types/src/telemetry.ts
Adding telemetry when feature flags are toggled.
Closes #5117
> feat: Added FeatureFlagChanged to telemetry

- Composer/packages/lib/shared/src/featureFlagUtils/index.ts
- Composer/packages/ui-plugins/orchestrator/src/index.ts
Minor text updates for Orchestrator. "Learn More" link goes to [https://aka.ms/bf-orchestrator](https://aka.ms/bf-orchestrator)
closes #5087 and #5112
> fix: Minor Orchestrator Text Changes

- Composer/packages/client/src/recoilModel/dispatchers/formDialogs.ts
- Composer/packages/types/src/telemetry.ts
Added telemetry log for each time user generates a form dialog.
Closes #5118
> feat: Added log call to generating dialog.

- Composer/packages/client/src/components/Header.tsx
> feat: Guard BotController with schema check

- Composer/packages/client/package.json
yarn start:client crashed on me couple of times today due to heap size so I increased it.
#minor
> chore: Increase webpack hmr heap size

- Composer/packages/client/src/components/QnA/CreateQnAFromUrlModal.tsx
> fix: QnA create placeholder updated to "Enter a URL"

- Composer/cypress/integration/LuisDeploy.spec.ts
e2e failed due to recent change on settings' page. luis region field changed to dropdown.
#minor
> fix:  e2e test

- Composer/packages/client/config/env.js
- Composer/packages/electron-server/package.json
update version to 1.3.0-rc1
#minor
> chore: update version to 1.3.0-rc1

- Composer/packages/client/src/pages/publish/__tests__/pullConfirmationDialog.test.tsx
- Composer/packages/client/src/pages/publish/pullConfirmationDialog.tsx
- Composer/packages/client/src/pages/publish/pullDialog.tsx
Adds a confirmation dialog to the pull UX
Closes #5208
> fix: Added confirmation dialog prior to pull

- Composer/packages/client/config/env.js
- Composer/packages/electron-server/package.json
> release: prep RC2

- Composer/cypress/integration/LuisDeploy.spec.ts
- Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
- Composer/packages/client/src/components/BotRuntimeController/BotControllerMenu.tsx
- Composer/packages/client/src/components/BotRuntimeController/BotRuntimeStatus.tsx
- Composer/packages/client/src/components/BotRuntimeController/BotStatusIndicator.tsx
- Composer/packages/client/src/components/BotRuntimeController/loading.tsx
- Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
- Composer/packages/client/src/components/__tests__/BotRuntimeController/BotRuntimeStatus.test.tsx
- Composer/packages/client/src/constants.ts
- Composer/packages/client/src/recoilModel/dispatchers/publisher.ts
- Composer/packages/client/src/recoilModel/selectors/localRuntimeBuilder.ts
- Composer/yarn.lock
This PR handles
1. Changing the status message to starting when LUIS models have been published and the bot runtime is starting
2. Pluralize only when in multi bot context
@garypretty 
#minor
> fix: single bot and multi bot context handled

- Composer/packages/server/src/constants.ts
> fix: update server version to 1.3.0-rc2 (for User-Agent)

- Composer/packages/server/src/constants.ts
- Composer/packages/server/src/services/telemetry.ts
Add session id to telemetry events
#minor
> fix: Add session id to telemetry events

- Composer/packages/client/config/env.js
- Composer/packages/electron-server/package.json
- Composer/packages/server/src/constants.ts
> release: RC3

- Composer/packages/client/config/env.js
- Composer/packages/electron-server/package.json
- Composer/packages/server/src/constants.ts
> release: RC4

- Composer/packages/client/src/pages/form-dialog/FormDialogPage.tsx
Fixes view dialog link in form dialog success notification when generation was initiated from overflow menu.
Updates messages.
#minor
> fix: Fixes "view dialog" link in form dialog success notification

- Composer/packages/server/src/locales/en-US.json
Another small round of l10n changes to resync with the current state of main.
#minor
> chore: Update en-US.json with latest string changes

- extensions/azurePublish/yarn.lock
- extensions/mongoStorage/yarn.lock
- extensions/packageManager/yarn.lock
- extensions/pvaPublish/yarn.lock
- extensions/sample-ui-plugin/yarn.lock
> fix: security analysis failed because of ini@1.3.5

- Composer/packages/electron-server/package.json
> fix: Remove path module from electron-server

- Composer/packages/electron-server/scripts/electronBuilderDist.js
- Composer/packages/electron-server/scripts/electronBuilderPack.js
It fixes the current broken electron build.
#minor
> fix: electron build is broken

- Composer/packages/server/package.json
- Composer/yarn.lock
ChrisMc has fixes for multiple form dialog bugs reported here in the latest version if bg-generate.
#minor
> chore: update to latest bg-generate

- .github/workflows/validate-pr.yml
Updates the pr validation action to be run when the PR title, body or base branch is edited.
#minor
> ci: validate pr when opened and edited

- Composer/packages/server/src/locales/de.json
- Composer/packages/server/src/locales/en-US.json
- Composer/packages/server/src/locales/es.json
- Composer/packages/server/src/locales/fr.json
- Composer/packages/server/src/locales/it.json
- Composer/packages/server/src/locales/ja.json
- Composer/packages/server/src/locales/nl.json
- Composer/packages/server/src/locales/pl.json
- Composer/packages/server/src/locales/tr.json
- Composer/packages/server/src/locales/zh-Hans.json
Some of our locale files had quote marks in places that broke ICU formatting. This should fix those.
fixes #5496
> fix: l18n apostrophe errors

- Composer/packages/server/package.json
- Composer/yarn.lock
Rolling back upgrade to version with bug
#minor
N/A
> fix: Rolling back to prev version for 1.3

- Composer/packages/client/src/components/QnA/CreateQnAFromScratchModal.tsx
> fix: create QnA from scratch check empty name

- releases/1.3.1.md
> release: v1.3.1

- Composer/packages/client/src/components/Header.tsx
It should be a pure callout component there.
#minor
> fix: change teaching bubble to callout

- Composer/packages/server/src/models/bot/__tests__/botProject.test.ts
> fix: Excluding this test for now to make pipeline pass

- Composer/packages/server/package.json
- Composer/yarn.lock
Updated to latest from myget for bf-generate
#minor
N/A
> chore: Update to latest bf-generate

- Composer/packages/client/src/components/ProjectTree/ProjectHeader.tsx
- Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
Remove some contextual menu items for remote skill, only left 'Remove from this skill from project', it would be more make sense.
close #5683
> fix: correct project tree menu items for remote skill

- .github/ISSUE_TEMPLATE/bot-framework-composer-bug.md
- .github/ISSUE_TEMPLATE/bot-framework-composer-feature-request.md
Reverts feature issue template. Feature requests are tracked in Azure and discussions are not yet supported.
#minor
> revert: feature issue template

- Composer/packages/client/src/pages/design/DebugPanel/DebugPanel.tsx
- Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/DiagnosticsStatus.tsx
- Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/constants.ts
- Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/DiagnosticsTab/index.ts
- Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogContent.tsx
- Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogItem.tsx
- Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/index.ts
- Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/index.ts
- Composer/packages/client/src/recoilModel/atoms/appState.ts
- Composer/packages/client/src/recoilModel/atoms/webchatState.ts
- Composer/packages/client/src/recoilModel/dispatchers/index.ts
- Composer/packages/client/src/recoilModel/dispatchers/webchat.ts
- Composer/packages/types/src/index.ts
- Composer/packages/types/src/webchat.ts
Changes:
1. Necessary Recoil state and actions to manage DL logs
2. A rough version of 'Webchat Inspector' implementation for testing (invisible before design complete)
Preview:
> manage DL logs in Debug Panel

- Composer/packages/lib/shared/src/featureFlagUtils/index.ts
Corrects a wrongly conflict-resolved file.
#minor
> fix: update index.ts and fix build

- Composer/packages/client/src/pages/botProject/adapters/ABSChannelSpeechModal.tsx
- Composer/packages/client/src/pages/botProject/adapters/ABSChannels.tsx
Collect a speech key when enabling the speech service.
Fixes #5632
> feat: collect speech key while enabling direct line speech

- Composer/packages/lib/indexers/src/utils/lgUtil.ts
Allow update lg template with empty body. 
close #5913
> fix: allow update lg template with empty body

- Composer/packages/lib/indexers/src/utils/lgUtil.ts
Fix the typo in last PR
refs #5917
> fix: allow update lg template with empty body ( follow up )

- Composer/packages/tools/language-servers/language-generation/__tests__/LGUtil.test.ts
- Composer/packages/tools/language-servers/language-generation/src/LGServer.ts
- Composer/packages/tools/language-servers/language-generation/src/lgParser.ts
- Composer/packages/tools/language-servers/language-generation/src/lgWorker.ts
closes #5889 
`@answer` and  `@itemList` has been remove.
> fix: remove redundant suggested static luis entities  

- Composer/cypress/integration/LuisDeploy.spec.ts
- Composer/packages/client/src/components/BotRuntimeController/BotController.tsx
> fix: luis deploy e2e test failed

- Composer/packages/client/__tests__/notFound.test.jsx
- Composer/packages/client/src/components/NotFound.jsx
- Composer/packages/client/src/constants.ts
- Composer/packages/lib/indexers/src/validations/expressionValidation/validation.ts
- Composer/packages/server/src/locales/en-US.json
- docs/internal/localization.md
Single quotes mess up string localization.  Replacing with U+2019 (curly single quote)
#minor
N/A
> chore: Replaces single apostrophies with ’ U+2019

- Composer/packages/lib/code-editor/src/lg/ModalityPivot.tsx
Fixes issue removing empty attachment modality in the Response Editor
Closes #6049
> fix: Fixed removing empty attachment modality in Response Editor

- docs/preview features/ms-teams.md
- docs/preview features/speech.md
- docs/preview features/webchat.md
This adds 3 new docs to the preview features folder. 
These docs discuss the "next steps" for activating the channel connections for Teams, DLS and web chat.
There are links to these docs from inside the channel enablement UI.
#minor
> feat: Docs for the new channel enablement

- Composer/packages/lib/code-editor/src/LgEditor.tsx
- Composer/packages/lib/code-editor/src/lg/modalityEditors/StringArrayItem.tsx
- Composer/packages/server/src/locales/en-US.json
- Composer/packages/ui-plugins/lg/src/LgField.tsx
- Composer/packages/ui-plugins/lg/src/index.ts
Changed the Send Activity LG Editor label to 'Bot Responses', and fixed misc capitalization.
Closes #6073
Close #5968
> fix: Updated labels in the lg editor

- extensions/samples/assets/shared/scripts/provisionComposer.js
- runtime/dotnet/azurewebapp/Scripts/deploy.ps1
1. make resource group configurable in deploy.ps1
2. add more fields to publishing profile
fixes #5773
> fix: make resource group configurable in deploy.ps1

- .github/workflows/main.yml
- Composer/package.json
- extensions/azurePublish/src/components/api.tsx
- extensions/azurePublish/src/components/azureProvisionDialog.tsx
- extensions/azurePublish/src/node/azureResourceManager/azureResourceManager.ts
- extensions/azurePublish/src/node/deploy.ts
- extensions/azurePublish/src/node/index.ts
- extensions/azurePublish/src/node/keyvaultHelper/keyvaultApi.ts
- extensions/azurePublish/src/node/keyvaultHelper/keyvaultApiConfig.ts
- extensions/azurePublish/src/node/provision.test.ts
- extensions/azurePublish/src/node/provision.ts
- extensions/azurePublish/src/node/schema.ts
- extensions/azurePublish/src/node/utils/errorHandler.ts
- extensions/packageManager/src/node/feeds/feedFactory.ts
- extensions/packageManager/src/node/feeds/npm/npmFeed.ts
- extensions/packageManager/src/node/feeds/nuget/localNuGetFeed.ts
- extensions/packageManager/src/node/feeds/nuget/nugetFeed.ts
- extensions/packageManager/src/node/index.ts
- extensions/packageManager/src/pages/Library.tsx
- Expands glob pattern for pre-commit hook to format files using prettier
- Adds `lint:extensions` yarn script and invokes on CI
- Applies linting fixes for extensions src
#minor
> chore: prettify and lint extensions

- Composer/packages/client/src/components/Header.tsx
- Composer/packages/client/src/hooks/useControllerBar.ts
> fix: hide BotController in home page

- Composer/packages/client/src/pages/setting/app-settings/FeatureFlagCheckBox.tsx
- Composer/packages/lib/shared/src/featureFlagUtils/index.ts
Rewrote this a little for better localizability too.
closes #6175
> fix: move additional period out of feature flag checkbox

- Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx
add subtext in provision dialog.
close #5923
> fix: add subtext in provision dialog.

- .github/ISSUE_TEMPLATE/bot-framework-composer-feature-request.md
Uses `feature-request` label for new feature request issues.
#minor
> chore: update label for new feature request issues

- Composer/packages/client/src/recoilModel/selectors/lg.ts
- Composer/packages/client/src/utils/lgUtil.ts
- Composer/packages/server/src/locales/en-US.json
This is a small patch to fix a build issue; the main branch was failing on a build step. This also picks up a few new strings for l10n.
#minor
> fix: reroute lgUtil import and add a few l10n things

- Composer/packages/server/src/models/bot/botStructure.ts
Fixes a regression on form dialog project tree rendering.
closes #6328
> fix: Fix form dialogs project tree rendering

- Composer/packages/server-workers/package.json
Fixes issue in nightly build causing yeoman-generators to fail.
#minor
> fix: revert yeoman-environment to 2.10.3 from 3.1.0

- Composer/packages/lib/shared/src/featureFlagUtils/index.ts
Changing feature flag text for new creation experience
fixes #6126
> fix: change feature flag text

- Composer/packages/client/src/Onboarding/WelcomeModal/WelcomeModal.tsx
> fix: Onboarding lint issue

- Composer/packages/server/package.json
- Composer/yarn.lock
Fixes #5349 #5415
This updates to the latest generator library which:
* Fixes an issue that makes it easier to have a form reanalyze a trigger phrase to extract entities.
* Simplifies prompts
* Has a number of other bug fixes that were tracked on the generator side
> chore: Update to latest generator package

- extensions/azurePublish/src/node/azureResourceManager/azureResourceManager.ts
> fix: fix azure application insights name

- extensions/azurePublish/src/components/azureProvisionDialog.tsx
This fixes an issue with the handoff dialog sequencing.
#minor 
N/A
> fix: Fixes to dialog sequencing for handoff

- Composer/packages/server/src/services/project.ts
This removes the newly created folder if the creation process fails
Fixes #6726
> fix: clean up if project creation fails

- Composer/packages/client/src/pages/publish/BotStatusList.tsx
Fixes stale list of publish profiles after profile is created.
fixes #6765 
N/A
> fix: Force refresh of fluent List via slice

- Composer/packages/client/src/recoilModel/Recognizers.tsx
if default language is not en-us and language en-us is one of the languages. It failed to open the bot.
reason: miss passing default language as a parameter
#minor
> fix: miss passing defaultLanguage as parameter

- extensions/azurePublish/src/components/ChooseProvisionAction.tsx
Needed to remove the stack from the summary
fixes #6780
> fix: Fixed content layout issue on create resources

- Composer/packages/adaptive-form/src/components/fields/OneOfField/OneOfField.tsx
- Composer/packages/server/src/locales/en-US.json
Fix missing array of choices expression field
Closes #6651
> fix: Fix missing array of choices expression field

- Composer/packages/client/src/components/ManageLuis/ManageLuis.tsx
- Composer/packages/client/src/components/ManageQNA/ManageQNA.tsx
- Composer/packages/client/src/components/ManageSpeech/ManageSpeech.tsx
- extensions/azurePublish/src/components/azureProvisionDialog.tsx
Adds the handoff instructions for LUIS, QNA, Speech and provision process.
Fixes #6567 
Fixes #6566 
Fixes #6867
> fix: update text in handoff modals

- Composer/packages/client/src/pages/botProject/AllowedCallers.tsx
- Composer/packages/client/src/pages/botProject/BotProjectsSettingsTabView.tsx
- Composer/packages/client/src/pages/botProject/BotSkillConfiguration.tsx
- Composer/packages/server/src/locales/en-US.json
Add allowed callers list to skill configuration settings
Closes #4222
> fix: Add allowed callers list to skill configuration settings

- CODE_OF_CONDUCT.md
required for ms oss projects.  
contains latest content
Fixes #minor
> chore: adding CODE_OF_CONDUCT.md

- Composer/packages/client/src/components/Header.tsx
> fix: Update Open Web Chat text

- Composer/packages/server/src/controllers/asset.ts
- Composer/packages/server/src/locales/en-US.json
qna template readme location was moved leading to a 404 on the template selection page for that template. This PR updates the call to that readme to reflect its final location
fixes #7010
> fix: Update query to grab qna template readme

- Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
> fix: can not create profile in abs

- Composer/packages/lib/code-editor/src/lu/InsertEntityButton.tsx
- Composer/packages/lib/code-editor/src/lu/LuLabelingMenu.tsx
- Composer/packages/lib/code-editor/src/lu/__test__/InsertEntityButton.test.tsx
- Composer/packages/lib/code-editor/src/lu/iconUtils.tsx
- Composer/packages/lib/code-editor/src/lu/types.ts
- Composer/packages/server/src/locales/en-US.json
- Remove Tag Entity menu from LU Toolbar
- Disable Insert Entity menu when Context Menu is visible
- Change 'Tag Entity' label to 'Label Entity'
Closes #6802
> fix: Remove tag entity menu from LU Toolbar

- Composer/packages/client/src/pages/publish/publishPageUtils.tsx
fix publish targets state update after provision
close #6826
> fix: fix publish targets state update after provision

- Composer/packages/lib/code-editor/src/lg/modalityEditors/AttachmentModalityEditor.tsx
- Composer/packages/server/src/locales/en-US.json
Change carousal to carousel in LG Editor
Closes #7309
> fix: Change carousal to carousel in LG Editor

- Composer/packages/electron-server/package.json
> chore: bump to 2.0.0

- Composer/packages/client/src/recoilModel/dispatchers/lu.ts
- Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
- Composer/packages/client/src/recoilModel/parsers/luWorker.ts
- Composer/packages/client/src/recoilModel/parsers/types.ts
- Composer/packages/client/src/recoilModel/parsers/workers/luParser.worker.ts
- Composer/packages/client/src/recoilModel/selectors/project.ts
- Composer/packages/lib/indexers/__tests__/luUtil.test.ts
- Composer/packages/lib/indexers/src/utils/luUtil.ts
- Composer/packages/types/src/settings.ts
when recognizer is Orchestrator, report entity error in LU file.
close #7151
> fix: Orchestrator report entity error

- templates.json
Updating templates.json to remove old display name mappings, as well as update the order to match the desired ordering of templates in the UI.
Fixes #7376.
N/A
> fix: templates.json update

- Composer/packages/client/src/utils/authClient.ts
Removed ARM & graph tokens on web app when user  signs out.
fixes #6561
> fix: Removed ARM & graph tokens on signout

- Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatLogContent.tsx
Show webchat inspector panel and hide the "Test in Webchat" link which helps discover the webchat panel when the webchat panel is opened the first time
Fixes #7513
> fix: Check for webchat panel visibility

- Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx
Changes the luis learn more link to the appropriate aka.ms link
Fixes #7525
> fix: correct luis link

- Composer/packages/client/src/pages/botProject/PublishTargets.tsx
- Composer/packages/client/src/pages/publish/Publish.tsx
Dialog was re-opening constantly due to hash in URL.
fixes #7492
N.A
> fix: Reopening of dialog due to hash

- Composer/packages/form-dialogs/src/FormDialogSchemaEditor.tsx
- Composer/packages/form-dialogs/src/atoms/appState.ts
- Composer/packages/form-dialogs/src/atoms/utils.ts
- Composer/packages/server/package.json
- Composer/packages/server/src/models/bot/botProject.ts
- Composer/yarn.lock
#minor
Update to the latest generator.
This required changing from .schema to .template and changing the calling arguments.
> chore: Update to the latest generator

- Composer/package.json
- Composer/yarn.lock
- extensions/packageManager/package.json
- extensions/packageManager/yarn.lock
This upgrades json-ptr in order to resolve a security issue.
#minor
> chore: upgrade json-ptr to 2.2

- Composer/packages/server/package.json
- Composer/packages/tools/language-servers/intellisense/package.json
- Composer/packages/tools/language-servers/language-generation/package.json
- Composer/packages/tools/language-servers/language-understanding/package.json
- Composer/yarn.lock
> chore: upgrade package ws from 5.0.0 to 7.4.6

- docs/1.3-supported-os.md
Per @cwhitten 
> The recommended OS versions are unchanged as of 1.3. We could modify this document to say something like 1.3 and above to be more correct.
- #minor
N/A
> docs: Rename article to be less confusing

- Composer/packages/lib/code-editor/src/LuEditor.tsx
- Composer/packages/lib/code-editor/src/lg/modalityEditors/AttachmentModalityEditor.tsx
- Composer/packages/lib/code-editor/src/lu/DefineEntityButton.tsx
- Composer/packages/lib/code-editor/src/lu/InsertEntityButton.tsx
- Composer/packages/lib/code-editor/src/lu/LuEditorToolbar.tsx
- Composer/packages/lib/code-editor/src/lu/__test__/DefineEntityButton.test.tsx
- Composer/packages/lib/code-editor/src/lu/__test__/entityDefinition.test.ts
- Composer/packages/lib/code-editor/src/lu/__test__/useListEntityValidation.test.ts
- Composer/packages/lib/code-editor/src/lu/dialogs/ListEntityCreationDialog.tsx
- Composer/packages/lib/code-editor/src/lu/dialogs/useListEntityValidation.ts
- Composer/packages/lib/code-editor/src/lu/types.ts
- Composer/packages/lib/code-editor/src/lu/utils/entityDefinition.ts
- Composer/packages/lib/code-editor/src/lu/utils/iconUtils.tsx
- Composer/packages/lib/code-editor/src/utils/luUtils.ts
- Composer/packages/lib/ui-shared/src/components/index.ts
- Composer/packages/lib/ui-shared/src/components/tags/ContentEditable.tsx
- Composer/packages/lib/ui-shared/src/components/tags/Tag.tsx
- Composer/packages/lib/ui-shared/src/components/tags/TagInput.tsx
- Composer/packages/lib/ui-shared/src/components/tags/utils.ts
- Composer/packages/server/src/locales/en-US.json
Adds list entity to LU editor toolbar
Adds list entity creation dialog to the LU editor
closes #7930 
closes #7931 
fixes #8020
> feat: Add list entity creation dialog to LU editor

- extensions/azurePublishNew/src/components/AzureProvisionWizard.tsx
- extensions/azurePublishNew/src/components/provisioningWizards/CreateResourcesWizard.tsx
- extensions/azurePublishNew/src/components/provisioningWizards/HandOffToAdminWizard.tsx
- extensions/azurePublishNew/src/components/provisioningWizards/ImportResourcesWizard.tsx
- extensions/azurePublishNew/src/components/provisioningWizards/steps/ResourceConfigurationStep.tsx
- extensions/azurePublishNew/src/components/resourceConfiguration/DeployLocationPicker.tsx
- extensions/azurePublishNew/src/components/resourceConfiguration/LuisRegionPicker.tsx
- extensions/azurePublishNew/src/components/resourceConfiguration/ResourceGroupPicker.tsx
- extensions/azurePublishNew/src/components/resourceConfiguration/ResourceNameTextField.tsx
- extensions/azurePublishNew/src/components/resourceConfiguration/SubscriptionPicker.tsx
- extensions/azurePublishNew/src/components/resourceConfiguration/TenantPicker.tsx
- extensions/azurePublishNew/src/components/shared/searchableDropdown/SearchableDropdown.tsx
- extensions/azurePublishNew/src/hooks/useResourceConfiguration.ts
- extensions/azurePublishNew/src/recoilModel/atoms/resourceConfigurationState.ts
- extensions/azurePublishNew/src/recoilModel/dispatchers/resourceConfigurationDispatcher.ts
- extensions/azurePublishNew/src/recoilModel/types.ts
Added implementation & validation for resource configuration step.
1. Added 'Create new' option for searchable dropdown.
2. Validation for new resource group
3. Persist the configuration to local  storage.
refs #7632 
refs #7631
> feat: Added implementation for ResourceConfigurationStep

- Composer/packages/lib/code-editor/src/lu/dialogs/ListEntityCreationDialog.tsx
Adds help url for list entity creation
#minor
> feat: Adds help url for list entity creation

- Composer/packages/adaptive-flow/src/adaptive-flow-editor/hooks/useEditorEventApi.ts
**Root cause**
composer doesn't support ctrl+v today, so if we use this shortcut will throw error for undefined selected actions in canvas.
**fix**
add ctrl+v behaviors. 
1. If some actions are selected, paste it to the end of the last selected action.
2. if there is no selected action, paste it to the end of the current dialog 
closes #7958
> fix: shortcuts for paste in canvas does not work

- Composer/packages/client/__tests__/recognizer.test.ts
- Composer/packages/client/src/recoilModel/Recognizers.tsx
- Composer/packages/client/src/recoilModel/dispatchers/recognizers.ts
- Composer/packages/server/src/models/bot/botProject.ts
- Composer/packages/server/src/models/bot/builder.ts
- Composer/packages/server/src/models/bot/interface.ts
- Composer/packages/server/src/models/settings/defaultSettingManager.ts
- Composer/packages/types/src/indexers.ts
- extensions/azurePublish/src/node/luisAndQnA.ts
add crosstrain settings to composer setting:
inner           Only performs the inner dialog cross train, default is true
intra            Only performs the intra dialog cross train, default is true
#minor
> fix: add options to support doing luis and qna cross-train separately

- .github/workflows/main.yml
Fixes yml error in github action.
> ci: fix yml syntax error

- Composer/packages/client/src/constants.tsx
- Composer/packages/lib/ui-shared/src/components/ProvisionHandoff/ProvisionHandoff.tsx
Minor fixes for UI bugs
fixes #8053 
fixes #7732
> fix: minor UI fixes in admin and create modal 

- Composer/packages/server/package.json
- Composer/yarn.lock
#minor
Update to the latest form generator.  
Switch substitutions to name in template directories to support external recognizers.
Fix dynamiclist without examples.
Fix logic for not generating array utterances.
Update comments for custom LU.
Add = to some expressions to work around Composer bug.
Make sure activity is everywhere.
> chore: Update to latest form generator

- Composer/packages/client/src/components/QnA/ImportQnAFromUrl.tsx
- Composer/packages/client/src/components/QnA/ReplaceQnAFromPortalModal.tsx
- Composer/packages/client/src/components/QnA/constants.ts
- Composer/packages/client/src/components/QnA/styles.ts
- Composer/packages/client/src/pages/knowledge-base/table-view.tsx
- Composer/packages/client/src/recoilModel/dispatchers/qna.ts
> refresh qna from qna portal

- Composer/packages/server/package.json
- Composer/yarn.lock
#minor
Update to the latest generator to pick up renaming and reorganization of trigger names.
> chore: Update generator to pick up renaming.

- Composer/packages/server/package.json
- Composer/yarn.lock
#minor
Update to the latest generator which added returning form results when end dialog is called.
> chore: Update form generator to add results to EndDialog

- extensions/azurePublish/src/components/azureProvisionDialog.tsx
- extensions/azurePublish/src/components/util.ts
Adds the default operating system recommendation per UX design: https://www.figma.com/file/J3oIdXDmeBQbAe4a4PYbQc/Jaskeerat's-files?node-id=5935%3A25
fixes #8063
> feat: Added recommended OS

- Composer/packages/server/src/models/bot/builder.ts
- Composer/packages/server/src/models/settings/defaultSettingManager.ts
**In this PR**
remove the downsampling field from the setting auto complete logic.
closes #7414
> fix: composer adds downsampling to appsettings.json

- extensions/azurePublishNew/src/api.ts
- extensions/azurePublishNew/src/components/provisioningWizards/steps/ResourceConfigurationStep.tsx
- extensions/azurePublishNew/src/components/resourceConfiguration/OperatingSystemChoiceGroup.tsx
- extensions/azurePublishNew/src/hooks/usePreferredAppServiceOS.ts
- extensions/azurePublishNew/src/hooks/usePublishProfileInitializer.ts
- extensions/azurePublishNew/src/hooks/useResourceConfiguration.ts
- extensions/azurePublishNew/src/recoilModel/atoms/handOffToAdminState.ts
- extensions/azurePublishNew/src/recoilModel/atoms/importConfigurationState.ts
- extensions/azurePublishNew/src/recoilModel/atoms/resourceConfigurationState.ts
- extensions/azurePublishNew/src/recoilModel/dispatchers/resourceConfigurationDispatcher.ts
- extensions/azurePublishNew/src/types/index.ts
1. Modified recoil key format to camelCase.
2. Added API implementations.
3. Added operating system selection on ResourceConfigurationStep 
- #8063 
- #8150
refs #7632
> feat: Added api implementation & added operating system control in ResourceConfigurationStep

- Composer/packages/integration-tests/cypress/integration/HomePage.spec.ts
Fix broken integration test in main. 
#minor
> fix: integration test to fill out dropdown

- extensions/azurePublishNew/src/node/availableResources.ts
- extensions/azurePublishNew/src/node/azureResources/cosmosDb.ts
- extensions/azurePublishNew/src/node/azureResources/types.ts
implement cosmosdb provision service
refs #7629
> feat: implement cosmosdb provision

- Composer/packages/electron-server/src/auth/oneAuthService.ts
apply existing error handling logic from the access token function to the ARM token function
fixes #7783
> fix: handle interactionrequired error during Arm token request

- extensions/azurePublishNew/src/node/availableResources.ts
- extensions/azurePublishNew/src/node/index.ts
- extensions/azurePublishNew/src/node/types.ts
Added a progress callback for resource provisioning services and wired up to the current job.
Via closure, resources don't have to know about the process ID.
#minor
related to #8066
N/A
> feat: Added provision progress callback

- Composer/packages/server/package.json
- Composer/yarn.lock
Update `@microsoft/bf-orchestrator` to `4.14.0-rc0`.  
#minor
> chore: Update orchestratorlib to 4.14.0-rc0

- Composer/packages/client/src/components/CreationFlow/TemplateDetailView.tsx
Fix version selection bug caused by memoized function
#minor
> fix: version button render issue

- Composer/packages/adaptive-form/src/components/FormTitle.tsx
Fixes an issue where the designer property is undefined.
fixes #8234
> fix: protect against $designer being undefined

- Composer/packages/client/src/components/CreationFlow/DefineConversation.tsx
- Composer/packages/server/src/locales/en-US.json
Re-adding the default to web app for runtime type
fixes #8135
N/A
> feat: Reverted to having web apps be default

- Composer/packages/server/package.json
- Composer/yarn.lock
#minor 
Update to the latest generator.
* Remove prefixes
* Update LU to support intellisense
* Fix activity parameters
> chore: update form generator

- Composer/packages/client/__tests__/pages/botProjectsSettings/BotProjectSettings.test.tsx
- Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
Fixes editor height in advanced settings
fixes #8256
> fix: Editor height in advanced settings

- .github/CODEOWNERS
Adding Natalie and Vamsi as approved code reviewers for publish and composer general dirs
#minor
> chore: Adding Natalie and Vamsi as certified code reviewers 

- extensions/azurePublish/package.json
- extensions/azurePublish/src/node/deploy.ts
- extensions/azurePublish/src/node/luisAndQnA.ts
- extensions/azurePublish/src/node/provision.ts
- extensions/azurePublish/yarn.lock
Changed request-promise api calls to axios in azurePublish extension.
fixes #8281
> chore: Removed request-promise dep in favor of axios

- Composer/packages/client/__tests__/pages/knowledge-base/CreateQnAModal.test.tsx
- Composer/packages/client/__tests__/pages/knowledge-base/ReplaceQnAFromModal.test.tsx
- Composer/packages/client/src/components/Notifications/__tests__/NotificationCard.test.tsx
- Composer/packages/client/src/components/QnA/CreateQnAFromQnAMaker.tsx
- Composer/packages/client/src/components/QnA/CreateQnAFromUrl.tsx
- Composer/packages/client/src/components/QnA/CreateQnAModal.tsx
- Composer/packages/client/src/components/QnA/EditQnAFromScratchModal.tsx
- Composer/packages/client/src/components/QnA/EditQnAFromUrlModal.tsx
- Composer/packages/client/src/components/QnA/ImportQnAFromUrl.tsx
- Composer/packages/client/src/components/QnA/PersonalCard.tsx
- Composer/packages/client/src/components/QnA/ReplaceQnAFromModal.tsx
- Composer/packages/client/src/components/QnA/constants.ts
- Composer/packages/client/src/components/QnA/styles.ts
- Composer/packages/client/src/pages/knowledge-base/table-view.tsx
- Composer/packages/client/src/recoilModel/dispatchers/__tests__/mocks/mockProjectResponse.json
- Composer/packages/client/src/recoilModel/dispatchers/provisionQNA.ts
- Composer/packages/client/src/utils/notifications.ts
- Composer/packages/client/src/utils/qnaUtil.ts
- QnA import with global auth
- Replace 'KB' with 'knowledge base'
#minor
> fix: QnA import with global auth 

- extensions/azurePublishNew/src/components/AzureProvisionWizard.tsx
- extensions/azurePublishNew/src/components/provisioningWizards/steps/PublishConfigEditorStep.tsx
- extensions/azurePublishNew/src/components/shared/searchableDropdown/SearchableDropdown.tsx
- extensions/azurePublishNew/src/components/shared/searchableDropdown/SearchableDropdownTextField.tsx
1. Fixes width issue on the JSON editor.
2. Fixes the below issue with the searchable dropdown.
when user filters the dropdown items and selects an item and clears the selection, input box in the dropdown will show 
random text.
refs #7632 
refs #7631
> fix: Fixes few issues in the new azurePublishNew Extension

- extensions/azurePublishNew/src/node/availableResources.ts
- extensions/azurePublishNew/src/node/azureResources/luisPrediction.ts
- extensions/azurePublishNew/src/node/azureResources/types.ts
Implementing luis prediction provision method.
Work in progress for new azure provisioning service layer (this code is not live to customers yet). 
refs #7629
> feat: provisioning luis prediction

- extensions/azurePublish/src/components/azureProvisionDialog.tsx
Placeholder text will be shown as 'Loading ...' when the call to server is still in progress.
Fixes #8341
> fix: added loading state to the subscriptions dropdown

- extensions/azurePublishNew/src/node/availableResources.ts
- extensions/azurePublishNew/src/node/azureResources/resourceGroup.ts
implement resourceGroup provisioning
refs #7629
> feat: implement resourceGroup provisioning

- Composer/jest.config.js
- Composer/packages/lib/indexers/__tests__/botIndexer.test.ts
- Composer/packages/lib/indexers/__tests__/formDialogSchemaIndexer.test.ts
- Composer/packages/lib/indexers/__tests__/luIndexer.test.ts
- Composer/packages/lib/indexers/__tests__/luUtil.test.ts
- Composer/packages/lib/indexers/src/botIndexer.ts
For some unknown reason, @bfc/indexers test were not running, this PR adds them back and fixes the tests.
closes #8329
> fix: Adds indexers unit test back and fixes them

- extensions/azurePublishNew/src/node/availableResources.ts
- extensions/azurePublishNew/src/node/azureResources/azureFunctions.ts
- extensions/azurePublishNew/src/node/provisioning.ts
rename azure function to azure functions
refs #7629
> fix: rename azure function to azure functions

- Composer/packages/lib/code-editor/src/lu/hooks/useLabelingMenuItems.tsx
Show list entity in insert entity menu
fixes #8371
> fix: Show list entity in insert entity menu

- Composer/packages/ui-plugins/composer/src/index.ts
Added the "dialogs" property to the hidden list for Adaptive Dialog
Closes #8387
> fix: hide dialogs property for AdaptiveDialog component

- Composer/packages/lib/code-editor/src/lu/hooks/useMonacoSelectedTextDom.tsx
- Composer/packages/ui-plugins/prompts/src/ExpectedResponsesField.tsx
Fixes LU editor placeholder format
Fixes a potential crash when editor is unmounted and has text selected.
#minor
> fix: fixes LU editor placeholder format & potential crash

- Composer/packages/client/src/recoilModel/utils/skill.ts
- Composer/packages/lib/shared/src/dialogFactory.ts
> fix: set BeginSkill initial value allowInterruptions: 'false',

- Composer/packages/adaptive-form/src/components/SchemaField.tsx
- Composer/packages/adaptive-form/src/components/fields/RecognizerField/RecognizerField.tsx
fix: New Recognizer selection text too large
closes #8385
> fix: New Recognizer selection text too large

- Composer/packages/server/package.json
- Composer/yarn.lock
#minor
Update to the latest generator to remove @ from LU files to match the expectations of LU intellisense.
> chore: Update to latest generator to remove @ from LU labels

- Composer/packages/client/src/components/AddRemoteSkillModal/SelectIntent.tsx
import fuzzy matched locale lu intent from PVA bot
Closes #8411
> fix: import fuzzy matched locale intent from PVA bot

- Composer/packages/electron-server/src/auth/oneAuthService.ts
- Composer/packages/server/src/externalContentProvider/__tests__/powerVirtualAgentsProvider.test.ts
- Composer/packages/server/src/externalContentProvider/powerVirtualAgentsProvider.ts
- Composer/packages/types/src/auth.ts
- extensions/pvaPublish/src/node/constants.ts
- extensions/pvaPublish/src/node/publish.ts
- extensions/pvaPublish/src/node/utils.spec.ts
- extensions/pvaPublish/src/node/utils.ts
This PR enable support for importing and publishing PVA bots from the GCC High environment (https://high.powerva.microsoft.us/)
Fixes #8214 
**Import:**
**Publish:**
> feat: Added support to import / publish flows for PVA GCC High env

- Composer/packages/adaptive-flow/src/adaptive-flow-renderer/adaptive/AdaptiveTrigger.tsx
- Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/TriggerSummary/TriggerSummary.tsx
- Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx
- Composer/packages/client/src/components/ProjectTree/treeItem.tsx
- Composer/packages/lib/shared/src/icons.ts
- Composer/packages/ui-plugins/luis/src/TriggerWidget/TriggerWidget.tsx
- Remove mulitple project levels in the tree.
- Update trigger widget UI to remove hyphens and handle click event on the trigger widget
> Project tree visual update and trigger phrase node

- Composer/packages/client/src/plugins.ts
- Composer/packages/client/src/plugins/question/index.ts
- Composer/packages/client/src/recoilModel/dispatchers/utils/PVADefs.ts
- Composer/packages/client/src/recoilModel/dispatchers/utils/project.ts
- Composer/packages/client/src/recoilModel/persistence/PVAUtils.ts
- Composer/packages/client/src/recoilModel/persistence/http.ts
- Composer/packages/client/src/recoilModel/selectors/diagnosticsPageSelector.ts
- Composer/packages/extension-client/src/hooks/useFormConfig.ts
- Composer/packages/extension-client/src/types/extension.ts
- Composer/packages/lib/shared/src/dialogFactory.ts
- Composer/packages/server/src/controllers/project.ts
Also adds a transformation layer when reading / writing to disk that takes PVA $kinds and transforms into BF $kinds. It's a WIP.
> add initial question ui plugin

- Composer/packages/client/src/components/Header.tsx
- Composer/packages/client/src/components/autoSaveIndicator.tsx
- Composer/packages/client/src/constants.tsx
- Composer/packages/client/src/pages/design/DesignPage.tsx
- Composer/packages/client/src/recoilModel/atoms/appState.ts
- Composer/packages/client/src/recoilModel/dispatchers/application.ts
- Composer/packages/client/src/recoilModel/dispatchers/project.ts
- Composer/packages/client/src/utils/triggerAutoSave.ts
Adds a UI indicator for when auto save is triggered.
> Added auto save indicator in header

- Composer/packages/client/public/index.html
- Composer/packages/client/src/components/TriggerCreationModal/resolveTriggerWidget.tsx
- Composer/packages/lib/code-editor/src/LuEditor.tsx
- Composer/packages/lib/code-editor/src/lg/modalityEditors/StringArrayEditor.tsx
- Composer/packages/lib/code-editor/src/lg/modalityEditors/StringArrayItem.tsx
- Composer/packages/lib/code-editor/src/lu/LuListEditor.tsx
- Composer/packages/ui-plugins/luis/src/LuisIntentEditor.tsx
feat: Add LuListEditor to the TriggerWidget and Form Editor
> feat: Add LuListEditor to the TriggerWidget and Form Editor

- Composer/packages/client/src/components/Toolbar.tsx
- Composer/packages/client/src/components/WebChat/utils/conversationService.ts
- Composer/packages/server/src/controllers/project.ts
Some minor fixes around the Web Chat testing integration with PVA and serializing bot assets
> Minor fixes for Web Chat integration and bot asset serialization

- Composer/packages/lib/code-editor/package.json
- Composer/packages/lib/code-editor/src/lg/AdaptiveCardRenderer.tsx
- Composer/packages/lib/code-editor/src/lg/LgAdaptiveCardEditor.tsx
- Composer/packages/lib/code-editor/src/lg/LgCodeEditor.tsx
- Composer/packages/lib/code-editor/src/lg/utils.ts
- Composer/yarn.lock
demo: Add adaptive card renderer to pop out editor
https://user-images.githubusercontent.com/17039790/131182961-a1751597-7a7a-46a0-90f2-db63c0d5168d.mp4
> demo: Add adaptive card renderer to pop out editor

- extensions/azurePublish/src/node/azureResourceManager/azureResourceManager.ts
- extensions/azurePublish/src/node/provision.ts
give the qna maker service plan a unique name
fixes #8427
> fix: give the qna maker service plan a unique name

- extensions/azurePublish/src/node/luisAndQnA.ts
Add helpful debugging info when an error is thrown during the Luis binding step
refs #8379
> fix: add additional info to Luis error message logging

- Composer/package.json
- Composer/packages/client/package.json
- Composer/yarn.lock
- extensions/mongoStorage/package.json
- extensions/mongoStorage/yarn.lock
Addresses CVE-2021-23436 & CVE-2021-23438
> chore: address critical security alerts

- extensions/azurePublish/package.json
- extensions/azurePublish/yarn.lock
- extensions/azurePublishNew/package.json
- extensions/azurePublishNew/yarn.lock
- extensions/samples/assets/shared/scripts/package.json
Upgrade Azure SDK package to support Composer created bot show 'Open In Composer' in Azure.
refs #minor
close https://github.com/microsoft/BotFramework-Services/issues/313
> feat: Composer created bot show 'Open In Composer' in Azure

- Composer/.eslintrc.js
- Composer/.eslintrc.react.js
- Composer/package.json
resolves https://msazure.visualstudio.com/DefaultCollection/One/_queries/edit/12409099/?triage=true
#minor
> chore: Adds eslint-plugin-security to lint rulesets

- Composer/package.json
- Composer/yarn-berry.lock
- Composer/yarn.lock
This updates `url-parse` package to the latest version as it fixes a number of CVEs
#minor
> chore: update url-parse to 1.5.10

- azure-pipelines.yml
> Attempt to fix cypress caching

- Composer/packages/integration-tests/package.json
- Composer/packages/integration-tests/scripts/e2e-ci.sh
- azure-pipelines.yml
Working around npx can't find the right binary
> Attempt to fix Cypress caching #2

- .config/tsaoptions.json
TSA config. CodeQL to be enabled in the Azure pipeline
#minor
> chore: Enable CodeQL and TSA

- Composer/packages/client/src/pages/language-generation/LGPage.tsx
- Composer/packages/client/src/pages/language-generation/table-view.tsx
- Composer/packages/client/src/recoilModel/DispatcherWrapper.tsx
- Composer/packages/client/src/recoilModel/parsers/workers/lgParser.worker.ts
This is the first version of the fix for the issue causing Composer to crash when the project contains a large number of LG files.
- Skipped initial _ParseAll_ process for LG files.
- Added parsing logic when the file is required in _LGPage_ and _table-view_ components (Bot Responses view).
#minor
This image shows the LG files being parsed when required by the _Bot Responses_ view.
> fix: [Composer crash issue] Parse LG files when required
